import { Types } from 'mongoose';
import { Document } from '../../database/models/Document.js';
import { AuthorizationService } from '../../core/authorization/authorization.service.js';
import { ResourceScopeService } from '../../core/authorization/resource-scope.service.js';
import { AppError } from '../../core/errors/AppError.js';
import { AuditService } from '../audit/audit.service.js';
import type { AuthenticatedUser } from '../../core/types/auth.js';
import type { createDocumentSchema, updateDocumentSchema } from './document.schemas.js';
import type { z } from 'zod';

type CreateInput=z.infer<typeof createDocumentSchema>; type UpdateInput=z.infer<typeof updateDocumentSchema>;
const oid=(v:string)=>new Types.ObjectId(v);
export class DocumentService {
  private static async authorize(auth:AuthenticatedUser, doc:{organizationId:Types.ObjectId;propertyId?:Types.ObjectId|null;buildingId?:Types.ObjectId|null;floorId?:Types.ObjectId|null;unitId?:Types.ObjectId|null;ownerUserId?:Types.ObjectId|null}, permission:string){
    if(doc.unitId){ResourceScopeService.assertUnit(auth,{_id:doc.unitId,organizationId:doc.organizationId,propertyId:doc.propertyId!,buildingId:doc.buildingId!},permission,doc.ownerUserId);return;}
    if(doc.propertyId){await ResourceScopeService.assertProperty(auth,{_id:doc.propertyId,organizationId:doc.organizationId},permission);return;}
    AuthorizationService.assertPermission(auth,permission,doc.organizationId);
  }
  static async list(auth:AuthenticatedUser,organizationId:string){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'document.view',org);const ids=await ResourceScopeService.scopedUnitIds(auth,org);const filter:Record<string,unknown>={organizationId:org,status:{$ne:'ARCHIVED'}};if(ids)filter.$or=[{unitId:{$in:ids}},{unitId:{$exists:false}}];if(auth.memberships.some(m=>String(m.organizationId)===String(org)&&m.roles.includes('TENANT'))&&!auth.isPlatformAdmin)filter.$and=[{ $or:[{visibility:'TENANT'},{ownerUserId:auth.userId}] }];return Document.find(filter).sort({createdAt:-1}).lean();}
  static async get(auth:AuthenticatedUser,id:string){if(!Types.ObjectId.isValid(id))throw new AppError(400,'INVALID_ID','Invalid document id');const doc=await Document.findById(id);if(!doc)throw new AppError(404,'DOCUMENT_NOT_FOUND','Document not found');await this.authorize(auth,doc,'document.view');if(!auth.isPlatformAdmin&&auth.memberships.some(m=>String(m.organizationId)===String(doc.organizationId)&&m.roles.includes('TENANT'))){if(doc.visibility!=='TENANT'&& !doc.ownerUserId?.equals(auth.userId))throw new AppError(403,'DOCUMENT_RESTRICTED','Document is not visible to this tenant');}else if(doc.visibility==='PRIVATE'&&!auth.isPlatformAdmin&&!doc.ownerUserId?.equals(auth.userId))throw new AppError(403,'DOCUMENT_PRIVATE','Document is private');return doc;}
  static async create(auth:AuthenticatedUser,organizationId:string,data:CreateInput){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'document.manage',org);if(data.propertyId){const property=await ResourceScopeService.assertPropertyExistsInOrganization(data.propertyId,org);await ResourceScopeService.assertProperty(auth,property,'document.manage');}if(data.buildingId){const building=await ResourceScopeService.assertBuildingExistsInOrganization(data.buildingId,org);if(data.propertyId&&String(building.propertyId)!==data.propertyId)throw new AppError(400,'HIERARCHY_MISMATCH','Building does not belong to property');await ResourceScopeService.assertBuilding(auth,building,'document.manage');}if(data.floorId){const floor=await ResourceScopeService.assertFloorExistsInOrganization(data.floorId,org);if(data.buildingId&&String(floor.buildingId)!==data.buildingId)throw new AppError(400,'HIERARCHY_MISMATCH','Floor does not belong to building');}if(data.unitId){const unit=await ResourceScopeService.assertUnitExistsInOrganization(data.unitId,org);ResourceScopeService.assertUnit(auth,unit,'document.manage',data.ownerUserId?oid(data.ownerUserId):undefined);if(data.propertyId&&String(unit.propertyId)!==data.propertyId)throw new AppError(400,'HIERARCHY_MISMATCH','Unit does not belong to property');if(data.buildingId&&String(unit.buildingId)!==data.buildingId)throw new AppError(400,'HIERARCHY_MISMATCH','Unit does not belong to building');if(data.floorId&&String(unit.floorId)!==data.floorId)throw new AppError(400,'HIERARCHY_MISMATCH','Unit does not belong to floor');}else if(data.propertyId===undefined&&data.buildingId===undefined){AuthorizationService.assertPermission(auth,'document.manage',org);}
    const doc=await Document.create({organizationId:org,...data,propertyId:data.propertyId?oid(data.propertyId):undefined,buildingId:data.buildingId?oid(data.buildingId):undefined,floorId:data.floorId?oid(data.floorId):undefined,unitId:data.unitId?oid(data.unitId):undefined,ownerUserId:data.ownerUserId?oid(data.ownerUserId):undefined,createdBy:auth.userId,updatedBy:auth.userId});await AuditService.record({organizationId:org,actorUserId:auth.userId,action:'document.created',resourceType:'Document',resourceId:doc._id,propertyId:doc.propertyId,buildingId:doc.buildingId,unitId:doc.unitId,after:doc.toObject()});await AuditService.publish({organizationId:org,name:'document.created',aggregateType:'Document',aggregateId:doc._id,actorUserId:auth.userId,payload:{category:doc.category,title:doc.title}});return doc;}
  static async update(auth:AuthenticatedUser,id:string,data:UpdateInput){const doc=await Document.findById(id);if(!doc)throw new AppError(404,'DOCUMENT_NOT_FOUND','Document not found');await this.authorize(auth,doc,'document.manage');const before=doc.toObject();Object.assign(doc,data,{updatedBy:auth.userId});await doc.save();await AuditService.record({organizationId:doc.organizationId,actorUserId:auth.userId,action:'document.updated',resourceType:'Document',resourceId:doc._id,propertyId:doc.propertyId,buildingId:doc.buildingId,unitId:doc.unitId,before,after:doc.toObject()});return doc;}
}
