import type {Request,Response} from 'express'; import {apiResponse} from '../../core/response/apiResponse.js'; import * as S from './model-serving.schemas.js'; import {ModelServingService} from './model-serving.service.js'; import {requiredParam} from '../../core/http/params.js';
export const policy=async(req:Request,res:Response)=>res.json(apiResponse(await ModelServingService.policy(req.auth!,requiredParam(req.params.organizationId,'organizationId'))));
export const updatePolicy=async(req:Request,res:Response)=>res.json(apiResponse(await ModelServingService.updatePolicy(req.auth!,requiredParam(req.params.organizationId,'organizationId'),S.servingPolicySchema.parse(req.body))));
export const deploy=async(req:Request,res:Response)=>res.status(201).json(apiResponse(await ModelServingService.deploy(req.auth!,requiredParam(req.params.organizationId,'organizationId'),S.deploymentSchema.parse(req.body))));
export const rollback=async(req:Request,res:Response)=>res.json(apiResponse(await ModelServingService.rollback(req.auth!,requiredParam(req.params.organizationId,'organizationId'),S.rollbackSchema.parse(req.body))));
export const deployments=async(req:Request,res:Response)=>res.json(apiResponse(await ModelServingService.listDeployments(req.auth!,requiredParam(req.params.organizationId,'organizationId'),S.servingQuerySchema.parse(req.query).limit)));
export const monitor=async(req:Request,res:Response)=>res.json(apiResponse(await ModelServingService.monitor(req.auth!,requiredParam(req.params.organizationId,'organizationId'),S.monitorSchema.parse(req.body))));
export const monitoring=async(req:Request,res:Response)=>{const q=S.servingQuerySchema.parse(req.query);return res.json(apiResponse(await ModelServingService.listMonitoring(req.auth!,requiredParam(req.params.organizationId,'organizationId'),q.domain,q.limit)));};

export const requestApproval=async(req:Request,res:Response)=>res.status(201).json(apiResponse(await ModelServingService.requestApproval(req.auth!,requiredParam(req.params.organizationId,'organizationId'),S.approvalRequestSchema.parse(req.body))));
export const decideApproval=async(req:Request,res:Response)=>res.json(apiResponse(await ModelServingService.decideApproval(req.auth!,requiredParam(req.params.approvalId,'approvalId'),S.approvalDecisionSchema.parse(req.body))));
export const approvals=async(req:Request,res:Response)=>res.json(apiResponse(await ModelServingService.listApprovals(req.auth!,requiredParam(req.params.organizationId,'organizationId'),S.servingQuerySchema.parse(req.query).limit)));
export const incidents=async(req:Request,res:Response)=>{const q=S.incidentQuerySchema.parse(req.query);return res.json(apiResponse(await ModelServingService.listIncidents(req.auth!,requiredParam(req.params.organizationId,'organizationId'),q)));};
export const updateIncident=async(req:Request,res:Response)=>res.json(apiResponse(await ModelServingService.updateIncident(req.auth!,requiredParam(req.params.incidentId,'incidentId'),S.incidentUpdateSchema.parse(req.body))));
