import { Types } from 'mongoose';
import { Contractor } from '../../database/models/Contractor.js';
import { MaintenanceRequest } from '../../database/models/MaintenanceRequest.js';
import { AuthorizationService } from '../../core/authorization/authorization.service.js';
import { ResourceScopeService } from '../../core/authorization/resource-scope.service.js';
import { AppError } from '../../core/errors/AppError.js';
import type { AuthenticatedUser } from '../../core/types/auth.js';
import type { CreateContractorInput, UpdateContractorInput } from './contractor.schemas.js';
export class ContractorService {
 static async list(auth:AuthenticatedUser,organizationId:string){const orgId=new Types.ObjectId(organizationId);AuthorizationService.assertPermission(auth,'contractor.view',orgId);const membership=auth.memberships.find(m=>String(m.organizationId)===String(orgId));const isContractor=membership?.roles.includes('CONTRACTOR')&&!auth.isPlatformAdmin;const filter:Record<string,unknown>={organizationId:orgId};if(isContractor)filter.userId=new Types.ObjectId(auth.userId);return Contractor.find(filter).sort({name:1}).lean();}
 static async get(auth:AuthenticatedUser,id:string){const c=await Contractor.findById(id);if(!c)throw new AppError(404,'NOT_FOUND','Contractor not found');AuthorizationService.assertCan(auth,'contractor.view',{organizationId:c.organizationId});const membership=auth.memberships.find(m=>String(m.organizationId)===String(c.organizationId));if(membership?.roles.includes('CONTRACTOR')&&!auth.isPlatformAdmin&&(!c.userId||String(c.userId)!==String(auth.userId)))throw new AppError(403,'FORBIDDEN','Contractor access is limited to the authenticated contractor profile');return c;}
 static async create(auth:AuthenticatedUser,organizationId:string,data:CreateContractorInput){const orgId=new Types.ObjectId(organizationId);AuthorizationService.assertPermission(auth,'contractor.manage',orgId);return Contractor.create({...data,organizationId:orgId,createdBy:auth.userId,updatedBy:auth.userId});}
 static async update(auth:AuthenticatedUser,id:string,data:UpdateContractorInput){const c=await Contractor.findById(id);if(!c)throw new AppError(404,'NOT_FOUND','Contractor not found');AuthorizationService.assertPermission(auth,'contractor.manage',c.organizationId);Object.assign(c,data,{updatedBy:auth.userId});await c.save();return c;}
 static async performance(auth:AuthenticatedUser,id:string){const c=await this.get(auth,id);const jobs=await MaintenanceRequest.find({organizationId:c.organizationId,contractorId:c._id}).select('status quoteAmount approvedAmount actualAmount createdAt completedAt').lean();const completed=jobs.filter(j=>j.status==='COMPLETED'||j.status==='VERIFIED'||j.status==='CLOSED');const durations=completed.filter(j=>j.completedAt).map(j=>j.completedAt!.getTime()-j.createdAt.getTime());const avgResponseMs=durations.length?durations.reduce((a,b)=>a+b,0)/durations.length:0;const variance=jobs.filter(j=>j.actualAmount!==undefined&&j.approvedAmount!==undefined);const overBudget=variance.filter(j=>(j.actualAmount??0)>(j.approvedAmount??0));return {contractorId:c._id,totalJobs:jobs.length,completedJobs:completed.length,completionRate:jobs.length?completed.length/jobs.length:0,averageCompletionHours:avgResponseMs/3600000,overBudgetJobs:overBudget.length,overBudgetRate:variance.length?overBudget.length/variance.length:0};}
}
