export const PERMISSIONS = ['sales.demo.manage','decision-intelligence.history.view','decision-intelligence.evaluate','decision-intelligence.action.manage','decision-intelligence.action.view','decision-intelligence.benchmark.view','decision-intelligence.view','intelligence.history.view','intelligence.evaluate','intelligence.alert.manage','intelligence.alert.view','command-center.view','decision-automation.view','decision-automation.evaluate','decision-automation.policy.manage','decision-automation.action.view','decision-automation.action.manage','decision-automation.tenant-risk.view','decision-automation.vacancy.view','predictive-learning.label.manage','predictive-learning.train','predictive-learning.model.view','predictive-learning.model.manage','model-serving.view','model-serving.policy.manage','model-serving.deployment.manage','model-serving.monitor.view','model-serving.approval.view','model-serving.approval.manage','model-serving.incident.view','model-serving.incident.manage',
  'organization.view','organization.update','organization.members.manage','organization.settings.manage','user.view','user.create','user.update','user.deactivate','role.view','role.create','role.update','role.delete','role.assign','permission.view','property.view','property.create','property.update','property.delete','building.view','building.create','building.update','building.delete','floor.view','floor.create','floor.update','floor.delete','unit.view','unit.create','unit.update','unit.assign','tenant.view','tenant.create','tenant.update','tenant.offboard','tenancy.view','tenancy.create','tenancy.update','tenancy.activate','tenancy.terminate','onboarding.view','onboarding.manage','move-out.view','move-out.manage','move-out.request','rent.view','rent.manage','rent.approve','payment.view','payment.create','payment.confirm','payment.reverse','expense.view','expense.create','expense.approve','expense.pay','service-charge.view','service-charge.manage','arrears.view','arrears.manage','financial.report.view','financial.report.export','financial.period.view','financial.period.manage','maintenance.view','maintenance.create','maintenance.assign','maintenance.quote','maintenance.approve','maintenance.close','maintenance.policy.view','maintenance.policy.manage','inspection.view','inspection.create','inspection.complete','inventory.view','inventory.create','inventory.update','contractor.view','contractor.manage','contractor.performance.view','financial.view','financial.manage','cctv.view','cctv.playback','cctv.download','cctv.manage','security-event.view','security-event.manage','access-point.view','access-point.manage','access-event.view','access-event.ingest','incident.view','incident.manage','document.view','document.manage','document.download','evidence.view','evidence.create','evidence.manage','evidence.download','notification.view','notification.manage','announcement.manage','job.view','job.manage','report.view','audit.view','staff.manage','billing.plan.view','billing.plan.manage','billing.subscription.view','billing.subscription.manage','billing.invoice.view','billing.invoice.manage','billing.usage.view','billing.usage.manage','billing.entitlement.view','billing.entitlement.manage','integration.view','integration.manage','integration.webhook.view','integration.webhook.manage','admin.manage'
] as const;

export type PermissionKey = typeof PERMISSIONS[number];

export const PERMISSION_META = PERMISSIONS.map((key) => {
  const segments = key.split('.');
  const action = segments.pop()!;
  const resource = segments.join('.');
  return { key, name: key.replace(/[.-]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()), resource, actions: [action], description: `${action} access for ${resource}` };
});
