'use client';

import { motion } from 'motion/react';
import {
  AlertTriangle, ArrowRight, Banknote, Building2, Camera, Check, CircleDollarSign,
  Clock3, FileCheck2, FileImage, Fingerprint, Gauge, KeyRound, Landmark, MapPin, ScanEye,
  ShieldCheck, Sparkles, TrendingUp, UserCheck, UsersRound, Wrench,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import {
  ActionQueueDemo, ApprovalDemo, AuditTrailDemo, CameraWallDemo, ChaosDemo,
  ContractorDemo, FinancialFlowDemo, HealthScoreDemo, MaintenanceWorkflowDemo,
  OnboardingDemo, PortfolioCommandCenterDemo, PropertyPassportDemo, RoleAccessDemo,
  VacancyDemo,
} from '../demos/product-demos';
import styles from './landing.module.css';

function Reveal({children,className=''}:{children:React.ReactNode;className?:string|undefined}) {
  return <motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} transition={{duration:.65,ease:[.2,.8,.2,1]}} viewport={{once:true,margin:'-10%'}}>{children}</motion.div>;
}

function Chapter({number,eyebrow,title,copy,children,id,tone='light'}:{number:string;eyebrow:string;title:React.ReactNode;copy?:string;children:React.ReactNode;id?:string|undefined;tone?:'light'|'dark'|'copper'}) {
  return <section id={id} className={`${styles.chapter} ${styles[`tone${tone[0]!.toUpperCase()}${tone.slice(1)}`]}`}><div className={styles.container}><Reveal className={styles.chapterIntro}><div className={styles.chapterIndex}>{number}</div><div><span className={styles.eyebrow}>{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div></Reveal>{children}</div></section>;
}

export function ChaosToControl() {
  return <><Chapter number="01" eyebrow="The old way is broken" title={'Your property should not be managed from phone calls, spreadsheets and “I’ll check.”'} copy="Rent. Repairs. Contractors. Access. Cameras. Tenants. Expenses. Incidents. When the truth lives in six places, the owner is always asking somebody else what is happening." id="product"><Reveal><ChaosDemo/></Reveal></Chapter>
  <section className={styles.controlBand}><div className={styles.container}><div className={styles.beforeAfter}><Reveal><span className={styles.eyebrow}>Dependency</span><h2>Call. Wait. Search. Ask. Verify.</h2><ul>{['Call the caretaker','Search WhatsApp','Ask the accountant','Request CCTV footage','Find the receipt'].map(item=><li key={item}><Clock3 size={15}/>{item}</li>)}</ul></Reveal><div className={styles.transformLine}><motion.i initial={{scaleY:0}} whileInView={{scaleY:1}} viewport={{once:true}}/><ArrowRight size={20}/></div><Reveal><span className={styles.eyebrow}>Control</span><h2>See the operation yourself.</h2><ul>{['Portfolio live','Arrears visible','Approvals waiting','Evidence attached','Audit trail recorded'].map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul></Reveal></div></div></section></>;
}

export function CommandCenterShowcase() {
  return <Chapter number="02" eyebrow="Landlord command center" title="The operation, arranged around your attention." copy="A portfolio view should not ask you to study every record. It should surface the money, risks and decisions that need you." id="command-center" tone="dark"><Reveal className={styles.showcaseFrame}><PortfolioCommandCenterDemo/></Reveal><div className={styles.signalStrip}>{[['8','properties'],['126','units'],['117','occupied'],['9','vacant'],['3','decisions waiting']].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></Chapter>;
}

export function FinancialVisibility() {
  return <><Chapter number="03" eyebrow="Financial visibility" title={<>Know what you should receive.<br/>Know what arrived. Know what is missing.</>} copy="Expected rent becomes allocations, balances, arrears, statements and property-level performance. Every shilling has a source and a destination." id="finance"><div className={styles.twoCol}><Reveal><FinancialFlowDemo/></Reveal><Reveal className={styles.editorialList}><div><Banknote/><span><b>Rent and service charge</b>Collection history, receipts and balances.</span></div><div><Landmark/><span><b>Property performance</b>Expenses and P&amp;L in the right context.</span></div><div><AlertTriangle/><span><b>Expense signal</b>Riverside maintenance is 31% above its 90-day average.</span></div></Reveal></div></Chapter><section className={styles.vacancyBand}><div className={styles.container}><Reveal><span className={styles.eyebrow}>Vacancy is lost revenue</span><h2>Vacancy is not a number.<br/>It is money standing still.</h2></Reveal><VacancyDemo/></div></section></>;
}

export function MaintenanceStory() {
  return <Chapter number="04" eyebrow="Maintenance command center" title="A repair is a chain of responsibility." copy="From the resident's first photo to the owner's approval and final verification, each handoff is visible, timestamped and attributable." id="maintenance" tone="dark"><div className={styles.maintenanceLayout}><Reveal className={styles.stickyCopy}><div className={styles.issueCard}><span><Wrench size={17}/></span><div><small>RIVERSIDE · BLOCK B · UNIT 12</small><strong>Bathroom supply-line leak</strong><p>Tenant report · 3 images · High priority</p></div></div><blockquote>“Show me the evidence before I approve the invoice.”</blockquote></Reveal><MaintenanceWorkflowDemo/></div></Chapter>;
}

export function ApprovalAndPassport() {
  return <><Chapter number="05" eyebrow="Spending control" title="Nobody spends your money without accountability." copy="Thresholds can let routine work move while routing larger or unusual costs to the owner with the quote, context and evidence attached."><div className={styles.twoCol}><Reveal><ApprovalDemo/></Reveal><Reveal className={styles.thresholds}><div><span>KES 3,800</span><b>Within manager threshold</b><em>AUTO APPROVED</em></div><div><span>KES 27,500</span><b>Above KES 5,000 threshold</b><em>OWNER APPROVAL</em></div></Reveal></div></Chapter><Chapter number="06" eyebrow="Digital property passport" title="Every unit remembers everything." copy="A building should not have an undocumented history. Tenancies, inspections, repairs, assets, meter readings, documents and evidence stay attached to the property." tone="copper"><Reveal className={styles.passportFrame}><PropertyPassportDemo/></Reveal></Chapter></>;
}

export function TenantAndRoleControl() {
  return <><Chapter number="07" eyebrow="Controlled onboarding" title="No confusion about who belongs where." copy="Staff assigns the verified phone number to the tenancy first. The resident verifies by OTP and the correct unit appears automatically."><div className={styles.onboardingLayout}><Reveal><OnboardingDemo/></Reveal><Reveal className={styles.guardrail}><KeyRound size={26}/><strong>The tenant never chooses their house manually.</strong><p>The verified backend tenancy decides what they can see. Unknown numbers enter a controlled access-request workflow.</p></Reveal></div></Chapter><Chapter number="08" eyebrow="Role-based control" title="Everyone sees what they need. Nothing more." copy="The same operation becomes a different, tightly scoped workspace for an owner, manager, caretaker, resident, contractor or platform administrator." id="roles" tone="dark"><Reveal><RoleAccessDemo/></Reveal></Chapter></>;
}

export function SecurityStory() {
  return <><Chapter number="09" eyebrow="CCTV and security" title="Security should not live in another system." copy="Authorized cameras, motion events, incidents and evidence become part of the same property history as maintenance, people and access." id="security" tone="dark"><Reveal><CameraWallDemo/></Reveal></Chapter><Chapter number="10" eyebrow="Accountable surveillance" title="Even watching the cameras leaves a record." copy="Camera access can be restricted by property, building and role. Sensitive viewing, playback and evidence actions remain attributable."><div className={styles.twoCol}><Reveal><AuditTrailDemo/></Reveal><Reveal className={styles.securityPromise}><ScanEye size={32}/><h3>Permission before playback.</h3><p>Caretakers only see explicitly permitted cameras in their assigned buildings. Evidence export can require a stronger identity check.</p></Reveal></div></Chapter><section className={styles.incidentBand}><div className={styles.container}><Reveal><span className={styles.eyebrow}>Incident to evidence</span><h2>A signal becomes a case.<br/>A case becomes a preserved record.</h2></Reveal><div className={styles.incidentFlow}>{['Motion detected','Event created','Incident opened','Footage attached','Manager notified','Evidence preserved','Resolved'].map((item,index)=><motion.div key={item} initial={{opacity:.25}} whileInView={{opacity:1}} viewport={{amount:.8}}><span>{String(index+1).padStart(2,'0')}</span><b>{item}</b>{index<6&&<i/>}</motion.div>)}</div></div></section></>;
}

export function EvidenceAndContractors() {
  const evidence=[['12:04','Tenant report'],['12:05','Photo uploaded'],['12:17','Caretaker acknowledged'],['14:11','Contractor arrived'],['14:14','Before image'],['16:48','Repair completed'],['16:51','Invoice uploaded'],['17:16','Tenant verified']];
  return <><Chapter number="11" eyebrow="Evidence, not stories" title={'Replace “he said, she said” with a timeline.'} copy="The record is not a summary written later. It is the work itself, captured as it happens."><div className={styles.evidenceTimeline}>{evidence.map(([time,event],index)=><motion.div key={time} initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} transition={{delay:index*.05}} viewport={{once:true}}><time>{time}</time><span><FileImage size={15}/></span><b>{event}</b></motion.div>)}</div></Chapter><Chapter number="12" eyebrow="Contractor accountability" title="Know who actually performs." copy="Response time, completion time, cost history, rework and resident feedback come from completed work, not promises." tone="copper"><div className={styles.twoCol}><Reveal><ContractorDemo/></Reveal><Reveal className={styles.contractorChart}><span>REWORK RATE</span>{[8,3,5].map((value,index)=><div key={index}><i><b style={{width:`${value*8}%`}}/></i><strong>{value}%</strong></div>)}</Reveal></div></Chapter></>;
}

export function RemoteAndIntelligence() {
  const properties=[['Westlands','Healthy','green'],['Kilimani','2 maintenance alerts','orange'],['Thika','4 arrears','red'],['Ruiru','Security event','red'],['Karen','100% occupied','green']];
  const signals=[['MAINTENANCE','Plumbing repairs in Block B occurred 4 times in 60 days.','Inspect the main water line.'],['ARREARS','5 tenants account for 71% of current arrears.','Prioritize structured follow-up.'],['VACANCY','Unit A-04 has been vacant for 46 days.','Estimated loss · KES 69,000'],['EXPENSE','Electrical maintenance is 24% above portfolio average.','Review repeat call-outs.']];
  return <><section className={styles.remoteBand} id="intelligence"><div className={styles.container}><Reveal className={styles.remoteCopy}><span className={styles.eyebrow}>Remote property control</span><h2>Your buildings are physical.<br/>Your control does not have to be.</h2><p>Every property reports into the same operational picture, even when you are nowhere near it.</p></Reveal><div className={styles.propertyMap}><div className={styles.mapLines}/>{properties.map(([name,status,tone],index)=><motion.div key={name} className={styles.mapNode} data-tone={tone} initial={{opacity:0,scale:.8}} whileInView={{opacity:1,scale:1}} transition={{delay:index*.1}} viewport={{once:true}} style={{'--map-index':index} as never}><MapPin size={16}/><strong>{name}</strong><span>{status}</span></motion.div>)}<div className={styles.mapCore}><Fingerprint size={24}/><span>COMMAND</span></div></div></div></section><Chapter number="13" eyebrow="Property intelligence" title="The system does not just record problems. It helps you see them coming." copy="Signals are grounded in operational history and paired with the evidence behind them. They inform a decision; they do not make legal or financial decisions for you." tone="dark"><div className={styles.intelligenceGrid}>{signals.map(([type,signal,action],index)=><motion.article key={type} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} transition={{delay:index*.08}} viewport={{once:true}}><span><Sparkles size={15}/>{type}</span><h3>{signal}</h3><p>{action}</p><button type="button">Open signal <ArrowRight size={14}/></button></motion.article>)}</div></Chapter></>;
}

export function AttentionAndHealth() {
  return <><Chapter number="14" eyebrow="Executive action queue" title="Do not show me everything. Show me what needs me." copy="Urgency, financial exposure and security risk are sorted into a short, defensible list." id="action-queue"><Reveal><ActionQueueDemo/></Reveal></Chapter><Chapter number="15" eyebrow="Property health" title="One number. The health of the operation behind it." copy="An explainable score brings occupancy, collections, maintenance, security, expenses and tenant service into one comparable view." tone="copper"><Reveal><HealthScoreDemo/></Reveal></Chapter></>;
}

export function ConnectedSystem() {
  const entities: Array<[string,LucideIcon]>=[['Tenant',UsersRound],['Tenancy',UserCheck],['Unit',Building2],['Property',Landmark],['Payments',CircleDollarSign],['Maintenance',Wrench],['Contractors',UsersRound],['Expenses',TrendingUp],['Security',Camera],['Evidence',FileCheck2],['Intelligence',Sparkles],['Action',ArrowRight]];
  return <><Chapter number="16" eyebrow="Everything is connected" title="One operational history. Not ten disconnected systems." copy="The connection between a person, a tenancy, a unit, a payment, a repair and its evidence is where control comes from." tone="dark"><div className={styles.entityFlow}>{entities.map(([label,Icon],index)=><motion.div key={String(label)} initial={{opacity:0,scale:.85}} whileInView={{opacity:1,scale:1}} transition={{delay:index*.04}} viewport={{once:true}}><span><Icon size={17}/></span><b>{label}</b>{index<entities.length-1&&<i/>}</motion.div>)}</div></Chapter><section className={styles.transformation}><div className={styles.container}><Reveal><span className={styles.eyebrow}>Before / after</span><h2>Property management becomes property command.</h2></Reveal><div className={styles.wordTransform}>{[['Blind','Visible'],['Scattered','Centralized'],['Reactive','Proactive'],['Dependent','In control'],['Unverified','Auditable'],['Manual','Automated']].map(([before,after],index)=><motion.div key={before} initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} transition={{delay:index*.08}} viewport={{once:true}}><del>{before}</del><ArrowRight/><ins>{after}</ins></motion.div>)}</div></div></section></>;
}

export function ProductComparison({onDemo}:{onDemo:(source:string)=>void}) {
  const control=['Properties, buildings and units','Tenants and tenancies','Rent, arrears and expenses','Maintenance and contractors','Documents and reporting','Property Health and role access'];
  const fort=['Everything in Control','CCTV and camera permissions','Motion events and incidents','Surveillance audit and evidence','Executive Action Queue','Deeper property intelligence'];
  return <Chapter number="17" eyebrow="Control or Fort Knox" title="Choose how much of the operation you want connected." copy="Pricing follows portfolio size and integration scope. CCTV hardware, installation, networking and some provider costs are quoted separately." id="pricing"><div className={styles.planGrid}><article><div className={styles.planTop}><span>CONTROL</span><Gauge size={24}/></div><h3>Operational and financial command.</h3><p>For owners ready to replace fragmented property administration.</p><ul>{control.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><button type="button" onClick={()=>onDemo('control')} data-analytics="control_interest">Start with Control <ArrowRight size={15}/></button></article><article className={styles.flagship}><div className={styles.planTop}><span>FORT KNOX</span><ShieldCheck size={24}/></div><h3>Full remote operational and security command.</h3><p>For owners who need evidence, surveillance governance and exception-led oversight.</p><ul>{fort.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><button type="button" onClick={()=>onDemo('fort-knox')} data-analytics="fort_knox_interest">Explore Fort Knox <ArrowRight size={15}/></button></article></div></Chapter>;
}

export function WhoItIsFor() {
  const audiences=['Apartment owners','Multi-property landlords','Commercial owners','Property developers','Estates','Mixed-use buildings','Management companies','Institutional owners'];
  return <section className={styles.audience}><div className={styles.container}><Reveal><span className={styles.eyebrow}>Built for valuable, distributed portfolios</span><h2>Especially when physical presence no longer scales.</h2><p>When maintenance is hard to verify, rent information is fragmented, CCTV stands alone or every answer depends on a caretaker phone call.</p></Reveal><div className={styles.audienceGrid}>{audiences.map(item=><span key={item}><Building2 size={16}/>{item}</span>)}</div></div></section>;
}
