import { Request, Response } from 'express'; import { Types } from 'mongoose'; import { Role } from '../../database/models/Role.js'; import { apiResponse } from '../../core/response/apiResponse.js'; import { AuthorizationService } from '../../core/authorization/authorization.service.js'; import { AppError } from '../../core/errors/AppError.js'; import { Permission } from '../../database/models/Permission.js'; import { OrganizationMembership } from '../../database/models/OrganizationMembership.js'; import { z } from 'zod'; import { requiredParam } from '../../core/http/params.js';
const roleSchema=z.object({name:z.string().min(2).max(80),key:z.string().regex(/^[A-Z][A-Z0-9_]*$/),description:z.string().max(500).optional(),permissions:z.array(z.string()).min(1),assignable:z.boolean().default(true)});
export async function list(req:Request,res:Response){
    const organizationId=requiredParam(req.params.organizationId,'organizationId');AuthorizationService.assertCan(req.auth!,'role.view',{organizationId});
    res.json(apiResponse(await Role.find({$or:[{organizationId:null,system:true},{organizationId}]}).sort({system:-1,name:1})));
}

export async function create(req:Request,res:Response){
    const organizationId=requiredParam(req.params.organizationId,'organizationId');AuthorizationService.assertCan(req.auth!,'role.create',{organizationId});
    const data=roleSchema.parse(req.body);
    const validPermissions=await Permission.countDocuments({key:{$in:data.permissions}});
    if(validPermissions!==new Set(data.permissions).size) throw new AppError(400,'INVALID_PERMISSIONS','One or more permissions are not in the system catalog');
    if((await Role.findOne({key:data.key,$or:[{organizationId:null,system:true},{organizationId}]})))throw new AppError(409,'ROLE_EXISTS','Role key already exists');const role=await Role.create({...data,organizationId:new Types.ObjectId(organizationId),system:false});res.status(201).json(apiResponse(role));
}
export async function update(req:Request,res:Response){const organizationId=requiredParam(req.params.organizationId,'organizationId');AuthorizationService.assertCan(req.auth!,'role.update',{organizationId});const data=roleSchema.partial().parse(req.body);if(data.permissions){const validPermissions=await Permission.countDocuments({key:{$in:data.permissions}});if(validPermissions!==new Set(data.permissions).size)throw new AppError(400,'INVALID_PERMISSIONS','One or more permissions are not in the system catalog');}const role=await Role.findOneAndUpdate({_id:requiredParam(req.params.roleId,'roleId'),organizationId},data,{new:true,runValidators:true});if(!role)throw new AppError(404,'NOT_FOUND','Custom role not found');res.json(apiResponse(role));}
export async function remove(req:Request,res:Response){const organizationId=requiredParam(req.params.organizationId,'organizationId');AuthorizationService.assertCan(req.auth!,'role.delete',{organizationId});const role=await Role.findOne({_id:requiredParam(req.params.roleId,'roleId'),organizationId});if(!role)throw new AppError(404,'NOT_FOUND','Custom role not found');const assigned=await OrganizationMembership.countDocuments({organizationId,roleIds:role._id,status:{$ne:'REMOVED'}});if(assigned>0)throw new AppError(409,'ROLE_IN_USE','Cannot delete a role assigned to active members');await role.deleteOne();res.json(apiResponse({deleted:true}));}
