'use client';
import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/hooks/use-auth';
import { Alert, Button, Input, Textarea } from '@/components/ui';
import { landlordOnboardingClient as client, contractVariableNames, downloadArtifact } from '@/lib/data/landlord-onboarding';
import { api } from '@/lib/api';
interface Draft { templateId: string; name: string; version: number; plans: string[]; body: string }
function TemplateEditor({ draft, onCreate }: { draft: Draft; onCreate: (input: Draft & { effectiveAt: string; variables: string[] }) => void }) {
  const [body, setBody] = useState(draft.body), [version, setVersion] = useState(draft.version), [id, setId] = useState(draft.templateId), [name, setName] = useState(draft.name), [effectiveAt, setEffectiveAt] = useState(new Date().toISOString().slice(0, 10));
  function submit(event: FormEvent) { event.preventDefault(); onCreate({ templateId: id, name, version, plans: draft.plans, body, effectiveAt: new Date(effectiveAt).toISOString(), variables: contractVariableNames }); }
  return <form className="mt-5 space-y-4" onSubmit={submit}><p className="text-sm text-muted-foreground">Create a draft version, review its full terms and then publish the approved version. Publishing retires the prior active version; existing organization contracts keep their original terms.</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Template ID<Input required value={id} onChange={e => setId(e.target.value)} /></label><label className="text-sm">Template name<Input required value={name} onChange={e => setName(e.target.value)} /></label><label className="text-sm">New version<Input required type="number" min={1} value={version} onChange={e => setVersion(Number(e.target.value))} /></label><label className="text-sm">Effective date<Input required type="date" value={effectiveAt} onChange={e => setEffectiveAt(e.target.value)} /></label></div><label className="block text-sm">Contract terms<Textarea required rows={18} value={body} onChange={e => setBody(e.target.value)} className="mt-2 font-mono text-xs" /></label><p className="text-xs text-muted-foreground">Preserve the declared variables: {contractVariableNames.map(value => `{{${value}}}`).join(', ')}.</p><Button type="submit">Create immutable draft version</Button></form>;
}
export function LandlordOversight() {
  const { user } = useAuth(), admin = !!user?.isPlatformAdmin, cache = useQueryClient();
  const [page, setPage] = useState(1), [selected, setSelected] = useState(''), [editor, setEditor] = useState(false);
  const organizations = useQuery({ queryKey: ['landlord-oversight', page], queryFn: () => client.oversight(page), enabled: admin });
  const templates = useQuery({ queryKey: ['contract-templates'], queryFn: client.templates, enabled: admin });
  const draft = useQuery({ queryKey: ['contract-template-draft'], queryFn: () => api<Draft>('/platform-control/contract-templates/draft'), enabled: admin && editor });
  const detail = useQuery({ queryKey: ['landlord-oversight-detail', selected], queryFn: () => client.status(selected), enabled: admin && !!selected });
  const command = useMutation({ mutationFn: (run: () => Promise<unknown>) => run(), onSuccess: () => { void cache.invalidateQueries({ queryKey: ['contract-templates'] }); } });
  const download = useMutation({ mutationFn: downloadArtifact });
  if (!admin) return <Alert>SUPER_ADMIN access required.</Alert>;
  return <section className="space-y-6"><div><h2 className="text-xl font-semibold">Landlord activation oversight</h2><p className="mt-2 text-sm text-muted-foreground">Inspect saved progress and integrity evidence. Payment verification and landlord signatures remain authoritative; these controls cannot activate an organization or rewrite a signed agreement.</p></div>{organizations.isLoading && <p role="status">Loading onboarding records…</p>}{organizations.error && <Alert tone="destructive">{organizations.error.message}<Button variant="link" onClick={() => void organizations.refetch()}>Retry</Button></Alert>}<div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border"><th className="p-4">Organization</th><th className="p-4">Saved state</th><th className="p-4">Attention</th><th className="p-4">Evidence</th></tr></thead><tbody>{organizations.data?.items.map(org => <tr key={org._id} className="border-b border-border"><td className="p-4">{org.name}</td><td className="p-4">{org.onboarding.state.replaceAll('_', ' ')}</td><td className="p-4">{org.onboarding.attentionCode?.replaceAll('_', ' ') ?? 'None recorded'}</td><td className="p-4"><Button variant="outline" size="sm" onClick={() => setSelected(org._id)}>Inspect</Button></td></tr>)}</tbody></table>{organizations.data?.total === 0 && <p className="p-4 text-sm text-muted-foreground">No organizations have started the versioned onboarding workflow.</p>}</div><div className="flex items-center gap-3"><Button variant="outline" disabled={page === 1} onClick={() => setPage(value => value - 1)}>Previous</Button><span className="text-sm">Page {page} · {organizations.data?.total ?? '…'} organizations</span><Button variant="outline" disabled={!organizations.data || page * 50 >= organizations.data.total} onClick={() => setPage(value => value + 1)}>Next</Button></div>
    {selected && <article className="rounded-xl border border-border bg-card p-5">{detail.isLoading && <p>Loading organization evidence…</p>}{detail.error && <Alert tone="destructive">{detail.error.message}</Alert>}{detail.data && <><h3 className="font-semibold">{detail.data.organization.name} — {detail.data.state}</h3><p className="mt-3 text-sm">Contract: {detail.data.contract?.status ?? 'Not generated'} · Template: {detail.data.contract ? `${detail.data.contract.templateId} v${detail.data.contract.templateVersion}` : 'Pending'}</p><p className="mt-2 text-sm">Signer: {detail.data.contract?.signature?.name ?? 'Awaiting signature'} · Signed: {detail.data.contract?.signature?.signedAt ?? 'Pending'}</p><p className="mt-2 break-all text-xs">Agreement SHA-256: {detail.data.contract?.sha256 ?? 'Pending'}</p><p className="mt-3 text-sm">Invoice: {detail.data.invoice?.invoiceNumber ?? 'Not issued'} · {detail.data.invoice?.status ?? 'Pending'} · {detail.data.invoice ? `${detail.data.invoice.currency} ${detail.data.invoice.total.toFixed(2)}` : ''}</p><p className="mt-2 text-sm">Renewal: {detail.data.subscription?.renewalState ?? 'Not scheduled'}</p><div className="mt-4 flex flex-wrap gap-3">{[detail.data.contract?.documentId, detail.data.contract?.signedDocumentId, detail.data.invoice?.documentId, detail.data.invoice?.receiptDocumentId].filter((id): id is string => !!id).map((id, index) => <Button key={id} variant="outline" loading={download.isPending} onClick={() => download.mutate(id)}>Evidence PDF {index + 1}</Button>)}</div></>}{download.error && <Alert tone="destructive">{download.error.message}</Alert>}</article>}
    <div className="rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Versioned contract templates</h2><Button variant="outline" onClick={() => setEditor(value => !value)}>{editor ? 'Close draft editor' : 'Create template version'}</Button></div>{(templates.error || command.error) && <Alert tone="destructive" className="mt-4">{templates.error?.message ?? command.error?.message}</Alert>}{templates.data?.map(template => <details key={template._id} className="mt-4 rounded-lg border border-border p-4"><summary className="cursor-pointer text-sm font-medium">{template.templateId} v{template.version} · {template.status} · {template.plans.join(', ')}</summary><p className="mt-3 text-xs text-muted-foreground">Effective {template.effectiveAt} · {template.sha256}</p><pre className="mt-4 max-h-80 overflow-auto whitespace-pre-wrap text-xs leading-6">{template.body}</pre>{template.status === 'DRAFT' && <Button className="mt-4" loading={command.isPending} onClick={() => command.mutate(() => client.templateStatus(template._id, 'ACTIVE'))}>Publish approved version</Button>}{template.status === 'ACTIVE' && <Button variant="outline" className="mt-4" loading={command.isPending} onClick={() => command.mutate(() => client.templateStatus(template._id, 'RETIRED'))}>Retire for future contracts</Button>}</details>)}{editor && draft.isLoading && <p className="mt-4">Loading draft terms…</p>}{draft.error && <Alert tone="destructive">{draft.error.message}</Alert>}{editor && draft.data && <TemplateEditor draft={draft.data} onCreate={input => command.mutate(() => client.createTemplate(input))} />}{command.isPending && <p role="status" className="mt-3 text-sm">Saving template review…</p>}</div>
  </section>;
}
