const org = { name: 'organizationId', in: 'path', required: true, schema: { type: 'string', pattern: '^[a-fA-F0-9]{24}$' } };
const responses = { '200': { description: 'Authoritative saved onboarding progress and organization-scoped snapshots' }, '400': { description: 'Invalid or injected fields' }, '401': { description: 'Authentication required' }, '403': { description: 'RBAC/ABAC or landlord signatory scope denied' }, '404': { description: 'Organization or current contract not found' }, '409': { description: 'State, hash, version, retry or settlement conflict' }, '503': { description: 'Required switch, active template or indexes unavailable' } };
const objectId = { type: 'string', pattern: '^[a-fA-F0-9]{24}$' };
const generate = { type: 'object', additionalProperties: false, required: ['planKey', 'expectedRevision'], properties: { planKey: { enum: ['CONTROL', 'FORT_KNOX'] }, prepaidMonths: { type: 'integer', minimum: 3, maximum: 24, default: 3 }, expectedRevision: { type: 'integer', minimum: 0 } } };
const body = (schema: unknown) => ({ required: true, content: { 'application/json': { schema } } });
export const landlordContractPaths = {
  '/organizations/{organizationId}/landlord-onboarding': { get: { summary: 'Restore backend-authoritative landlord onboarding', parameters: [org], responses } },
  '/organizations/{organizationId}/landlord-onboarding/details': { put: { summary: 'Save legal organization and portfolio details', description: 'Organization-wide landlord only. Locked after contract generation; audited in a transaction.', parameters: [org], requestBody: body({ type: 'object', additionalProperties: false, required: ['legalName', 'legalIdentifier', 'billingEmail', 'unitCount'], properties: { legalName: { type: 'string', minLength: 2, maxLength: 200 }, legalIdentifier: { type: 'string', minLength: 2, maxLength: 100 }, billingEmail: { type: 'string', format: 'email' }, unitCount: { type: 'integer', minimum: 0, maximum: 100000 } } }), responses } },
  '/organizations/{organizationId}/landlord-onboarding/quote': { get: { summary: 'Calculate server pricing for the saved portfolio', parameters: [org, { name: 'planKey', in: 'query', required: true, schema: { enum: ['CONTROL', 'FORT_KNOX'] } }, { name: 'prepaidMonths', in: 'query', required: true, schema: { type: 'integer', minimum: 3, maximum: 24 } }], responses } },
  '/organizations/{organizationId}/landlord-onboarding/contract': { post: { summary: 'Idempotently generate snapshotted contract, initial invoice and PDFs', description: 'Reuses OrganizationSubscription, SubscriptionInvoice, Document and Evidence. Requires an effective approved template. No checkout or activation before signature.', parameters: [org], requestBody: body(generate), responses } },
  '/organizations/{organizationId}/landlord-onboarding/replacement': { post: { summary: 'Explicit audited replacement before checkout', description: 'Preserves the predecessor, including any signature, voids the unpaid invoice and requires a new signature. Blocked once checkout/payment begins.', parameters: [org], requestBody: body({ ...generate, required: [...generate.required, 'reason'], properties: { ...generate.properties, reason: { type: 'string', minLength: 10, maxLength: 1000 } } }), responses } },
  '/organizations/{organizationId}/landlord-onboarding/signature': { post: { summary: 'Sign exactly the reviewed current agreement', description: 'Organization-wide landlord only, including platform administrators who independently hold that role. Signature, evidence/PDF, progress and audit commit atomically. SUPER_ADMIN cannot impersonate the signer. Signed artifacts are immutable.', parameters: [org], requestBody: body({ type: 'object', additionalProperties: false, required: ['contractId', 'documentHash', 'signatoryName', 'authorityConfirmed', 'termsAccepted'], properties: { contractId: objectId, documentHash: { type: 'string', pattern: '^[a-f0-9]{64}$' }, signatoryName: { type: 'string', minLength: 2, maxLength: 200 }, authorityConfirmed: { const: true }, termsAccepted: { const: true } } }), responses } },
  '/organizations/{organizationId}/landlord-onboarding/checkout': { post: { summary: 'Prepare one-off prepaid checkout after signing', description: 'Signed current contract and matching invoice required. Persisted checkout reference prevents blind retries. No frontend activation input is accepted.', parameters: [org], responses } },
  '/organizations/{organizationId}/landlord-onboarding/reconcile': { post: { summary: 'Verify provider payment or recover a failed checkout', description: 'Server-side provider verification only. Signed webhook and billing.reconcile use the same atomic settlement boundary. New retry checkout respects PAYSTACK_PAYMENTS.', parameters: [org], responses } },
  '/documents/{documentId}/pdf': { get: { summary: 'Download retained historical PDF through document authorization', description: 'Private no-store bytes, exact SHA-256 and audited access. No recalculation from current prices/templates.', parameters: [{ name: 'documentId', in: 'path', required: true, schema: objectId }], responses: { '200': { description: 'Immutable PDF bytes', content: { 'application/pdf': { schema: { type: 'string', format: 'binary' } } } }, '401': responses['401'], '403': responses['403'], '404': { description: 'Generated artifact not found' } } } },
  '/platform-control/landlord-onboarding': { get: { summary: 'Super Admin paginated onboarding oversight', parameters: [{ name: 'page', in: 'query', schema: { type: 'integer', minimum: 1 } }], responses } },
  '/platform-control/contract-templates/draft': { get: { summary: 'Super Admin starting contract draft for review; never auto-published', responses } },
  '/platform-control/contract-templates': {
    get: { summary: 'Super Admin immutable contract template versions', responses },
    post: { summary: 'Super Admin create a new append-only DRAFT version', requestBody: body({ type: 'object', additionalProperties: false, required: ['templateId', 'name', 'version', 'effectiveAt', 'plans', 'variables', 'body'], properties: { templateId: { type: 'string', pattern: '^[A-Z0-9_-]{2,80}$' }, name: { type: 'string' }, version: { type: 'integer', minimum: 1 }, effectiveAt: { type: 'string', format: 'date-time' }, plans: { type: 'array', items: { enum: ['CONTROL', 'FORT_KNOX'] } }, variables: { type: 'array', items: { type: 'string' } }, body: { type: 'string', minLength: 100, maxLength: 50000 } } }), responses },
  },
  '/platform-control/contract-templates/{templateVersionId}': { patch: { summary: 'Super Admin publish approved template or retire version', description: 'Atomic audit and active-version retirement. Never mutates version content or historical organization contracts.', parameters: [{ name: 'templateVersionId', in: 'path', required: true, schema: objectId }], requestBody: body({ type: 'object', additionalProperties: false, required: ['status'], properties: { status: { enum: ['ACTIVE', 'RETIRED'] } } }), responses } },
};
