import { z } from 'zod';
const oid=z.string().regex(/^[a-f\d]{24}$/i,'Must be a valid MongoDB ObjectId');
const money=z.number().finite().nonnegative(); const date=z.coerce.date();
export const organizationParamsSchema=z.object({organizationId:oid}).strict();
export const idParamsSchema=z.object({id:oid}).strict();
export const rentChargeSchema=z.object({tenancyId:oid,periodStart:date,periodEnd:date,dueDate:date,rentAmount:money,serviceChargeAmount:money.default(0),adjustments:z.number().finite().default(0),currency:z.string().trim().length(3).default('KES'),notes:z.string().trim().max(5000).optional()}).strict().refine(v=>v.periodEnd>=v.periodStart,{message:'periodEnd must be on or after periodStart'});
export const generateRentSchema=z.object({periodStart:date,periodEnd:date,dueDate:date,currency:z.string().trim().length(3).default('KES')}).strict().refine(v=>v.periodEnd>=v.periodStart,{message:'periodEnd must be on or after periodStart'});
export const paymentSchema=z.object({tenancyId:oid,amount:z.number().finite().positive(),currency:z.string().trim().length(3).default('KES'),method:z.enum(['MPESA','BANK_TRANSFER','CARD','CASH','CHEQUE','OTHER']),provider:z.string().trim().max(80).optional(),providerTransactionId:z.string().trim().max(180).optional(),receiptNumber:z.string().trim().max(180).optional(),paidAt:date.optional(),notes:z.string().trim().max(5000).optional()}).strict();
const destinationBase={label:z.string().trim().min(2).max(120),isDefault:z.boolean().default(true),country:z.string().trim().length(2).default('KE')};
export const paymentDestinationSchema=z.discriminatedUnion('provider',[
  z.object({...destinationBase,provider:z.literal('PAYSTACK'),currency:z.string().trim().length(3).default('KES'),businessName:z.string().trim().min(2).max(120),bankCode:z.string().trim().min(2).max(30),accountNumber:z.string().trim().min(6).max(34).regex(/^\d+$/),percentageCharge:z.number().min(0).max(100).default(0),contactEmail:z.string().email().optional(),contactPhone:z.string().min(7).max(40).optional()}).strict(),
  z.object({...destinationBase,provider:z.literal('MPESA'),currency:z.literal('KES').default('KES'),shortCode:z.string().trim().regex(/^\d{5,7}$/),accountReference:z.string().trim().min(1).max(40).optional()}).strict(),
  z.object({...destinationBase,provider:z.literal('CRYPTO'),currency:z.string().trim().min(3).max(10).default('USDC'),asset:z.enum(['USDC','USDT','BTC','ETH']),network:z.enum(['BASE','ETHEREUM','POLYGON','BITCOIN']),walletAddress:z.string().trim().min(20).max(180)}).strict(),
]);
export const allocationSchema=z.object({allocations:z.array(z.object({rentChargeId:oid,amount:z.number().finite().positive()}).strict()).min(1).max(100)}).strict();
export const expenseSchema=z.object({propertyId:oid,buildingId:oid.optional(),floorId:oid.optional(),unitId:oid.optional(),category:z.enum(['MAINTENANCE','UTILITIES','SECURITY','CLEANING','INSURANCE','TAX','STAFF','MANAGEMENT','SUPPLIES','LEGAL','MARKETING','OTHER']),description:z.string().trim().min(3).max(5000),amount:z.number().finite().positive(),currency:z.string().trim().length(3).default('KES'),incurredAt:date,vendorName:z.string().trim().max(180).optional(),contractorId:oid.optional(),evidenceIds:z.array(oid).max(100).default([]),notes:z.string().trim().max(5000).optional()}).strict();
export const expenseActionSchema=z.object({notes:z.string().trim().max(5000).optional()}).strict();
export const serviceChargeSchema=z.object({tenancyId:oid,periodStart:date,periodEnd:date,amount:money,currency:z.string().trim().length(3).default('KES'),description:z.string().trim().max(5000).optional()}).strict();
export const arrearsActionSchema=z.object({status:z.enum(['CONTACTED','PROMISED','ESCALATED','RESOLVED','WRITTEN_OFF']),promiseDate:date.optional(),notes:z.string().trim().max(5000).optional()}).strict();
export const reportSchema=z.object({from:date,to:date,propertyId:oid.optional()}).strict().refine(v=>v.to>=v.from,{message:'to must be on or after from'});
export const periodSchema=z.object({periodStart:date,periodEnd:date,notes:z.string().trim().max(5000).optional()}).strict().refine(v=>v.periodEnd>=v.periodStart,{message:'periodEnd must be on or after periodStart'});
export type RentChargeInput=z.infer<typeof rentChargeSchema>; export type GenerateRentInput=z.infer<typeof generateRentSchema>; export type PaymentInput=z.infer<typeof paymentSchema>; export type PaymentDestinationInput=z.infer<typeof paymentDestinationSchema>; export type AllocationInput=z.infer<typeof allocationSchema>; export type ExpenseInput=z.infer<typeof expenseSchema>; export type ServiceChargeInput=z.infer<typeof serviceChargeSchema>; export type ArrearsActionInput=z.infer<typeof arrearsActionSchema>; export type ReportInput=z.infer<typeof reportSchema>; export type PeriodInput=z.infer<typeof periodSchema>;
