import type { Request, Response } from 'express'; import { apiResponse } from '../../core/response/apiResponse.js'; import { requiredParam } from '../../core/http/params.js'; import { AuthorizationService } from '../../core/authorization/authorization.service.js'; import * as s from './finance.schemas.js'; import { FinanceService } from './finance.service.js';
const auth=(req:Request)=>req.auth!;
export async function listRent(req:Request,res:Response){const org=requiredParam(req.params.organizationId,'organizationId');res.json(apiResponse(await FinanceService.listRent(auth(req),org)));}
export async function createRent(req:Request,res:Response){const org=requiredParam(req.params.organizationId,'organizationId');res.status(201).json(apiResponse(await FinanceService.createRent(auth(req),org,s.rentChargeSchema.parse(req.body))));}
export async function generateRent(req:Request,res:Response){const org=requiredParam(req.params.organizationId,'organizationId');res.status(201).json(apiResponse(await FinanceService.generateRent(auth(req),org,s.generateRentSchema.parse(req.body))));}
export async function getRent(req:Request,res:Response){res.json(apiResponse(await FinanceService.getRent(auth(req),requiredParam(req.params.id,'id'))));}
export async function listPayments(req:Request,res:Response){res.json(apiResponse(await FinanceService.listPayments(auth(req),requiredParam(req.params.organizationId,'organizationId'))));}
export async function createPayment(req:Request,res:Response){res.status(201).json(apiResponse(await FinanceService.createPayment(auth(req),requiredParam(req.params.organizationId,'organizationId'),s.paymentSchema.parse(req.body))));}
export async function listPaymentDestinations(req:Request,res:Response){res.json(apiResponse(await FinanceService.listPaymentDestinations(auth(req),requiredParam(req.params.organizationId,'organizationId'))));}
export async function createPaymentDestination(req:Request,res:Response){res.status(201).json(apiResponse(await FinanceService.createPaymentDestination(auth(req),requiredParam(req.params.organizationId,'organizationId'),s.paymentDestinationSchema.parse(req.body))));}
export async function disablePaymentDestination(req:Request,res:Response){res.json(apiResponse(await FinanceService.disablePaymentDestination(auth(req),requiredParam(req.params.id,'id'))));}
export async function confirmPayment(req:Request,res:Response){res.json(apiResponse(await FinanceService.confirmPayment(auth(req),requiredParam(req.params.id,'id'),s.allocationSchema.parse(req.body))));}
export async function reversePayment(req:Request,res:Response){res.json(apiResponse(await FinanceService.reversePayment(auth(req),requiredParam(req.params.id,'id'))));}
export async function listExpenses(req:Request,res:Response){res.json(apiResponse(await FinanceService.listExpenses(auth(req),requiredParam(req.params.organizationId,'organizationId'))));}
export async function createExpense(req:Request,res:Response){res.status(201).json(apiResponse(await FinanceService.createExpense(auth(req),requiredParam(req.params.organizationId,'organizationId'),s.expenseSchema.parse(req.body))));}
export async function approveExpense(req:Request,res:Response){res.json(apiResponse(await FinanceService.approveExpense(auth(req),requiredParam(req.params.id,'id'),s.expenseActionSchema.parse(req.body).notes)));}
export async function payExpense(req:Request,res:Response){res.json(apiResponse(await FinanceService.payExpense(auth(req),requiredParam(req.params.id,'id'),s.expenseActionSchema.parse(req.body).notes)));}
export async function rejectExpense(req:Request,res:Response){res.json(apiResponse(await FinanceService.rejectExpense(auth(req),requiredParam(req.params.id,'id'),s.expenseActionSchema.parse(req.body).notes)));}
export async function listServiceCharges(req:Request,res:Response){res.json(apiResponse(await FinanceService.listServiceCharges(auth(req),requiredParam(req.params.organizationId,'organizationId'))));}
export async function createServiceCharge(req:Request,res:Response){res.status(201).json(apiResponse(await FinanceService.createServiceCharge(auth(req),requiredParam(req.params.organizationId,'organizationId'),s.serviceChargeSchema.parse(req.body))));}
export async function listArrears(req:Request,res:Response){res.json(apiResponse(await FinanceService.listArrears(auth(req),requiredParam(req.params.organizationId,'organizationId'))));}
export async function openArrearsCase(req:Request,res:Response){const org=requiredParam(req.params.organizationId,'organizationId');const tenant=requiredParam(req.params.tenantId,'tenantId');res.status(201).json(apiResponse(await FinanceService.openArrearsCase(auth(req),org,tenant)));}
export async function updateArrearsCase(req:Request,res:Response){res.json(apiResponse(await FinanceService.updateArrearsCase(auth(req),requiredParam(req.params.id,'id'),s.arrearsActionSchema.parse(req.body))));}
export async function report(req:Request,res:Response){const org=requiredParam(req.params.organizationId,'organizationId');res.json(apiResponse(await FinanceService.report(auth(req),org,s.reportSchema.parse(req.query))));}
export async function listPeriods(req:Request,res:Response){res.json(apiResponse(await FinanceService.listPeriods(auth(req),requiredParam(req.params.organizationId,'organizationId'))));}
export async function createPeriod(req:Request,res:Response){const org=requiredParam(req.params.organizationId,'organizationId');res.status(201).json(apiResponse(await FinanceService.createPeriod(auth(req),org,s.periodSchema.parse(req.body))));}
export async function closePeriod(req:Request,res:Response){res.json(apiResponse(await FinanceService.closePeriod(auth(req),requiredParam(req.params.id,'id'))));}
export async function financePermissionProbe(req:Request,res:Response){AuthorizationService.assertPermission(auth(req),'financial.view',requiredParam(req.params.organizationId,'organizationId'));res.json(apiResponse({enabled:true}));}
