import { Types } from 'mongoose';
import { InventoryItem } from '../../database/models/InventoryItem.js';
import { Unit } from '../../database/models/Unit.js';
import { MaintenanceRequest } from '../../database/models/MaintenanceRequest.js';
import { AuthorizationService } from '../../core/authorization/authorization.service.js';
import { ResourceScopeService } from '../../core/authorization/resource-scope.service.js';
import { AppError } from '../../core/errors/AppError.js';
import type { AuthenticatedUser } from '../../core/types/auth.js';
import type { CreateInventoryInput, UpdateInventoryInput } from './inventory.schemas.js';
export class InventoryService {
 static async list(auth:AuthenticatedUser,organizationId:string){const orgId=new Types.ObjectId(organizationId);const ids=await ResourceScopeService.scopedUnitIds(auth,orgId);const f:Record<string,unknown>={organizationId:orgId};if(ids)f.unitId={$in:ids};return InventoryItem.find(f).sort({name:1}).lean();}
 static async get(auth:AuthenticatedUser,id:string){const item=await InventoryItem.findById(id);if(!item)throw new AppError(404,'NOT_FOUND','Inventory item not found');ResourceScopeService.assertUnit(auth,item,'inventory.view');return item;}
 static async create(auth:AuthenticatedUser,organizationId:string,data:CreateInventoryInput){const orgId=new Types.ObjectId(organizationId);const unit=await Unit.findOne({_id:data.unitId,organizationId:orgId}).lean();if(!unit)throw new AppError(404,'UNIT_NOT_FOUND','Unit not found');ResourceScopeService.assertUnit(auth,unit,'inventory.create');const duplicate=await InventoryItem.exists({organizationId:orgId,assetTag:data.assetTag.toUpperCase()});if(duplicate)throw new AppError(409,'ASSET_TAG_EXISTS','Asset tag already exists');const next=data.maintenanceIntervalDays&&data.purchaseDate?new Date(data.purchaseDate.getTime()+data.maintenanceIntervalDays*86400000):undefined;return InventoryItem.create({...data,assetTag:data.assetTag.toUpperCase(),organizationId:orgId,propertyId:unit.propertyId,buildingId:unit.buildingId,floorId:unit.floorId,unitId:unit._id,nextServiceDueAt:next,createdBy:auth.userId,updatedBy:auth.userId});}
 static async update(auth:AuthenticatedUser,id:string,data:UpdateInventoryInput){const item=await InventoryItem.findById(id);if(!item)throw new AppError(404,'NOT_FOUND','Inventory item not found');ResourceScopeService.assertUnit(auth,item,'inventory.update');if(data.assetTag&&data.assetTag.toUpperCase()!==item.assetTag){const duplicate=await InventoryItem.exists({organizationId:item.organizationId,assetTag:data.assetTag.toUpperCase(),_id:{$ne:item._id}});if(duplicate)throw new AppError(409,'ASSET_TAG_EXISTS','Asset tag already exists');}Object.assign(item,{...data,assetTag:data.assetTag?.toUpperCase()??item.assetTag,updatedBy:auth.userId});if(data.lastServicedAt&&item.maintenanceIntervalDays)item.nextServiceDueAt=new Date(data.lastServicedAt.getTime()+item.maintenanceIntervalDays*86400000);await item.save();return item;}
 static async serviceDue(auth:AuthenticatedUser,organizationId:string){const orgId=new Types.ObjectId(organizationId);const ids=await ResourceScopeService.scopedUnitIds(auth,orgId);const f:Record<string,unknown>={organizationId:orgId,status:{$in:['ACTIVE','UNDER_REPAIR']},nextServiceDueAt:{$lte:new Date()}};if(ids)f.unitId={$in:ids};return InventoryItem.find(f).sort({nextServiceDueAt:1}).lean();}
 static async maintenanceHistory(auth:AuthenticatedUser,id:string){const item=await this.get(auth,id);return MaintenanceRequest.find({organizationId:item.organizationId,unitId:item.unitId}).sort({createdAt:-1}).lean();}
}
