'use client';
import { useMemo, useState } from 'react';
import * as I from '@/components/icons';
import { StatusBadge,  Badge, EmptyState, PageTitle, SectionHeader, Stat } from '@/components/ui';
import { useOrganization } from '@/hooks/use-organization';
import { usePropertiesQuery } from '@/hooks/queries/use-property-queries';
import { useDecisionAutomationOverviewQuery, useTenantArrearsRisksQuery, useVacancyForecastsQuery } from '@/hooks/queries/use-decision-automation-queries';
import { useLabelPredictiveOutcomesMutation, usePredictiveModelsQuery } from '@/hooks/queries/use-predictive-learning-queries';
import type { RevenueRiskForecast, TenantArrearsRisk, VacancyForecast } from '@/lib/data/resource-types';

const money=(n:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:'KES',maximumFractionDigits:0}).format(n);
const pct=(n:number)=>`${Math.round(n*100)}%`;
const pretty=(s:string)=>s.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,m=>m.toUpperCase());

const date=(s?:string)=>s?new Date(s).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'—';
const domainLabel=(d:string)=>d==='ARREARS'?'Tenant arrears':d==='VACANCY'?'Vacancy':'Revenue';

function DriverList({drivers}:{drivers:Array<{code:string;label:string;impact:number}>}){return <div className="space-y-2">{drivers.slice(0,4).map(d=><div key={d.code} className="flex items-center justify-between gap-3 text-sm"><span className="text-muted-foreground">{d.label}</span><span className="font-semibold">{d.impact===0?'—':money(d.impact)}</span></div>)}</div>}
function Confidence({value}:{value:number}){return <div><div className="flex justify-between text-[11px] text-muted-foreground"><span>Confidence</span><span className="font-semibold text-muted-foreground">{pct(value)}</span></div><div className="h-1.5 bg-[#eaecf0] rounded-full mt-1 overflow-hidden"><div className="h-full rounded-full bg-[#101828]" style={{width:`${Math.round(value*100)}%`}}/></div></div>}
function RiskCard({risk}:{risk:TenantArrearsRisk}){return <div className="rounded-2xl border border-border p-4"><div className="flex justify-between gap-3"><div><div className="text-[11px] text-muted-foreground">Tenant {risk.tenantId}</div><div className="font-semibold mt-1">{pretty(risk.grade)} arrears risk</div></div><StatusBadge status={risk.grade} domain="monitoring">{risk.score.toFixed(0)}/100 · {pretty(risk.grade)}</StatusBadge></div><div className="grid grid-cols-3 gap-3 mt-4"><Metric label="Probability" value={pct(risk.probability)}/><Metric label="Outstanding" value={money(risk.outstandingAmount)}/><Metric label="Past due" value={`${Math.round(risk.daysPastDue)}d`}/></div><div className="mt-4"><DriverList drivers={risk.drivers}/></div><div className="mt-4"><Confidence value={risk.confidence}/></div><div className="mt-3 text-[11px] text-muted-foreground">Observed {date(risk.asOf)} · model {risk.modelVersion}</div></div>}
function VacancyCard({forecast}:{forecast:VacancyForecast}){return <div className="rounded-2xl border border-border p-4"><div className="flex justify-between gap-3"><div><div className="text-[11px] text-muted-foreground">Unit {forecast.unitId}</div><div className="font-semibold mt-1">Lease timing forecast</div></div><Badge tone={forecast.predictedDaysToLease>=60?'red':forecast.predictedDaysToLease>=30?'orange':'green'}>{Math.round(forecast.predictedDaysToLease)} days</Badge></div><div className="grid grid-cols-3 gap-3 mt-4"><Metric label="Vacant now" value={`${Math.round(forecast.currentVacancyDays)}d`}/><Metric label="Historical median" value={`${Math.round(forecast.historicalMedianDays)}d`}/><Metric label="Revenue at risk" value={money(forecast.revenueAtRisk)}/></div><div className="mt-4"><DriverList drivers={forecast.drivers}/></div><div className="mt-4"><Confidence value={forecast.confidence}/></div><div className="mt-3 text-[11px] text-muted-foreground">Predicted lease {date(forecast.predictedLeaseDate)} · {forecast.historicalSampleSize} historical transitions</div></div>}
function Metric({label,value}:{label:string;value:string}){return <div><div className="text-[11px] text-muted-foreground">{label}</div><div className="font-semibold text-sm mt-1">{value}</div></div>}
function RevenueCard({forecast}:{forecast:RevenueRiskForecast}){return <div className="card p-5"><SectionHeader title={`Revenue risk · ${forecast.horizonDays} days`} action={<Badge tone={forecast.revenueAtRisk>0?'orange':'green'}>{money(forecast.revenueAtRisk)} at risk</Badge>}/><div className="grid sm:grid-cols-3 gap-4 mt-4"><Metric label="Baseline" value={money(forecast.baselineMonthlyRevenue)}/><Metric label="Expected revenue" value={money(forecast.expectedRevenue)}/><Metric label="Health velocity" value={`${forecast.healthVelocity.toFixed(2)} / day`}/></div><div className="grid sm:grid-cols-4 gap-3 mt-5"><Metric label="Vacancy" value={money(forecast.vacancyRiskAmount)}/><Metric label="Arrears" value={money(forecast.arrearsRiskAmount)}/><Metric label="Collection" value={money(forecast.collectionRiskAmount)}/><Metric label="Maintenance" value={money(forecast.maintenanceRiskAmount)}/></div><div className="mt-5 grid md:grid-cols-2 gap-5"><div><div className="text-xs font-semibold mb-2">Risk drivers</div><DriverList drivers={forecast.drivers}/></div><div><div className="text-xs font-semibold mb-2">Model provenance</div><div className="text-sm text-muted-foreground space-y-2"><div>Source: <b>{pretty(forecast.modelSource??'RULE')}</b></div><div>Version: <b>{forecast.modelVersion}</b></div><div>ML influence: <b>{forecast.mlInfluenced?'Enabled':'Not applied'}</b></div></div><div className="mt-4"><Confidence value={forecast.confidence}/></div></div></div></div>}
function ModelRow({model}:{model:{domain:string;version:string;status:string;validationPassed:boolean;metrics?:Record<string,number|undefined>;trainedAt?:string}}){const m=model.metrics??{};return <div className="rounded-xl border border-border p-3"><div className="flex justify-between gap-3"><div><div className="font-semibold text-sm">{domainLabel(model.domain)}</div><div className="text-[11px] text-muted-foreground mt-1">{model.version}</div></div><StatusBadge status={model.status} domain="predictive">{pretty(model.status)}</StatusBadge></div><div className="grid grid-cols-3 gap-3 mt-3"><Metric label="Samples" value={String(m.sampleCount??0)}/><Metric label="Validation" value={String(m.validationCount??0)}/><Metric label="Passed" value={model.validationPassed?'Yes':'No'}/></div><div className="text-[11px] text-muted-foreground mt-3">Trained {date(model.trainedAt)}</div></div>}

export default function PredictiveIntelligencePage(){
 const {activeOrganizationId}=useOrganization();
 const [propertyId,setPropertyId]=useState('ALL');
 const [tab,setTab]=useState<'overview'|'arrears'|'vacancy'|'revenue'|'learning'>('overview');
 const scope=propertyId==='ALL'?{}:{propertyId};
 const properties=usePropertiesQuery(activeOrganizationId);
 const overview=useDecisionAutomationOverviewQuery(activeOrganizationId,scope);
 const risks=useTenantArrearsRisksQuery(activeOrganizationId,{...scope,limit:100});
 const vacancies=useVacancyForecastsQuery(activeOrganizationId,{...scope,limit:100});
 const models=usePredictiveModelsQuery(activeOrganizationId,{limit:50});
 const label=useLabelPredictiveOutcomesMutation(activeOrganizationId);
 const revenue=useMemo(()=>overview.data?.revenueForecasts??[],[overview.data]);
 if(!activeOrganizationId)return <EmptyState icon={I.Brain} title="No active organization" description="Select an organization before opening predictive intelligence."/>;
 const highRisk=(risks.data??[]).filter(r=>r.grade==='HIGH'||r.grade==='CRITICAL');
 const vacancyExposure=(vacancies.data??[]).reduce((s,v)=>s+v.revenueAtRisk,0);
 const totalRevenueRisk=revenue.reduce((s,r)=>s+r.revenueAtRisk,0);
 return <div className="space-y-5">
  <PageTitle eyebrow="Forward-looking intelligence" title="Predictive Intelligence" description="See what the portfolio is likely to lose, where risk is accumulating, and why the model believes it." action={<button className="btn-primary" disabled={label.isPending} onClick={()=>label.mutate({horizonDays:30})}><I.History size={15}/>{label.isPending?'Labeling…':'Refresh outcomes'}</button>}/>
  <div className="card p-3 flex flex-wrap items-center gap-2"><span className="text-xs font-semibold flex gap-2 items-center"><I.SlidersHorizontal size={14}/> Scope</span><select className="input max-w-[280px]" value={propertyId} onChange={e=>setPropertyId(e.target.value)}><option value="ALL">All properties</option>{(properties.data??[]).map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select><span className="ml-auto text-[11px] text-muted-foreground">Predictions are advisory; financial records remain authoritative.</span></div>
  {overview.isLoading?<div className="card h-40 animate-pulse"/>:overview.isError?<div className="card p-8 text-center"><I.AlertTriangle className="mx-auto"/><b className="block mt-3">Predictive intelligence unavailable</b><p className="text-sm text-muted-foreground mt-1">Run a governed evaluation from Decision Automation first if no predictions exist.</p></div>:<>
   <div className="grid grid-cols-2 xl:grid-cols-6 gap-3"><Stat label="Money at risk" value={money(totalRevenueRisk)} sub="Revenue forecast exposure" icon={I.Landmark}/><Stat label="High-risk tenants" value={String(highRisk.length)} sub="Arrears probability" icon={I.Users}/><Stat label="Vacancy exposure" value={money(vacancyExposure)} sub="Predicted lease delay" icon={I.Building2}/><Stat label="Revenue forecasts" value={String(revenue.length)} sub="Property-level" icon={I.LineChart}/><Stat label="Model versions" value={String(models.data?.length??0)} sub="Governed registry" icon={I.Target}/><Stat label="As of" value={overview.data?.asOf?new Date(overview.data.asOf).toLocaleDateString():'—'} sub="Latest evaluation" icon={I.Clock3}/></div>
   <div className="card p-5"><SectionHeader title="Prediction methodology"/><div className="grid md:grid-cols-4 gap-3 mt-4"><Method icon={I.History} title="Historical outcomes" text="Observed rent, tenancy and leasing outcomes are used for learning when available."/><Method icon={I.Target} title="Risk score" text="Probability and exposure are separated so a small probability cannot hide a large balance."/><Method icon={I.Brain} title="Explainability" text="Every forecast carries model provenance, confidence and contributing drivers."/><Method icon={I.ShieldCheck} title="Governance" text="Predictions can inform automation, but they do not bypass approvals or mutate the ledger."/></div></div>
   <div className="card p-5"><div className="flex gap-2 border-b border-border pb-3 overflow-x-auto">{(['overview','arrears','vacancy','revenue','learning'] as const).map(x=><button key={x} className={`px-3 py-2 rounded-xl text-xs font-semibold whitespace-nowrap ${tab===x?'bg-[#101828] text-white':'text-muted-foreground hover:bg-muted'}`} onClick={()=>setTab(x)}>{pretty(x)}</button>)}</div>
    {tab==='overview'&&<div className="pt-4 grid xl:grid-cols-2 gap-5"><div><SectionHeader title="Highest arrears risk"/><div className="space-y-3 mt-3">{highRisk.slice(0,5).map(r=><RiskCard key={r._id} risk={r}/>)}{!highRisk.length&&<EmptyLine text="No high or critical tenant risk observations."/>}</div></div><div><SectionHeader title="Largest vacancy exposure"/><div className="space-y-3 mt-3">{[...(vacancies.data??[])].sort((a,b)=>b.revenueAtRisk-a.revenueAtRisk).slice(0,5).map(v=><VacancyCard key={v._id} forecast={v}/>)}{!(vacancies.data??[]).length&&<EmptyLine text="No vacancy forecasts available."/>}</div></div></div>}
    {tab==='arrears'&&<div className="pt-4 grid xl:grid-cols-2 gap-3">{(risks.data??[]).map(r=><RiskCard key={r._id} risk={r}/>)}{!(risks.data??[]).length&&<EmptyLine text="No tenant arrears risk observations available."/>}</div>}
    {tab==='vacancy'&&<div className="pt-4 grid xl:grid-cols-2 gap-3">{(vacancies.data??[]).map(v=><VacancyCard key={v._id} forecast={v}/>)}{!(vacancies.data??[]).length&&<EmptyLine text="No vacancy forecasts available."/>}</div>}
    {tab==='revenue'&&<div className="pt-4 space-y-3">{revenue.map((r,i)=><RevenueCard key={`${r.modelVersion}-${i}`} forecast={r}/>)}{!revenue.length&&<EmptyLine text="No property revenue forecasts available."/>}</div>}
    {tab==='learning'&&<div className="pt-4"><div className="p-4 rounded-2xl bg-muted border border-border mb-4"><div className="font-semibold text-sm">Outcome learning</div><p className="text-sm text-muted-foreground mt-1">Refresh outcomes labels pending predictive observations against observed rent, vacancy and revenue outcomes. Training and model promotion remain controlled by the ML governance layer.</p><button className="btn-secondary mt-3" disabled={label.isPending} onClick={()=>label.mutate({horizonDays:30})}>{label.isPending?'Refreshing…':'Label observed outcomes'}</button></div><div className="space-y-3">{(models.data??[]).map(m=><ModelRow key={m._id} model={m}/>)}{!(models.data??[]).length&&<EmptyLine text="No predictive model records are available yet. Rule-based forecasts may still be shown."/>}</div></div>}
   </div>
  </>}
 </div>
}
function Method({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <div className="rounded-2xl border border-border p-4"><div className="w-9 h-9 rounded-xl bg-muted flex items-center justify-center"><Icon size={17}/></div><div className="font-semibold text-sm mt-3">{title}</div><p className="text-xs text-muted-foreground mt-1 leading-5">{text}</p></div>}
function EmptyLine({text}:{text:string}){return <div className="py-10 text-center text-sm text-muted-foreground rounded-xl bg-muted">{text}</div>}
