import { Types } from 'mongoose';
import { Evidence } from '../../database/models/Evidence.js';
import { MaintenanceRequest } from '../../database/models/MaintenanceRequest.js'; import { Inspection } from '../../database/models/Inspection.js'; import { MoveOut } from '../../database/models/MoveOut.js'; import { Tenancy } from '../../database/models/Tenancy.js'; import { Expense } from '../../database/models/Expense.js'; import { Payment } from '../../database/models/Payment.js'; import { ArrearsCase } from '../../database/models/ArrearsCase.js'; import { Property } from '../../database/models/Property.js'; import { Unit } from '../../database/models/Unit.js'; import { SecurityEvent } from '../../database/models/SecurityEvent.js';
import { AuthorizationService } from '../../core/authorization/authorization.service.js'; import { ResourceScopeService } from '../../core/authorization/resource-scope.service.js'; import { AppError } from '../../core/errors/AppError.js'; import { AuditService } from '../audit/audit.service.js'; import type { AuthenticatedUser } from '../../core/types/auth.js'; import type { z } from 'zod'; import type { createEvidenceSchema, evidenceQuerySchema } from './evidence.schemas.js';
type CreateInput=z.infer<typeof createEvidenceSchema>; type QueryInput=z.infer<typeof evidenceQuerySchema>; const oid=(v:string)=>new Types.ObjectId(v);
export class EvidenceService {
  private static async authorizeRelated(auth:AuthenticatedUser,org:Types.ObjectId,type:string,id:string,permission:string){
    if(!Types.ObjectId.isValid(id))throw new AppError(400,'INVALID_ID','Invalid related resource id'); const resourceId=oid(id);
    let resource:{organizationId:Types.ObjectId;propertyId?:Types.ObjectId|null;buildingId?:Types.ObjectId|null;unitId?:Types.ObjectId|null;ownerUserId?:Types.ObjectId|null}|null=null;
    switch(type){case 'MAINTENANCE':{const x=await MaintenanceRequest.findById(resourceId).lean();if(x)resource=x;break;}case 'INSPECTION':{const x=await Inspection.findById(resourceId).lean();if(x)resource=x;break;}case 'MOVE_OUT':{const x=await MoveOut.findById(resourceId).lean();if(x)resource=x;break;}case 'TENANCY':{const x=await Tenancy.findById(resourceId).lean();if(x)resource=x;break;}case 'EXPENSE':{const x=await Expense.findById(resourceId).lean();if(x)resource=x;break;}case 'PAYMENT':{const x=await Payment.findById(resourceId).lean();if(x)resource=x;break;}case 'ARREARS':{const x=await ArrearsCase.findById(resourceId).lean();if(x)resource=x;break;}case 'PROPERTY':{const x=await Property.findById(resourceId).lean();if(x)resource=x;break;}case 'UNIT':{const x=await Unit.findById(resourceId).lean();if(x)resource=x;break;}case 'SECURITY_EVENT':{const x=await SecurityEvent.findById(resourceId).lean();if(x)resource=x;break;} default: AuthorizationService.assertPermission(auth,permission,org);return;}
    if(!resource)throw new AppError(404,'RELATED_RESOURCE_NOT_FOUND','Related resource not found'); if(String(resource.organizationId)!==String(org))throw new AppError(403,'CROSS_ORGANIZATION_ACCESS_DENIED','Related resource belongs to another organization');
    if(resource.unitId){ResourceScopeService.assertUnit(auth,{_id:resource.unitId,organizationId:resource.organizationId,propertyId:resource.propertyId!,buildingId:resource.buildingId!},permission,resource.ownerUserId);return;} if(resource.propertyId){await ResourceScopeService.assertProperty(auth,{_id:resource.propertyId,organizationId:resource.organizationId},permission);return;} AuthorizationService.assertPermission(auth,permission,org);
  }
  static async create(auth:AuthenticatedUser,organizationId:string,data:CreateInput){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'evidence.create',org);const tenantRole=auth.memberships.some(m=>String(m.organizationId)===String(org)&&m.roles.includes('TENANT'));if(tenantRole&&!data.unitId)throw new AppError(403,'TENANT_EVIDENCE_SCOPE_REQUIRED','Tenant evidence must be linked to a unit');await this.authorizeRelated(auth,org,data.relatedResourceType,data.relatedResourceId,'evidence.create');const ev=await Evidence.create({organizationId:org,...data,propertyId:data.propertyId?oid(data.propertyId):undefined,buildingId:data.buildingId?oid(data.buildingId):undefined,floorId:data.floorId?oid(data.floorId):undefined,unitId:data.unitId?oid(data.unitId):undefined,ownerUserId:data.ownerUserId?oid(data.ownerUserId):undefined,documentId:data.documentId?oid(data.documentId):undefined,relatedResourceId:oid(data.relatedResourceId),createdBy:auth.userId});await AuditService.record({organizationId:org,actorUserId:auth.userId,action:'evidence.created',resourceType:'Evidence',resourceId:ev._id,propertyId:ev.propertyId,buildingId:ev.buildingId,unitId:ev.unitId,after:ev.toObject()});await AuditService.publish({organizationId:org,name:'evidence.created',aggregateType:'Evidence',aggregateId:ev._id,actorUserId:auth.userId,payload:{relatedResourceType:ev.relatedResourceType,relatedResourceId:ev.relatedResourceId}});return ev;}
  static async list(auth:AuthenticatedUser,organizationId:string,query:QueryInput){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'evidence.view',org);const ids=await ResourceScopeService.scopedUnitIds(auth,org);const filter:Record<string,unknown>={organizationId:org};if(query.relatedResourceType)filter.relatedResourceType=query.relatedResourceType;if(query.relatedResourceId)filter.relatedResourceId=oid(query.relatedResourceId);if(ids)filter.$or=[{unitId:{$in:ids}},{unitId:{$exists:false}}];if(auth.memberships.some(m=>String(m.organizationId)===String(org)&&m.roles.includes('TENANT'))&&!auth.isPlatformAdmin)filter.$and=[{ $or:[{ownerUserId:auth.userId},{unitId:{$in:ids??[]}}] }];return Evidence.find(filter).sort({capturedAt:-1}).limit(200).lean();}
}
