"use client";

import { useState, type CSSProperties } from "react";
import Link from "next/link";
import { BRAND } from "@/lib/brand";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ArrowRight, Camera, Check, ChevronRight, LockKeyhole, Play } from "lucide-react";
import { money, personas, portfolio, portfolioTotals, roleViews, type DemoRole, type DemoScene, type SceneKind } from "@/lib/cinematic-demo/content";
import styles from "./demo.module.css";

type Props = { scene: DemoScene; progress: number; captions: boolean; showLabels: boolean; theme: "dark" | "light"; safeArea?: boolean; prospect?: string; platform?: string | undefined };

const queue = [
  ["APPROVAL", "Kitchen sink repair", "Riverside / B-12", "KES 27,500"],
  ["FINANCE", "Five tenancies overdue", "Portfolio / 30+ days", "KES 184,000"],
  ["SECURITY", "Overnight motion", "Greenview / rear gate", "03:12"],
  ["VACANCY", "Unit A-04 vacant", "46 days unoccupied", "KES 69,000"],
] as const;
const workflow = ["NEW", "TRIAGED", "ASSIGNED", "QUOTED", "APPROVAL REQUIRED", "APPROVED", "IN PROGRESS", "COMPLETED", "VERIFIED", "CLOSED"] as const;
const roleKeys: DemoRole[] = ["owner", "manager", "caretaker", "tenant", "contractor", "admin"];
const health = [["Occupancy", 93], ["Collections", 93], ["Maintenance", 78], ["Expenses", 84], ["Security", 86], ["Tenant service", 90]] as const;

function Opening({ progress }: { progress: number }) {
  const figures = [[String(portfolioTotals.properties), "PROPERTIES"], [String(portfolioTotals.units), "UNITS"], [money(portfolio.expectedRent), "EXPECTED RENT"], [`${portfolioTotals.occupancyPercent}%`, "OCCUPIED"]] as const;
  return <div className={styles.opening}><span className={styles.eyebrow}>ACACIA PROPERTY HOLDINGS / FICTIONAL PORTFOLIO</span><div className={styles.openingFigures}>{figures.map(([value, label], index) => <motion.div key={label} initial={false} animate={{ opacity: index <= Math.floor(progress * 4) ? 1 : .16, y: index <= Math.floor(progress * 4) ? 0 : 12 }} transition={{ duration: .55 }}><strong>{value}</strong><small>{label}</small></motion.div>)}</div><h3>One portfolio.<br/>One operational picture.</h3></div>;
}

function Decisions() { return <div className={styles.decisions}>{queue.map(([type, title, context, value], index) => <div className={styles.decision} key={type}><span>0{index + 1}</span><div><small>{type} / {context}</small><strong>{title}</strong></div><b>{value}</b><ChevronRight size={15}/></div>)}</div>; }

function CommandCenter() { return <div className={styles.command}><div className={styles.commandHead}><div><span className={styles.eyebrow}>ACACIA / EXECUTIVE OVERVIEW</span><h3>Portfolio performance.</h3></div><div className={styles.commandHealth}>PROPERTY HEALTH <strong>87<small>/100</small></strong></div></div><div className={styles.commandBody}><div className={styles.commandMain}><div className={styles.metrics}><div><small>EXPECTED</small><strong>{money(portfolio.expectedRent)}</strong></div><div><small>COLLECTED</small><strong>{money(portfolio.collectedRent)}</strong></div><div><small>OCCUPIED</small><strong>{portfolioTotals.occupied} / {portfolioTotals.units}</strong></div></div><div className={styles.chart}><div>{[56, 61, 59, 70, 74, 72, 81, 84, 87, 93].map((value, index) => <span key={index} style={{ height: `${value}%` }}/>)}</div><small>JAN <span>COLLECTION TREND / ILLUSTRATIVE</span> OCT</small></div></div><div className={styles.commandAside}><div className={styles.sectionLabel}>WHAT NEEDS YOU <b>04</b></div><Decisions/></div></div></div>; }

function DecisionDesk() { return <div className={styles.desk}><span className={styles.eyebrow}>OWNER / ACTION QUEUE</span><h3>What needs your attention?</h3><div className={styles.deskPriority}><small>APPROVAL REQUIRED / RIVERSIDE APARTMENTS</small><strong>Unit B-12 needs a decision.</strong><span>KES 27,500 <ArrowRight size={17}/></span></div><Decisions/></div>; }

function Finance() { return <div className={styles.finance}><span className={styles.eyebrow}>RENT / PORTFOLIO</span><h3>Money in motion.</h3><div className={styles.financeMetrics}><div><small>EXPECTED</small><strong>{money(portfolio.expectedRent)}</strong></div><div><small>COLLECTED</small><strong>{money(portfolio.collectedRent)}</strong></div><div><small>OUTSTANDING</small><strong>{money(portfolioTotals.outstanding)}</strong></div></div><div className={styles.flow}><div>{["A-01", "A-02", "B-04", "B-12"].map((unit, index) => <span key={unit} data-paid={index !== 3}><small>UNIT</small><strong>{unit}</strong><em>{index === 3 ? "DUE" : "PAID"}</em></span>)}</div><i/><strong>PROPERTY LEDGER <small>Riverside Apartments / {portfolioTotals.collectionPercent}% collected</small></strong></div></div>; }

function Vacancy() { return <div className={styles.vacancy}><div><span className={styles.eyebrow}>VACANCY / REVENUE EXPOSURE</span><h3>{portfolioTotals.vacant}<small> vacant units</small></h3><strong>{money(portfolio.estimatedVacancyLoss)}</strong><p>Estimated monthly revenue not being collected.</p></div><div className={styles.floorplan}><small>PORTFOLIO / SAMPLE FLOOR PLAN</small><div>{Array.from({ length: 24 }, (_, index) => <span key={index} data-vacant={[3, 11, 20].includes(index)}>{String(index + 1).padStart(2, "0")}</span>)}</div><p>Illustrative occupied and vacant spaces</p></div></div>; }

const maintenanceStep: Partial<Record<SceneKind, number>> = { tenant: 0, context: 1, caretaker: 2, contractor: 3, approval: 4, progress: 7, evidence: 9 };
function Maintenance({ kind }: { kind: SceneKind }) { const [approved, setApproved] = useState(false); const step = maintenanceStep[kind] ?? 7; return <div className={styles.maintenance}><div className={styles.steps}><span className={styles.eyebrow}>MR-1082 / RIVERSIDE</span>{workflow.map((item, index) => <div key={item} data-state={index < step || (approved && index === 4) ? "done" : index === step ? "active" : "waiting"}><i/>{item}</div>)}</div><div className={styles.record}><span className={styles.eyebrow}>{kind === "approval" ? "EXECUTIVE DECISION" : "OPERATIONAL RECORD"}</span><h3>Water leaking below kitchen sink.</h3><p>One request. A known unit, an accountable owner and a complete history.</p>{[["TENANT", "Jane Wambui"], ["PROPERTY", "Riverside Apartments"], ["BUILDING", "Block B"], ["UNIT", "B-12"], ["REPORTED", "10:42 AM"]].map(([label, value]) => <div className={styles.context} key={label}><small>{label}</small><strong>{value}</strong></div>)}<p className={styles.recordNote}>The system already knows where it happened.</p></div><div className={styles.evidence}><span className={styles.eyebrow}>EVIDENCE / RESPONSIBILITY</span><div className={styles.evidenceVisual}><i/><i/><span>PHOTO EVIDENCE<br/>KITCHEN SINK / B-12</span></div>{[["CONTRACTOR", "Otieno Plumbing"], ["PREVIOUS REPAIRS", "2 recorded"], ["MANAGER THRESHOLD", "KES 5,000"], ["QUOTE", "KES 27,500"]].map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}{kind === "approval" && <div className={styles.approvalActions}><button type="button" onClick={() => setApproved(false)}>Decline</button><button type="button" onClick={() => setApproved(true)}>{approved ? <><Check size={14}/> Simulated approval</> : "Approve KES 27,500"}</button></div>}<small className={styles.demoNotice}>FICTIONAL DEMO / NO PRODUCTION ACTION</small></div></div>; }

function Passport() { return <div className={styles.passport}><div><span className={styles.eyebrow}>PROPERTY PASSPORT / UNIT DOSSIER</span><h3>UNIT B-12</h3><p>Riverside Apartments / Block B / Floor 3</p><strong>Every unit has a memory.</strong></div><div className={styles.passportRows}>{[["2026", "TENANCY", "Jane Wambui"], ["OCT 12", "MAINTENANCE", "Kitchen sink repair verified"], ["SEP 01", "RENT", "KES 69,000 reconciled"], ["AUG 18", "INSPECTION", "Move-in condition recorded"], ["JUL 25", "DOCUMENT", "Lease countersigned"]].map(([date, kind, detail]) => <div key={date}><time>{date}</time><span>{kind}</span><strong>{detail}</strong></div>)}</div></div>; }

function EvidenceLedger() { return <div className={styles.ledger}><span className={styles.eyebrow}>MR-1082 / ACCOUNTABLE HISTORY</span><h3>Every handoff leaves a record.</h3>{[["10:42", "Tenant report", "Jane Wambui"], ["10:51", "Triaged", "James Kamau"], ["11:04", "Contractor assigned", "Peter Otieno"], ["11:18", "Quote submitted", "KES 27,500"], ["11:24", "Owner approval", "David Mwangi"], ["15:47", "After photo attached", "Peter Otieno"], ["16:09", "Work verified", "James Kamau"]].map(([time, action, actor]) => <div key={time}><time>{time}</time><i/><strong>{action}</strong><span>{actor}</span></div>)}</div>; }

function Performance() { return <div className={styles.performance}><span className={styles.eyebrow}>CONTRACTOR ACCOUNTABILITY</span><h3>Performance is recorded.</h3><p>Peter Otieno / Otieno Plumbing Services</p><div>{[["48", "JOBS COMPLETED"], ["36 min", "AVERAGE RESPONSE"], ["5.7 hrs", "AVERAGE RESOLUTION"], ["2.1%", "REWORK RATE"]].map(([value, label]) => <span key={label}><strong>{value}</strong><small>{label}</small></span>)}</div></div>; }

function Tiers() { return <div className={styles.tiers}><span className={styles.eyebrow}>CONTROL / FORT KNOX</span><h3>Operations meet evidence.</h3><div><section><small>01 / CONTROL</small><strong>Operate with clarity.</strong><p>Rent, tenancies, maintenance, contractors, documents and reporting.</p></section><section><small>02 / FORT KNOX</small><strong>Protect with evidence.</strong><p>Scoped surveillance, security events, incidents and immutable access history.</p></section></div></div>; }

function Roles({ progress }: { progress: number }) { const [selected, setSelected] = useState<DemoRole | null>(null); const role = selected ?? roleKeys[Math.min(roleKeys.length - 1, Math.floor(progress * roleKeys.length))]!; return <div className={styles.roles}><span className={styles.eyebrow}>SCOPED ACCESS / FICTIONAL VIEWS</span><h3>Everyone sees what they need.<br/><em>Nothing more.</em></h3><div className={styles.roleTabs} role="tablist" aria-label="Preview role scope">{roleKeys.map((key) => <button key={key} type="button" role="tab" aria-selected={role === key} onClick={() => setSelected(key)}>{key.toUpperCase()}</button>)}</div><motion.div layout className={styles.roleView}><div><strong>{personas[role].name}</strong><span>{personas[role].title}</span><small>DEMO VIEW / SCOPE UNCHANGED</small></div><div>{roleViews[role].map((item) => <motion.span layout key={item}><Check size={13}/>{item}</motion.span>)}</div><LockKeyhole size={18}/></motion.div><p>Production permissions remain enforced by backend RBAC, ABAC and entitlements.</p></div>; }

function Security({ kind }: { kind: SceneKind }) { if (kind === "audit") return <div className={styles.audit}><span className={styles.eyebrow}>FORT KNOX / SURVEILLANCE AUDIT</span><h3>Even watching cameras leaves a record.</h3>{[["03:12:18", "James Kamau", "VIEW CAMERA", "Block A Entrance"], ["03:13:04", "James Kamau", "PLAYBACK", "Block A Entrance"], ["03:15:22", "David Mwangi", "VIEW INCIDENT", "SEC-281"]].map(([time, who, action, target]) => <div key={time}><time>{time}</time><strong>{who}</strong><span>{action}</span><span>{target}</span><b>SUCCESS</b></div>)}</div>; if (kind === "incident") return <div className={styles.incident}><span className={styles.eyebrow}>SEC-281 / ACCOUNTABLE INVESTIGATION</span><h3>From event to evidence.</h3><div>{["Motion detected", "Security event", "Incident opened", "Footage attached", "Manager notified", "Investigation", "Resolved"].map((item, index) => <span key={item}><i>{String(index + 1).padStart(2, "0")}</i>{item}</span>)}</div></div>; return <div className={styles.security}><span className={styles.eyebrow}>FORT KNOX / SIMULATED CAMERA NETWORK</span><h3>{kind === "motion" ? "03:12 AM. Motion detected." : "Security in property context."}</h3><div className={styles.cameraGrid}>{["MAIN GATE", "PARKING", "CORRIDOR", "REAR GATE", "BLOCK B ENTRANCE"].map((name, index) => <div className={styles.camera} key={name} data-alert={kind === "motion" && index === 0}><div><i/><i/><i/></div><span><Camera size={12}/> CAM 0{index + 1} / {name}<time>03:12:18</time></span>{kind === "motion" && index === 0 && <strong>MOTION DETECTED</strong>}</div>)}</div></div>; }

function Intelligence({ kind, progress }: { kind: SceneKind; progress: number }) { if (kind === "health") return <div className={styles.health}><div><span className={styles.eyebrow}>PROPERTY HEALTH</span><div className={styles.healthArc} style={{ "--score": progress > .7 ? "91%" : "87%" } as CSSProperties}><strong>{progress > .7 ? 91 : 87}<small>/100</small></strong></div><span>PORTFOLIO / HEALTHY</span></div><div>{health.map(([label, value]) => <div key={label}><span>{label}</span><i><b style={{ width: `${value}%` }}/></i><strong>{value}</strong></div>)}</div></div>; return <div className={styles.intelligence}><span className={styles.eyebrow}>PROPERTY INTELLIGENCE / EXPLAINABLE SIGNALS</span><h3>Signals worth acting on.</h3>{[["MAINTENANCE PATTERN", "Block B has recorded 4 plumbing incidents in 60 days.", "Inspect the main water line."], ["ARREARS CONCENTRATION", "Five tenancies represent 71% of overdue rent.", "Prioritize direct follow-up."], ["VACANCY EXPOSURE", "Unit A-04 has been vacant for 46 days.", "Review listing and pricing."]].map(([type, finding, action]) => <div key={type}><small>{type}</small><strong>{finding}</strong><p>{action} <ArrowRight size={14}/></p></div>)}</div>; }

function Network() { return <div className={styles.network}><span className={styles.eyebrow}>ONE CONNECTED SYSTEM</span><h3>Everything in context.</h3><div>{["PROPERTY", "UNIT", "TENANT", "PAYMENT", "MAINTENANCE", "CONTRACTOR", "SECURITY", "EVIDENCE", "INTELLIGENCE"].map((item) => <span key={item}>{item}</span>)}</div><p>One operational history connects physical assets, people, money and decisions.</p></div>; }

function Closing({ progress }: { progress: number }) { const lines = ["Your buildings are physical.", "Your control doesn't have to be.", "You don't need to be everywhere.", "You just need to be connected to everything that matters."]; const index = Math.min(lines.length - 1, Math.floor(progress * lines.length)); return <div className={styles.closing}><span className={styles.eyebrow}>{BRAND.name} / {BRAND.descriptor}</span><AnimatePresence mode="wait"><motion.h3 key={index} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} transition={{ duration: .6 }}>{lines[index]}</motion.h3></AnimatePresence><p>{BRAND.promise}</p><Link href="/#contact">Request a private demo <ArrowRight size={16}/></Link></div>; }

function SceneContent({ scene, progress }: { scene: DemoScene; progress: number }) { switch (scene.kind) { case "opening": return <Opening progress={progress}/>; case "dashboard": return <CommandCenter/>; case "queue": return <DecisionDesk/>; case "finance": return <Finance/>; case "vacancy": return <Vacancy/>; case "tenant": case "context": case "caretaker": case "contractor": case "approval": case "progress": return <Maintenance kind={scene.kind}/>; case "evidence": return <EvidenceLedger/>; case "performance": return <Performance/>; case "passport": return <Passport/>; case "roles": return <Roles progress={progress}/>; case "security": case "motion": case "incident": case "audit": return <Security kind={scene.kind}/>; case "tiers": return <Tiers/>; case "intelligence": case "health": return <Intelligence kind={scene.kind} progress={progress}/>; case "network": return <Network/>; case "closing": return <Closing progress={progress}/>; } }

export function DemoStage({ scene, progress, captions, showLabels, theme, safeArea, prospect, platform }: Props) {
  const reducedMotion = Boolean(useReducedMotion());
  return <div className={styles.stage} data-theme={theme} data-kind={scene.kind} data-platform={platform}>
    <div className={styles.stageLine} aria-hidden="true"/>
    <div className={styles.stageTop}><span>{BRAND.name}</span><span>{showLabels ? `${prospect || portfolio.organization} / ${scene.kind.toUpperCase()}` : "FICTIONAL PRODUCT DEMO"}</span><span>ACACIA / DEMO</span></div>
    <AnimatePresence mode="wait"><motion.div className={styles.scene} key={`${scene.id}-${scene.title}`} initial={reducedMotion ? false : { opacity: 0, scale: .975, x: 18 }} animate={{ opacity: 1, scale: 1, x: 0 }} exit={reducedMotion ? {} : { opacity: 0, scale: 1.015, x: -12 }} transition={{ duration: reducedMotion ? 0 : .65, ease: [0.16, 1, .3, 1] }}><SceneContent scene={scene} progress={progress}/></motion.div></AnimatePresence>
    {captions && <div className={styles.caption}>{scene.narration}</div>}
    {safeArea && <div className={styles.safeArea} aria-hidden="true"/>}
    <div className={styles.stageFoot}><span>FICTIONAL PORTFOLIO / NO LIVE OPERATIONS</span><span><Play size={10}/> {scene.title}</span></div>
  </div>;
}
