import type {
  ArrearsCase,
  Building,
  Contractor,
  DocumentRecord,
  Expense,
  FinancialPeriod,
  Floor,
  Incident,
  Inspection,
  MaintenanceRequest,
  NotificationRecord,
  Payment,
  Property,
  RentCharge,
  SecurityCamera,
  SecurityEvent,
  ServiceChargeAssessment,
  Tenant,
  Tenancy,
  Unit,
} from "../data/resource-types";
import type { Organization } from "../../types/organization";
import type {
  CommandCenter,
  CommandCenterProperty,
  HealthGrade,
} from "../../types/api";

export const demoOrganization: Organization = {
  _id: "demo-org-dapini",
  name: "Dapini Properties",
  slug: "dapini-properties",
  status: "ACTIVE",
  settings: {
    managementPhone: "+254700000002",
    managementEmail: "residents@dapini.demo",
    emergencyPhone: "+254700000003",
    officeHours: "Monday to Saturday, 8:00 AM - 6:00 PM",
  },
  createdAt: "2026-01-05T08:00:00.000Z",
};

export const demoProperties: Property[] = [
  {
    _id: "demo-property-1",
    organizationId: demoOrganization._id,
    name: "Dapini Heights",
    code: "DPH-001",
    description:
      "Premium mixed residential estate with managed apartments and resident services.",
    propertyType: "RESIDENTIAL_ESTATE",
    status: "ACTIVE",
    totalUnits: 12,
    address: {
      addressLine1: "14 Riverside Drive",
      city: "Nairobi",
      county: "Nairobi",
      country: "Kenya",
    },
    location: { type: "Point", coordinates: [36.8107, -1.2684] },
  },
  {
    _id: "demo-property-2",
    organizationId: demoOrganization._id,
    name: "Dapini Business Park",
    code: "DBP-002",
    description:
      "Commercial property with offices, retail frontage and controlled access.",
    propertyType: "MIXED_USE",
    status: "ACTIVE",
    totalUnits: 8,
    address: {
      addressLine1: "22 Mombasa Road",
      city: "Nairobi",
      county: "Nairobi",
      country: "Kenya",
    },
    location: { type: "Point", coordinates: [36.8796, -1.3226] },
  },
];

export const demoBuildings: Building[] = [
  {
    _id: "demo-building-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    name: "North Tower",
    code: "NT-01",
    status: "ACTIVE",
    totalFloors: 4,
    totalUnits: 8,
  },
  {
    _id: "demo-building-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    name: "Garden Wing",
    code: "GW-01",
    status: "ACTIVE",
    totalFloors: 2,
    totalUnits: 4,
  },
  {
    _id: "demo-building-3",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-2",
    name: "Business Block A",
    code: "BBA-01",
    status: "ACTIVE",
    totalFloors: 3,
    totalUnits: 8,
  },
];

export const demoFloors: Floor[] = [
  {
    _id: "demo-floor-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    name: "Ground Floor",
    level: 0,
    code: "NT-G",
    status: "ACTIVE",
    totalUnits: 2,
  },
  {
    _id: "demo-floor-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    name: "First Floor",
    level: 1,
    code: "NT-1",
    status: "ACTIVE",
    totalUnits: 2,
  },
  {
    _id: "demo-floor-3",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    name: "Second Floor",
    level: 2,
    code: "NT-2",
    status: "ACTIVE",
    totalUnits: 2,
  },
  {
    _id: "demo-floor-4",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    name: "Third Floor",
    level: 3,
    code: "NT-3",
    status: "ACTIVE",
    totalUnits: 2,
  },
  {
    _id: "demo-floor-5",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    name: "Ground Floor",
    level: 0,
    code: "GW-G",
    status: "ACTIVE",
    totalUnits: 2,
  },
  {
    _id: "demo-floor-6",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    name: "First Floor",
    level: 1,
    code: "GW-1",
    status: "ACTIVE",
    totalUnits: 2,
  },
  {
    _id: "demo-floor-7",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-2",
    buildingId: "demo-building-3",
    name: "Ground Floor",
    level: 0,
    code: "BBA-G",
    status: "ACTIVE",
    totalUnits: 3,
  },
  {
    _id: "demo-floor-8",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-2",
    buildingId: "demo-building-3",
    name: "First Floor",
    level: 1,
    code: "BBA-1",
    status: "ACTIVE",
    totalUnits: 3,
  },
  {
    _id: "demo-floor-9",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-2",
    buildingId: "demo-building-3",
    name: "Second Floor",
    level: 2,
    code: "BBA-2",
    status: "ACTIVE",
    totalUnits: 2,
  },
];

const unit = (
  id: string,
  buildingId: string,
  floorId: string,
  name: string,
  code: string,
  type: Unit["unitType"],
  status: Unit["status"],
  rent: number,
  bedrooms = 1,
): Unit => ({
  _id: id,
  organizationId: demoOrganization._id,
  propertyId:
    buildingId === "demo-building-3" ? "demo-property-2" : "demo-property-1",
  buildingId,
  floorId,
  name,
  code,
  unitType: type,
  status,
  monthlyRent: rent,
  serviceCharge: 650,
  areaSqm: 58,
  bedrooms,
  bathrooms: bedrooms,
  amenities: ["Parking", "Security", "Water backup"],
});

export const demoUnits: Unit[] = [
  unit(
    "demo-unit-101",
    "demo-building-1",
    "demo-floor-1",
    "Unit 101",
    "NT-101",
    "ONE_BEDROOM",
    "OCCUPIED",
    45000,
  ),
  unit(
    "demo-unit-102",
    "demo-building-1",
    "demo-floor-1",
    "Unit 102",
    "NT-102",
    "ONE_BEDROOM",
    "OCCUPIED",
    48000,
  ),
  unit(
    "demo-unit-201",
    "demo-building-1",
    "demo-floor-2",
    "Unit 201",
    "NT-201",
    "TWO_BEDROOM",
    "OCCUPIED",
    68000,
    2,
  ),
  unit(
    "demo-unit-202",
    "demo-building-1",
    "demo-floor-2",
    "Unit 202",
    "NT-202",
    "TWO_BEDROOM",
    "VACANT",
    68000,
    2,
  ),
  unit(
    "demo-unit-301",
    "demo-building-1",
    "demo-floor-3",
    "Unit 301",
    "NT-301",
    "ONE_BEDROOM",
    "OCCUPIED",
    52000,
  ),
  unit(
    "demo-unit-302",
    "demo-building-1",
    "demo-floor-3",
    "Unit 302",
    "NT-302",
    "ONE_BEDROOM",
    "MAINTENANCE",
    52000,
  ),
  unit(
    "demo-unit-401",
    "demo-building-1",
    "demo-floor-4",
    "Penthouse 401",
    "NT-401",
    "THREE_PLUS_BEDROOM",
    "OCCUPIED",
    120000,
    3,
  ),
  unit(
    "demo-unit-402",
    "demo-building-1",
    "demo-floor-4",
    "Penthouse 402",
    "NT-402",
    "THREE_PLUS_BEDROOM",
    "RESERVED",
    115000,
    3,
  ),
  unit(
    "demo-unit-g01",
    "demo-building-2",
    "demo-floor-5",
    "Garden 01",
    "GW-01",
    "BEDSITTER",
    "OCCUPIED",
    30000,
  ),
  unit(
    "demo-unit-g02",
    "demo-building-2",
    "demo-floor-5",
    "Garden 02",
    "GW-02",
    "BEDSITTER",
    "VACANT",
    30000,
  ),
  unit(
    "demo-unit-g11",
    "demo-building-2",
    "demo-floor-6",
    "Garden 11",
    "GW-11",
    "ONE_BEDROOM",
    "OCCUPIED",
    42000,
  ),
  unit(
    "demo-unit-g12",
    "demo-building-2",
    "demo-floor-6",
    "Garden 12",
    "GW-12",
    "ONE_BEDROOM",
    "OCCUPIED",
    42000,
  ),
  unit(
    "demo-unit-c01",
    "demo-building-3",
    "demo-floor-7",
    "Office 01",
    "BBA-01",
    "OFFICE",
    "OCCUPIED",
    85000,
  ),
  unit(
    "demo-unit-c02",
    "demo-building-3",
    "demo-floor-7",
    "Office 02",
    "BBA-02",
    "OFFICE",
    "OCCUPIED",
    90000,
  ),
  unit(
    "demo-unit-c03",
    "demo-building-3",
    "demo-floor-7",
    "Retail 03",
    "BBA-03",
    "RETAIL",
    "OCCUPIED",
    110000,
  ),
  unit(
    "demo-unit-c11",
    "demo-building-3",
    "demo-floor-8",
    "Office 11",
    "BBA-11",
    "OFFICE",
    "OCCUPIED",
    95000,
  ),
  unit(
    "demo-unit-c12",
    "demo-building-3",
    "demo-floor-8",
    "Office 12",
    "BBA-12",
    "OFFICE",
    "VACANT",
    95000,
  ),
  unit(
    "demo-unit-c13",
    "demo-building-3",
    "demo-floor-8",
    "Office 13",
    "BBA-13",
    "OFFICE",
    "OCCUPIED",
    100000,
  ),
  unit(
    "demo-unit-c21",
    "demo-building-3",
    "demo-floor-9",
    "Office 21",
    "BBA-21",
    "OFFICE",
    "OCCUPIED",
    105000,
  ),
  unit(
    "demo-unit-c22",
    "demo-building-3",
    "demo-floor-9",
    "Office 22",
    "BBA-22",
    "OFFICE",
    "VACANT",
    105000,
  ),
];

export const demoTenants: Tenant[] = [
  {
    _id: "demo-tenant-1",
    organizationId: demoOrganization._id,
    userId: "demo-user-tenant-1",
    status: "ACTIVE",
    nationalIdLast4: "4821",
    emergencyContact: {
      name: "Amina Hassan",
      phone: "+254711000101",
      relationship: "Sister",
    },
  },
  {
    _id: "demo-tenant-2",
    organizationId: demoOrganization._id,
    userId: "demo-user-tenant-2",
    status: "ACTIVE",
    nationalIdLast4: "1904",
    emergencyContact: {
      name: "David Otieno",
      phone: "+254722000202",
      relationship: "Brother",
    },
  },
  {
    _id: "demo-tenant-3",
    organizationId: demoOrganization._id,
    userId: "demo-user-tenant-3",
    status: "ACTIVE",
    nationalIdLast4: "7718",
    emergencyContact: {
      name: "Miriam Wanjiku",
      phone: "+254733000303",
      relationship: "Mother",
    },
  },
  {
    _id: "demo-tenant-4",
    organizationId: demoOrganization._id,
    userId: "demo-user-tenant-4",
    status: "ACTIVE",
    nationalIdLast4: "4427",
  },
  {
    _id: "demo-tenant-5",
    organizationId: demoOrganization._id,
    userId: "demo-user-tenant-5",
    status: "ACTIVE",
    nationalIdLast4: "6109",
  },
  {
    _id: "demo-tenant-6",
    organizationId: demoOrganization._id,
    userId: "demo-user-tenant-6",
    status: "ACTIVE",
    nationalIdLast4: "3340",
  },
  {
    _id: "demo-tenant-7",
    organizationId: demoOrganization._id,
    userId: "demo-user-tenant-7",
    status: "PROSPECT",
    nationalIdLast4: "4281",
  },
];

export const demoTenancies: Tenancy[] = [
  {
    _id: "demo-tenancy-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-1",
    unitId: "demo-unit-101",
    tenantId: "demo-tenant-1",
    status: "ACTIVE",
    leaseNumber: "DAPH-2026-001",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    monthlyRent: 45000,
    serviceCharge: 650,
    depositAmount: 90000,
    billingDay: 1,
    noticePeriodDays: 60,
    activatedAt: "2026-01-01T08:00:00.000Z",
  },
  {
    _id: "demo-tenancy-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-1",
    unitId: "demo-unit-102",
    tenantId: "demo-tenant-2",
    status: "ACTIVE",
    leaseNumber: "DAPH-2026-002",
    startDate: "2026-02-01",
    endDate: "2027-01-31",
    monthlyRent: 48000,
    serviceCharge: 650,
    depositAmount: 96000,
    billingDay: 1,
    noticePeriodDays: 60,
    activatedAt: "2026-02-01T08:00:00.000Z",
  },
  {
    _id: "demo-tenancy-3",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-2",
    unitId: "demo-unit-201",
    tenantId: "demo-tenant-3",
    status: "NOTICE",
    leaseNumber: "DAPH-2025-017",
    startDate: "2025-07-01",
    endDate: "2026-06-30",
    monthlyRent: 68000,
    serviceCharge: 650,
    depositAmount: 136000,
    billingDay: 1,
    noticePeriodDays: 60,
  },
  {
    _id: "demo-tenancy-4",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-3",
    unitId: "demo-unit-301",
    tenantId: "demo-tenant-4",
    status: "ACTIVE",
    leaseNumber: "DAPH-2026-004",
    startDate: "2026-03-01",
    endDate: "2027-02-28",
    monthlyRent: 52000,
    serviceCharge: 650,
    depositAmount: 104000,
    billingDay: 5,
    noticePeriodDays: 60,
    activatedAt: "2026-03-01T08:00:00.000Z",
  },
  {
    _id: "demo-tenancy-5",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    floorId: "demo-floor-5",
    unitId: "demo-unit-g01",
    tenantId: "demo-tenant-5",
    status: "ACTIVE",
    leaseNumber: "DAPH-2026-005",
    startDate: "2026-01-15",
    endDate: "2026-12-31",
    monthlyRent: 30000,
    serviceCharge: 650,
    depositAmount: 60000,
    billingDay: 5,
    noticePeriodDays: 30,
    activatedAt: "2026-01-15T08:00:00.000Z",
  },
  {
    _id: "demo-tenancy-6",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    floorId: "demo-floor-6",
    unitId: "demo-unit-g11",
    tenantId: "demo-tenant-6",
    status: "ACTIVE",
    leaseNumber: "DAPH-2026-006",
    startDate: "2026-02-15",
    endDate: "2027-02-14",
    monthlyRent: 42000,
    serviceCharge: 650,
    depositAmount: 84000,
    billingDay: 5,
    noticePeriodDays: 30,
    activatedAt: "2026-02-15T08:00:00.000Z",
  },
  {
    _id: "demo-tenancy-7",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    floorId: "demo-floor-5",
    unitId: "demo-unit-g02",
    tenantId: "demo-tenant-7",
    status: "PENDING",
    leaseNumber: "DAPH-2026-007",
    startDate: "2026-10-01",
    endDate: "2027-09-30",
    monthlyRent: 34000,
    serviceCharge: 650,
    depositAmount: 68000,
    billingDay: 5,
    noticePeriodDays: 30,
  },
];

const today = new Date();
const iso = (days: number) =>
  new Date(today.getTime() + days * 86400000).toISOString();

export const demoRentCharges: RentCharge[] = demoTenancies.map((t, index) => {
  const total = t.monthlyRent + (t.serviceCharge ?? 0);
  const paid = index === 2 ? 30000 : index === 5 ? 25000 : total;
  return {
    _id: `demo-rent-${index + 1}`,
    organizationId: demoOrganization._id,
    propertyId: t.propertyId,
    buildingId: t.buildingId,
    floorId: t.floorId,
    unitId: t.unitId,
    tenantId: t.tenantId,
    tenancyId: t._id,
    periodStart: "2026-09-01",
    periodEnd: "2026-09-30",
    dueDate: "2026-09-05",
    rentAmount: t.monthlyRent,
    serviceChargeAmount: t.serviceCharge ?? 0,
    adjustments: 0,
    totalAmount: total,
    paidAmount: paid,
    balanceAmount: total - paid,
    currency: "KES",
    status:
      paid === total ? "PAID" : index === 2 ? "OVERDUE" : "PARTIALLY_PAID",
  };
});

export const demoPayments: Payment[] = demoTenancies.map((t, index) => ({
  _id: `demo-payment-${index + 1}`,
  organizationId: demoOrganization._id,
  propertyId: t.propertyId,
  buildingId: t.buildingId,
  floorId: t.floorId,
  unitId: t.unitId,
  tenantId: t.tenantId,
  tenancyId: t._id,
  amount:
    index === 2
      ? 30000
      : index === 5
        ? 25000
        : t.monthlyRent + (t.serviceCharge ?? 0),
  currency: "KES",
  method: index % 2 === 0 ? "MPESA" : "BANK_TRANSFER",
  status: "CONFIRMED",
  provider: index % 2 === 0 ? "M-Pesa" : "KCB",
  providerTransactionId: `DEMO-TXN-${String(index + 1).padStart(4, "0")}`,
  receiptNumber: `DPR-${String(index + 1).padStart(5, "0")}`,
  paidAt: iso(-3 - index),
  confirmedAt: iso(-3 - index),
}));

export const demoExpenses: Expense[] = [
  {
    _id: "demo-expense-review",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    category: "SUPPLIES",
    description: "Emergency plumbing isolation valves",
    amount: 14600,
    currency: "KES",
    incurredAt: iso(-1),
    status: "SUBMITTED",
    vendorName: "Industrial Hardware Kenya",
    sourceType: "MANUAL",
    sourceId: "demo-expense-review",
    evidenceIds: [],
  },
  {
    _id: "demo-expense-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    category: "MAINTENANCE",
    description: "Water pump replacement",
    amount: 38500,
    currency: "KES",
    incurredAt: iso(-12),
    paidAt: iso(-8),
    status: "PAID",
    vendorName: "Apex Mechanical",
    contractorId: "demo-contractor-1",
    sourceType: "MAINTENANCE",
    sourceId: "demo-maint-1",
    evidenceIds: [],
  },
  {
    _id: "demo-expense-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    category: "SECURITY",
    description: "Gate access controller service",
    amount: 22000,
    currency: "KES",
    incurredAt: iso(-9),
    status: "APPROVED",
    vendorName: "SecureGate Kenya",
    contractorId: "demo-contractor-2",
    sourceType: "MANUAL",
    sourceId: "demo-expense-2",
    evidenceIds: [],
  },
  {
    _id: "demo-expense-3",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-2",
    buildingId: "demo-building-3",
    category: "UTILITIES",
    description: "Common-area electricity",
    amount: 74600,
    currency: "KES",
    incurredAt: iso(-4),
    paidAt: iso(-2),
    status: "PAID",
    vendorName: "Kenya Power",
    sourceType: "MANUAL",
    sourceId: "demo-expense-3",
    evidenceIds: [],
  },
];

export const demoArrears: ArrearsCase[] = [
  {
    _id: "demo-arrears-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-2",
    unitId: "demo-unit-201",
    tenantId: "demo-tenant-3",
    tenancyId: "demo-tenancy-3",
    rentChargeIds: ["demo-rent-3"],
    amountOutstanding: 38650,
    currency: "KES",
    status: "CONTACTED",
    lastContactedAt: iso(-1),
    notes: "Tenant committed to settle balance within 5 days.",
  },
  {
    _id: "demo-arrears-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    floorId: "demo-floor-6",
    unitId: "demo-unit-g11",
    tenantId: "demo-tenant-6",
    tenancyId: "demo-tenancy-6",
    rentChargeIds: ["demo-rent-6"],
    amountOutstanding: 17650,
    currency: "KES",
    status: "PROMISED",
    promiseDate: iso(3),
  },
];

export const demoMaintenance: MaintenanceRequest[] = [
  {
    _id: "demo-maint-quote",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-1",
    unitId: "demo-unit-101",
    tenantId: "demo-tenant-1",
    reportedByUserId: "demo-user-tenant-1",
    contractorId: "demo-contractor-1",
    title: "Replace kitchen mixer tap",
    description:
      "Inspect the worn mixer, quote for replacement parts, and confirm the earliest service window.",
    category: "PLUMBING",
    priority: "MEDIUM",
    status: "ASSIGNED",
    evidenceIds: [],
    approvalRequired: false,
    createdAt: iso(-1),
    updatedAt: iso(-1),
  },
  {
    _id: "demo-maint-approved",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-1",
    unitId: "demo-unit-101",
    tenantId: "demo-tenant-1",
    reportedByUserId: "demo-user-tenant-1",
    contractorId: "demo-contractor-1",
    title: "Service booster pump",
    description:
      "Approved preventive service for the pressure booster pump and inlet filter.",
    category: "PLUMBING",
    priority: "LOW",
    status: "APPROVED",
    evidenceIds: [],
    quoteAmount: 12500,
    approvedAmount: 12500,
    approvalRequired: false,
    createdAt: iso(-3),
    updatedAt: iso(-2),
  },
  {
    _id: "demo-maint-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-1",
    unitId: "demo-unit-101",
    tenantId: "demo-tenant-1",
    reportedByUserId: "demo-user-tenant-1",
    contractorId: "demo-contractor-1",
    title: "Low water pressure",
    description: "Resident reports inconsistent pressure during evening hours.",
    category: "PLUMBING",
    priority: "HIGH",
    status: "IN_PROGRESS",
    evidenceIds: [],
    quoteAmount: 38500,
    approvedAmount: 38500,
    approvalRequired: true,
  },
  {
    _id: "demo-maint-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-3",
    unitId: "demo-unit-302",
    tenantId: "demo-tenant-4",
    reportedByUserId: "demo-user-tenant-4",
    contractorId: "demo-contractor-2",
    title: "Electrical fault",
    description: "Circuit breaker trips intermittently.",
    category: "ELECTRICAL",
    priority: "EMERGENCY",
    status: "APPROVAL_REQUIRED",
    evidenceIds: [],
    quoteAmount: 18000,
    approvalRequired: true,
  },
  {
    _id: "demo-maint-owner-verify",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-2",
    buildingId: "demo-building-2",
    floorId: "demo-floor-4",
    unitId: "demo-unit-401",
    tenantId: "demo-tenant-5",
    reportedByUserId: "demo-user-tenant-5",
    contractorId: "demo-contractor-1",
    title: "Water pump replacement",
    description: "Replacement completed and awaiting owner verification.",
    category: "PLUMBING",
    priority: "HIGH",
    status: "COMPLETED",
    evidenceIds: [],
    quoteAmount: 32000,
    approvedAmount: 30000,
    actualAmount: 29600,
    approvalRequired: true,
    completedAt: iso(-1),
  },
  {
    _id: "demo-maint-owner-close",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-1",
    unitId: "demo-unit-101",
    tenantId: "demo-tenant-1",
    reportedByUserId: "demo-user-tenant-1",
    contractorId: "demo-contractor-1",
    title: "Lobby access reader repair",
    description: "Repair verified and ready for final closure.",
    category: "SECURITY",
    priority: "MEDIUM",
    status: "VERIFIED",
    evidenceIds: [],
    quoteAmount: 12000,
    approvedAmount: 12000,
    actualAmount: 11800,
    approvalRequired: false,
    completedAt: iso(-2),
    verifiedAt: iso(-1),
  },
  {
    _id: "demo-maint-3",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    floorId: "demo-floor-5",
    unitId: "demo-unit-g02",
    reportedByUserId: "demo-user-manager",
    title: "Vacant unit inspection",
    description: "Pre-letting inspection and touch-up cleaning.",
    category: "CLEANING",
    priority: "LOW",
    status: "NEW",
    evidenceIds: [],
    approvalRequired: false,
  },
];

export const demoInspections: Inspection[] = [
  {
    _id: "demo-inspection-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-1",
    unitId: "demo-unit-102",
    tenancyId: "demo-tenancy-2",
    type: "ROUTINE",
    status: "DRAFT",
    checklist: [],
    meterReadings: [],
    notes: "Quarterly resident unit condition check.",
    evidenceIds: [],
    inspectedBy: "demo-user-manager",
    createdAt: iso(-2),
    updatedAt: iso(-2),
  },
  {
    _id: "demo-inspection-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-2",
    unitId: "demo-unit-201",
    tenancyId: "demo-tenancy-3",
    type: "MOVE_OUT",
    status: "COMPLETED",
    overallCondition: "FAIR",
    checklist: [],
    meterReadings: [],
    notes: "Minor wall touch-up required before handover.",
    evidenceIds: [],
    inspectedBy: "demo-user-manager",
    completedAt: iso(-4),
    createdAt: iso(-5),
    updatedAt: iso(-4),
  },
];

export const demoNotifications: NotificationRecord[] = [
  {
    _id: "demo-notification-caretaker-1",
    organizationId: demoOrganization._id,
    recipientUserId: "demo-user-caretaker",
    channel: "IN_APP",
    type: "SITE_ALERT",
    title: "Safety round needs attention",
    body: "A loose stairwell handrail and one routine inspection are waiting in your site queue.",
    status: "DELIVERED",
    priority: "HIGH",
    sentAt: iso(0),
    createdAt: iso(0),
  },
  {
    _id: "demo-notification-landlord-1",
    organizationId: demoOrganization._id,
    recipientUserId: "demo-user-landlord",
    channel: "IN_APP",
    type: "PORTFOLIO_ALERT",
    title: "Portfolio approvals need attention",
    body: "An emergency maintenance quote and a supplier expense are waiting for owner review.",
    status: "DELIVERED",
    priority: "HIGH",
    sentAt: iso(0),
    createdAt: iso(0),
  },
  {
    _id: "demo-notification-manager-1",
    organizationId: demoOrganization._id,
    recipientUserId: "demo-user-manager",
    channel: "IN_APP",
    type: "MAINTENANCE_UPDATED",
    title: "Emergency quote awaiting approval",
    body: "The electrical fault at Unit 302 has a contractor quote ready for your review.",
    status: "DELIVERED",
    priority: "URGENT",
    sentAt: iso(0),
    createdAt: iso(0),
  },
  {
    _id: "demo-notification-contractor-1",
    organizationId: demoOrganization._id,
    recipientUserId: "demo-user-contractor-1",
    channel: "IN_APP",
    type: "MAINTENANCE_UPDATED",
    title: "New quote requested",
    body: "A kitchen mixer replacement has been assigned to your team for assessment and quotation.",
    status: "DELIVERED",
    priority: "HIGH",
    sentAt: iso(0),
    createdAt: iso(0),
  },
  {
    _id: "demo-notification-1",
    organizationId: demoOrganization._id,
    recipientUserId: "demo-user-tenant-1",
    channel: "IN_APP",
    type: "MAINTENANCE_UPDATED",
    title: "Maintenance team assigned",
    body: "Apex Mechanical Services is handling your low water pressure request.",
    status: "DELIVERED",
    priority: "HIGH",
    sentAt: iso(0),
    createdAt: iso(0),
  },
  {
    _id: "demo-notification-2",
    organizationId: demoOrganization._id,
    recipientUserId: "demo-user-tenant-1",
    channel: "IN_APP",
    type: "PROPERTY_NOTICE",
    title: "Water system inspection",
    body: "The building water system will be inspected on Saturday between 10:00 AM and noon.",
    status: "DELIVERED",
    priority: "NORMAL",
    sentAt: iso(-1),
    createdAt: iso(-1),
  },
  {
    _id: "demo-notification-3",
    organizationId: demoOrganization._id,
    recipientUserId: "demo-user-tenant-1",
    channel: "IN_APP",
    type: "PAYMENT_CONFIRMED",
    title: "Rent payment confirmed",
    body: "Your latest rent payment has been confirmed and added to your account.",
    status: "READ",
    priority: "NORMAL",
    sentAt: iso(-4),
    readAt: iso(-3),
    createdAt: iso(-4),
  },
];

export const demoContractors: Contractor[] = [
  {
    _id: "demo-contractor-1",
    organizationId: demoOrganization._id,
    userId: "demo-user-contractor-1",
    name: "Apex Mechanical Services",
    phone: "+254700100001",
    email: "ops@apexmechanical.demo",
    trade: "Plumbing & Pumps",
    status: "ACTIVE",
    rating: 4.7,
    performance: {
      totalJobs: 34,
      completedJobs: 31,
      completionRate: 91.2,
      averageCompletionHours: 29,
      overBudgetJobs: 3,
      overBudgetRate: 8.8,
    },
  },
  {
    _id: "demo-contractor-2",
    organizationId: demoOrganization._id,
    userId: "demo-user-contractor-2",
    name: "VoltPro Electrical",
    phone: "+254700100002",
    email: "service@voltpro.demo",
    trade: "Electrical",
    status: "ACTIVE",
    rating: 4.5,
    performance: {
      totalJobs: 27,
      completedJobs: 25,
      completionRate: 92.6,
      averageCompletionHours: 22,
      overBudgetJobs: 2,
      overBudgetRate: 7.4,
    },
  },
  {
    _id: "demo-contractor-3",
    organizationId: demoOrganization._id,
    name: "SecureGate Kenya",
    phone: "+254700100003",
    email: "support@securegate.demo",
    trade: "Security Systems",
    status: "ACTIVE",
    rating: 4.8,
    performance: {
      totalJobs: 19,
      completedJobs: 18,
      completionRate: 94.7,
      averageCompletionHours: 18,
      overBudgetJobs: 1,
      overBudgetRate: 5.3,
    },
  },
];

export const demoDocuments: DocumentRecord[] = [
  {
    _id: "demo-doc-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    title: "Dapini Heights Insurance Certificate",
    category: "INSURANCE",
    fileName: "dapini-heights-insurance.pdf",
    mimeType: "application/pdf",
    sizeBytes: 842000,
    storageProvider: "S3",
    storageKey: "demo/dapini-heights-insurance.pdf",
    sha256: "demo-sha-001",
    version: 1,
    visibility: "STAFF",
    status: "ACTIVE",
    tags: ["insurance", "property"],
  },
  {
    _id: "demo-doc-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    unitId: "demo-unit-101",
    title: "Lease — Unit 101",
    category: "LEASE",
    fileName: "lease-unit-101.pdf",
    mimeType: "application/pdf",
    sizeBytes: 412000,
    storageProvider: "S3",
    storageKey: "demo/lease-unit-101.pdf",
    sha256: "demo-sha-002",
    version: 2,
    visibility: "TENANT",
    status: "ACTIVE",
    tags: ["lease", "unit-101"],
  },
  {
    _id: "demo-doc-3",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    title: "Q3 Fire Safety Inspection",
    category: "INSPECTION",
    fileName: "q3-fire-inspection.pdf",
    mimeType: "application/pdf",
    sizeBytes: 228000,
    storageProvider: "S3",
    storageKey: "demo/q3-fire-inspection.pdf",
    sha256: "demo-sha-003",
    version: 1,
    visibility: "STAFF",
    status: "ACTIVE",
    tags: ["inspection", "fire-safety"],
  },
  {
    _id: "demo-doc-4",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    unitId: "demo-unit-201",
    title: "Rent Payment Receipt — September",
    category: "RECEIPT",
    fileName: "receipt-demo-0003.pdf",
    mimeType: "application/pdf",
    sizeBytes: 114000,
    storageProvider: "S3",
    storageKey: "demo/receipt-demo-0003.pdf",
    sha256: "demo-sha-004",
    version: 1,
    visibility: "TENANT",
    status: "ACTIVE",
    tags: ["receipt", "rent"],
  },
];

export const demoCameras: SecurityCamera[] = [
  {
    _id: "demo-camera-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    name: "North Gate Overview",
    cameraCode: "DPH-CAM-01",
    provider: "Demo NVR",
    connectionType: "NVR",
    status: "ONLINE",
    capabilities: ["LIVE", "PLAYBACK", "MOTION"],
    lastSeenAt: iso(0),
    lastHeartbeatAt: iso(0),
  },
  {
    _id: "demo-camera-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    name: "Garden Wing Corridor",
    cameraCode: "DPH-CAM-02",
    provider: "Demo NVR",
    connectionType: "NVR",
    status: "ONLINE",
    capabilities: ["LIVE", "PLAYBACK"],
    lastSeenAt: iso(0),
    lastHeartbeatAt: iso(0),
  },
  {
    _id: "demo-camera-3",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-2",
    buildingId: "demo-building-3",
    name: "Business Park Parking",
    cameraCode: "DBP-CAM-01",
    provider: "Demo NVR",
    connectionType: "NVR",
    status: "DEGRADED",
    capabilities: ["LIVE", "MOTION"],
    lastSeenAt: iso(-1),
    lastHeartbeatAt: iso(-1),
  },
];

export const demoSecurityEvents: SecurityEvent[] = [
  {
    _id: "demo-security-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    cameraId: "demo-camera-1",
    type: "PERSON_DETECTED",
    severity: "INFO",
    status: "RESOLVED",
    detectedAt: iso(-1),
    source: "CCTV",
    confidence: 0.97,
    snapshotEvidenceIds: [],
    description: "Normal resident movement detected at North Gate.",
  },
  {
    _id: "demo-security-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-2",
    buildingId: "demo-building-3",
    cameraId: "demo-camera-3",
    type: "CAMERA_OFFLINE",
    severity: "HIGH",
    status: "OPEN",
    detectedAt: iso(-2),
    source: "CCTV",
    snapshotEvidenceIds: [],
    description: "Parking camera heartbeat below expected threshold.",
  },
  {
    _id: "demo-security-3",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    cameraId: "demo-camera-1",
    type: "ACCESS_DENIED",
    severity: "MEDIUM",
    status: "ACKNOWLEDGED",
    detectedAt: iso(-3),
    source: "ACCESS_CONTROL",
    snapshotEvidenceIds: [],
    description:
      "Three denied credentials at the north gate within ten minutes.",
  },
];

export const demoIncidents: Incident[] = [
  {
    _id: "demo-incident-1",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-1",
    floorId: "demo-floor-1",
    unitId: "demo-unit-102",
    incidentNumber: "INC-20260924-00001",
    title: "North stairwell handrail loose",
    description: "The lower handrail bracket has separated from the wall.",
    category: "SAFETY",
    severity: "HIGH",
    status: "OPEN",
    reportedAt: iso(0),
    sourceEventIds: [],
    evidenceIds: [],
    documentIds: [],
    createdAt: iso(0),
    updatedAt: iso(0),
  },
  {
    _id: "demo-incident-2",
    organizationId: demoOrganization._id,
    propertyId: "demo-property-1",
    buildingId: "demo-building-2",
    floorId: "demo-floor-5",
    unitId: "demo-unit-501",
    incidentNumber: "INC-20260923-00002",
    title: "Garden gate forced open",
    description: "Gate secured temporarily while the lock is assessed.",
    category: "ACCESS_CONTROL",
    severity: "MEDIUM",
    status: "INVESTIGATING",
    reportedAt: iso(-1),
    sourceEventIds: [],
    evidenceIds: [],
    documentIds: [],
    createdAt: iso(-1),
    updatedAt: iso(-1),
  },
];

export const demoServiceCharges: ServiceChargeAssessment[] = demoTenancies.map(
  (t, index) => ({
    _id: `demo-service-charge-${index + 1}`,
    organizationId: demoOrganization._id,
    propertyId: t.propertyId,
    buildingId: t.buildingId,
    floorId: t.floorId,
    unitId: t.unitId,
    tenantId: t.tenantId,
    tenancyId: t._id,
    periodStart: "2026-09-01",
    periodEnd: "2026-09-30",
    amount: t.serviceCharge ?? 0,
    currency: "KES",
    status: "INVOICED",
    description: "September service charge",
  }),
);

export const demoFinancialPeriods: FinancialPeriod[] = [
  {
    _id: "demo-period-2026-08",
    organizationId: demoOrganization._id,
    periodStart: "2026-08-01",
    periodEnd: "2026-08-31",
    status: "CLOSED",
    closedAt: iso(-15),
  },
  {
    _id: "demo-period-2026-09",
    organizationId: demoOrganization._id,
    periodStart: "2026-09-01",
    periodEnd: "2026-09-30",
    status: "OPEN",
  },
];

export const demoUsers = [
  {
    _id: "demo-user-landlord",
    firstName: "Hillary",
    lastName: "Murimi",
    email: "landlord@dapini.demo",
    phone: "+254700000001",
    role: "LANDLORD",
  },
  {
    _id: "demo-user-manager",
    firstName: "Shadrack",
    lastName: "Cheruiyot",
    email: "manager@dapini.demo",
    phone: "+254700000002",
    role: "PROPERTY_MANAGER",
  },
  {
    _id: "demo-user-caretaker",
    firstName: "Peter",
    lastName: "Kiptoo",
    email: "caretaker@dapini.demo",
    phone: "+254700000003",
    role: "CARETAKER",
  },
  {
    _id: "demo-user-contractor-1",
    firstName: "Apex",
    lastName: "Operations",
    email: "ops@apexmechanical.demo",
    phone: "+254700100001",
    role: "CONTRACTOR",
  },
  {
    _id: "demo-user-contractor-2",
    firstName: "VoltPro",
    lastName: "Operations",
    email: "service@voltpro.demo",
    phone: "+254700100002",
    role: "CONTRACTOR",
  },
  {
    _id: "demo-user-contractor-3",
    firstName: "SecureGate",
    lastName: "Operations",
    email: "support@securegate.demo",
    phone: "+254700100003",
    role: "CONTRACTOR",
  },
  ...demoTenants.map((tenant, index) => ({
    _id: tenant.userId,
    firstName: [
      "Aisha",
      "Brian",
      "Miriam",
      "Kevin",
      "Faith",
      "Samuel",
      "Nadia",
    ][index],
    lastName: [
      "Hassan",
      "Otieno",
      "Wanjiku",
      "Mwangi",
      "Njeri",
      "Kiprotich",
      "Ali",
    ][index],
    email: `tenant${index + 1}@dapini.demo`,
    phone: `+254711000${101 + index}`,
    role: "TENANT",
  })),
];

function tenantName(tenantId: string): string {
  return (
    demoUsers.find(
      (user) =>
        user._id ===
        demoTenants.find((tenant) => tenant._id === tenantId)?.userId,
    )?.firstName ?? "Resident"
  );
}

export function financialReport(): Record<string, unknown> {
  const billed = demoRentCharges.reduce(
    (sum, item) => sum + item.totalAmount,
    0,
  );
  const collected = demoRentCharges.reduce(
    (sum, item) => sum + item.paidAmount,
    0,
  );
  const expenses = demoExpenses.reduce((sum, item) => sum + item.amount, 0);
  return {
    rentBilled:
      billed - demoServiceCharges.reduce((sum, item) => sum + item.amount, 0),
    serviceChargesBilled: demoServiceCharges.reduce(
      (sum, item) => sum + item.amount,
      0,
    ),
    totalBilled: billed,
    totalCollected: collected,
    collectionRate: Math.round((collected / billed) * 1000) / 10,
    outstanding: billed - collected,
    expensesByCategory: demoExpenses.reduce<Record<string, number>>(
      (acc, item) => {
        acc[item.category] = (acc[item.category] ?? 0) + item.amount;
        return acc;
      },
      {},
    ),
    totalExpenses: expenses,
    accrualPnl: collected - expenses,
    cashPnl: collected - expenses,
    arrearsAmount: demoArrears.reduce(
      (sum, item) => sum + item.amountOutstanding,
      0,
    ),
    arrearsCount: demoArrears.length,
    serviceChargeAssessed: demoServiceCharges.reduce(
      (sum, item) => sum + item.amount,
      0,
    ),
    activeTenancyCount: demoTenancies.filter((item) => item.status === "ACTIVE")
      .length,
    paymentCount: demoPayments.length,
  };
}

function healthGrade(score: number): HealthGrade {
  if (score >= 90) return "EXCELLENT";
  if (score >= 80) return "GOOD";
  if (score >= 70) return "WATCH";
  if (score >= 60) return "AT_RISK";
  return "CRITICAL";
}

export function propertyHealth(propertyId: string): CommandCenterProperty {
  const property =
    demoProperties.find((item) => item._id === propertyId) ?? demoProperties[0];
  if (!property) throw new Error("Demo property dataset is incomplete.");
  const units = demoUnits.filter((item) => item.propertyId === property._id);
  const rent = demoRentCharges.filter(
    (item) => item.propertyId === property._id,
  );
  const maintenance = demoMaintenance.filter(
    (item) =>
      item.propertyId === property._id &&
      !["CLOSED", "CANCELLED"].includes(item.status),
  );
  const security = demoSecurityEvents.filter(
    (item) =>
      item.propertyId === property._id &&
      !["RESOLVED", "DISMISSED"].includes(item.status),
  );
  const cameras = demoCameras.filter(
    (item) => item.propertyId === property._id,
  );
  const billed = rent.reduce((sum, item) => sum + item.totalAmount, 0);
  const collected = rent.reduce((sum, item) => sum + item.paidAmount, 0);
  const occupancy = units.length
    ? units.filter((item) => item.status === "OCCUPIED").length / units.length
    : 0;
  const collection = billed ? collected / billed : 0;
  const score = Math.round(
    occupancy * 35 +
      collection * 35 +
      Math.max(0, 20 - maintenance.length * 3) +
      Math.max(0, 10 - security.length * 3),
  );
  const financialScore = Math.round(collection * 100);
  const operationalScore = Math.max(0, 100 - maintenance.length * 10);
  const securityScore = Math.max(0, 100 - security.length * 15);
  return {
    property: {
      _id: property._id,
      name: property.name,
      code: property.code,
      propertyType: property.propertyType,
      address: { ...property.address },
    },
    health: {
      score,
      grade: healthGrade(score),
      warningCodes: security.length
        ? ["SECURITY_EVENTS_OPEN"]
        : maintenance.length
          ? ["MAINTENANCE_BACKLOG"]
          : [],
      dimensions: {
        financial: {
          score: financialScore,
          weight: 0.4,
          weightedScore: financialScore * 0.4,
          signals: [],
        },
        operational: {
          score: operationalScore,
          weight: 0.35,
          weightedScore: operationalScore * 0.35,
          signals: [],
        },
        security: {
          score: securityScore,
          weight: 0.25,
          weightedScore: securityScore * 0.25,
          signals: [],
        },
      },
    },
    metrics: {
      propertyId: property._id,
      units: units.length,
      occupiedUnits: units.filter((item) => item.status === "OCCUPIED").length,
      vacantUnits: units.filter((item) => item.status === "VACANT").length,
      reservedUnits: units.filter((item) => item.status === "RESERVED").length,
      maintenanceUnits: units.filter((item) => item.status === "MAINTENANCE")
        .length,
      occupancyRate: occupancy,
      rentBilled: billed,
      rentCollected: collected,
      cashCollected: collected,
      collectionRate: collection,
      outstandingRent: billed - collected,
      arrearsCases: demoArrears.filter(
        (item) => item.propertyId === property._id,
      ).length,
      arrearsAmount: demoArrears
        .filter((item) => item.propertyId === property._id)
        .reduce((sum, item) => sum + item.amountOutstanding, 0),
      expenses: demoExpenses
        .filter((item) => item.propertyId === property._id)
        .reduce((sum, item) => sum + item.amount, 0),
      expenseRatio: billed ? 0.14 : 0,
      maintenanceOpen: maintenance.length,
      urgentMaintenance: maintenance.filter(
        (item) => item.priority === "EMERGENCY" || item.priority === "HIGH",
      ).length,
      maintenanceSpend: demoExpenses
        .filter(
          (item) =>
            item.propertyId === property._id && item.category === "MAINTENANCE",
        )
        .reduce((sum, item) => sum + item.amount, 0),
      inspectionCoverage: 0.92,
      inventoryItems: 148,
      inventoryServiceDue: 7,
      cameras: cameras.length,
      camerasOnline: cameras.filter((item) => item.status === "ONLINE").length,
      openSecurityEvents: security.length,
      highCriticalSecurityEvents: security.filter((item) =>
        ["HIGH", "CRITICAL"].includes(item.severity),
      ).length,
      openIncidents: security.length,
      criticalIncidents: security.filter((item) => item.severity === "CRITICAL")
        .length,
      accessDenied24h: 3,
    },
    actions: maintenance.length
      ? [
          {
            priority: "HIGH",
            code: "MAINT_BACKLOG",
            title: "Clear maintenance backlog",
            reason: `${maintenance.length} operational requests need attention.`,
          },
        ]
      : [],
  };
}

export function commandCenter(): CommandCenter {
  const health = demoProperties.map((property) => propertyHealth(property._id));
  const units = demoUnits.length;
  const occupied = demoUnits.filter(
    (item) => item.status === "OCCUPIED",
  ).length;
  const billed = demoRentCharges.reduce(
    (sum, item) => sum + item.totalAmount,
    0,
  );
  const collected = demoRentCharges.reduce(
    (sum, item) => sum + item.paidAmount,
    0,
  );
  const portfolioHealthScore = Math.round(
    health.reduce((sum, item) => sum + item.health.score, 0) / health.length,
  );
  return {
    asOf: new Date().toISOString(),
    period: { from: "2026-09-01", to: "2026-09-30" },
    portfolio: {
      propertyCount: demoProperties.length,
      healthScore: portfolioHealthScore,
      grade: healthGrade(portfolioHealthScore),
      units,
      occupiedUnits: occupied,
      vacantUnits: demoUnits.filter((item) => item.status === "VACANT").length,
      rentBilled: billed,
      rentCollected: collected,
      cashCollected: collected,
      outstandingRent: billed - collected,
      expenses: demoExpenses.reduce((sum, item) => sum + item.amount, 0),
      maintenanceOpen: demoMaintenance.length,
      urgentMaintenance: demoMaintenance.filter((item) =>
        ["EMERGENCY", "HIGH"].includes(item.priority),
      ).length,
      openIncidents: demoSecurityEvents.filter(
        (item) => !["RESOLVED", "DISMISSED"].includes(item.status),
      ).length,
      criticalIncidents: 0,
      openSecurityEvents: demoSecurityEvents.filter(
        (item) => !["RESOLVED", "DISMISSED"].includes(item.status),
      ).length,
      offlineCameras: demoCameras.filter((item) => item.status !== "ONLINE")
        .length,
      accessDenied24h: 3,
      collectionRate: collected / billed,
    },
    properties: health,
    activeAlerts: [
      {
        _id: "demo-alert-1",
        organizationId: demoOrganization._id,
        propertyId: "demo-property-2",
        code: "CAMERA_DEGRADED",
        severity: "HIGH",
        status: "OPEN",
        title: "Business Park camera degraded",
        message: "Parking camera heartbeat is below normal threshold.",
        source: "SECURITY",
        metric: "cameraHeartbeat",
        observedValue: 61,
        thresholdValue: 90,
        firstDetectedAt: iso(-1),
        lastDetectedAt: iso(0),
      },
      {
        _id: "demo-alert-2",
        organizationId: demoOrganization._id,
        propertyId: "demo-property-1",
        code: "ARREARS_RISK",
        severity: "MEDIUM",
        status: "OPEN",
        title: "Tenant arrears require follow-up",
        message: `${demoArrears.length} arrears cases remain active.`,
        source: "FINANCE",
        metric: "arrearsAmount",
        observedValue: demoArrears.reduce(
          (sum, item) => sum + item.amountOutstanding,
          0,
        ),
        thresholdValue: 25000,
        firstDetectedAt: iso(-3),
        lastDetectedAt: iso(0),
      },
    ],
  };
}

export function demoUserForRole(role: string) {
  const tenant = demoUsers.find((item) => item._id === "demo-user-tenant-1");
  const match = demoUsers.find((item) => item.role === role);
  const fallback = demoUsers.find((item) => item.role === "LANDLORD");
  if (!tenant || !fallback)
    throw new Error("Demo identity dataset is incomplete.");
  return role === "TENANT" ? tenant : (match ?? fallback);
}

export function tenantWorkspaceData() {
  const tenancy = demoTenancies[0];
  const tenant = demoTenants[0];
  if (!tenancy || !tenant)
    throw new Error("Demo tenancy dataset is incomplete.");
  const unitRecord = demoUnits.find((item) => item._id === tenancy.unitId);
  const property = demoProperties.find(
    (item) => item._id === tenancy.propertyId,
  );
  const rentCharge = demoRentCharges[0];
  if (!unitRecord || !property || !rentCharge)
    throw new Error("Demo tenant workspace dataset is incomplete.");
  return {
    tenant,
    tenancy,
    unit: unitRecord,
    property,
    tenantName: tenantName(tenant._id),
    rentCharge,
    payments: demoPayments.filter((item) => item.tenantId === tenant._id),
    maintenance: demoMaintenance.filter((item) => item.tenantId === tenant._id),
    documents: demoDocuments.filter(
      (item) => item.unitId === unitRecord._id || item.visibility === "TENANT",
    ),
  };
}
