'use client';
import { IntegrationSetupForms } from '@/components/integrations/setup-forms';
import { useMemo,useState } from 'react';
import * as I from '@/components/icons';
import { Badge,EmptyState,PageTitle,SectionHeader,Stat } from '@/components/ui';
import { useOrganization } from '@/hooks/use-organization';
import { useIntegrationHealthQuery,useReconcileProviderPaymentMutation,useStorageSignedUrlMutation } from '@/hooks/queries/use-integration-queries';
import { usePaymentsQuery } from '@/hooks/queries/use-finance-queries';
import type { Payment } from '@/lib/data/resource-types';
const providers=[['mpesa','M-Pesa','Daraja payments'],['paystack','Paystack','Checkout + verified webhooks'],['email','Email','SendGrid delivery'],['sms','SMS','Twilio delivery'],['whatsapp','WhatsApp','Cloud API delivery'],['cloudinary','Cloudinary','Media storage'],['s3','S3','Object storage'],['cctv','CCTV','Generic CCTV provider'],['nvr','NVR','NVR HTTP boundary']] as const;
const tone=(ok:boolean):'green'|'red'=>ok?'green':'red'; const money=(p:Payment)=>`${p.currency} ${p.amount.toLocaleString()}`;
export default function Integrations(){
 const {activeOrganizationId}=useOrganization(); const health=useIntegrationHealthQuery(); const payments=usePaymentsQuery(activeOrganizationId); const reconcile=useReconcileProviderPaymentMutation(activeOrganizationId); const signed=useStorageSignedUrlMutation(activeOrganizationId);
 const [provider,setProvider]=useState<'CLOUDINARY'|'S3'>('S3'); const [key,setKey]=useState('property-command-center/'); const [signedUrl,setSignedUrl]=useState<string>(); const configured=health.data?.providers;
 const pending=useMemo(()=> (payments.data??[]).filter(p=>p.status==='PENDING'&&Boolean(p.provider&&p.providerTransactionId)).slice(0,8),[payments.data]); const configuredCount=configured?Object.values(configured).filter(Boolean).length:0;
 function sign(){if(!activeOrganizationId||!key.trim())return;signed.mutate({provider,key:key.trim()},{onSuccess:r=>setSignedUrl(r.url)})}
 return <>
 <PageTitle eyebrow="Control plane" title="Integrations" description="Provider health, payment reconciliation and controlled external-service boundaries." action={<button className="btn-secondary" onClick={()=>void health.refetch()}><I.RefreshCw size={15}/>Refresh health</button>}/>
 {activeOrganizationId ? <IntegrationSetupForms key={activeOrganizationId} organizationId={activeOrganizationId}/> : <p role="status">Select an organization to set up CCTV and payments.</p>}
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><Stat label="Providers configured" value={`${configuredCount}/10`} sub="Environment-backed readiness" icon={I.Workflow}/><Stat label="Pending provider payments" value={String(pending.length)} sub="Eligible for reconciliation" icon={I.CreditCard}/><Stat label="Webhook trust boundary" value="Protected" sub="Signature verification server-side" icon={I.ShieldCheck}/><Stat label="Retry execution" value="Durable" sub="Provider work can enter job queue" icon={I.RefreshCw}/></div>
 <div className="card p-5 mt-6"><SectionHeader title="Provider health" action={<span className="text-xs text-muted-foreground">Auto-refresh 30s</span>}/><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{providers.map(([id,name,desc])=>{const ok=Boolean(configured?.[id]);return <div key={id} className="rounded-xl border border-border p-4"><div className="flex items-start gap-3"><div className="w-9 h-9 rounded-lg bg-muted flex items-center justify-center"><I.CloudCog size={16}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><div className="font-medium text-sm">{name}</div><Badge tone={health.isLoading?'orange':tone(ok)}>{health.isLoading?'CHECKING':ok?'CONFIGURED':'NOT CONFIGURED'}</Badge></div><div className="text-xs text-muted-foreground mt-1">{desc}</div><div className="text-[11px] text-muted-foreground mt-2">{health.isError?'Health unavailable':'Configuration status only; credentials are never rendered.'}</div></div></div></div>})}</div></div>
 <div className="grid xl:grid-cols-[1.2fr_.8fr] gap-6 mt-6"><div className="card p-5"><SectionHeader title="Provider payment reconciliation" action={<span className="text-xs text-muted-foreground">M-Pesa / Paystack payments</span>}/>{pending.length===0?<EmptyState icon={I.CreditCard} title="No pending provider payments" description="Pending payments with provider transaction references will appear here for authoritative provider-state reconciliation."/>:<div className="space-y-2">{pending.map(p=><div key={p._id} className="rounded-xl border border-border p-3 flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-muted flex items-center justify-center"><I.CreditCard size={14}/></div><div className="min-w-0 flex-1"><div className="text-sm font-medium">{money(p)}</div><div className="text-[11px] text-muted-foreground truncate">{p.provider} · {p.providerTransactionId}</div></div><Badge tone="orange">PENDING</Badge><button className="btn-secondary text-xs" disabled={reconcile.isPending} onClick={()=>reconcile.mutate(p._id)}>Reconcile</button></div>)}</div>}</div>
 <div className="card p-5"><SectionHeader title="Secure storage boundary"/><p className="text-xs text-muted-foreground mb-4">Request a server-generated storage URL. Provider credentials and secrets remain backend-only.</p><div className="grid grid-cols-2 gap-2"><select className="input" value={provider} onChange={e=>setProvider(e.target.value as 'CLOUDINARY'|'S3')}><option value="S3">S3</option><option value="CLOUDINARY">Cloudinary</option></select><input className="input col-span-2" value={key} onChange={e=>setKey(e.target.value)} placeholder="object key"/><button className="btn-primary col-span-2" disabled={signed.isPending||!activeOrganizationId} onClick={sign}><I.LockKeyhole size={15}/>{signed.isPending?'Signing…':'Generate signed URL'}</button></div>{signedUrl&&<div className="mt-4 rounded-xl bg-muted p-3"><div className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">Signed URL</div><div className="text-xs break-all mt-1">{signedUrl}</div></div>}</div></div>
 <div className="card p-5 mt-6"><SectionHeader title="Integration operating model"/><div className="grid md:grid-cols-4 gap-3 text-xs"><div className="rounded-xl bg-muted p-4"><b>1 · Initiate</b><p className="text-muted-foreground mt-1">Provider calls originate behind authenticated server APIs.</p></div><div className="rounded-xl bg-muted p-4"><b>2 · Verify</b><p className="text-muted-foreground mt-1">M-Pesa/Paystack webhook signatures are verified before processing.</p></div><div className="rounded-xl bg-muted p-4"><b>3 · Reconcile</b><p className="text-muted-foreground mt-1">Provider state is reconciled against the authoritative finance ledger.</p></div><div className="rounded-xl bg-muted p-4"><b>4 · Observe</b><p className="text-muted-foreground mt-1">Attempts, jobs and webhook records remain durable backend operational records.</p></div></div></div>
 <div className="mt-4 text-[11px] text-muted-foreground">Phase 19 contract note: the backend exposes webhook ingestion and integration health, but no read endpoints for raw WebhookEvent or IntegrationAttempt records. This UI therefore does not fabricate webhook tables or retry history.</div>
 </>;
}
