import type { Request, Response } from 'express';
import { apiResponse } from '../../core/response/apiResponse.js'; import { requiredParam } from '../../core/http/params.js'; import { AuthorizationService } from '../../core/authorization/authorization.service.js';
import * as s from './maintenance.schemas.js'; import { MaintenanceService } from './maintenance.service.js';
export async function list(req:Request,res:Response):Promise<void>{const {organizationId}=s.organizationParamsSchema.parse({organizationId:requiredParam(req.params.organizationId,'organizationId')});AuthorizationService.assertPermission(req.auth!,'maintenance.view',organizationId);res.json(apiResponse(await MaintenanceService.list(req.auth!,organizationId)));}
export async function get(req:Request,res:Response):Promise<void>{const id=requiredParam(req.params.maintenanceId,'maintenanceId');res.json(apiResponse(await MaintenanceService.get(req.auth!,id)));}
export async function create(req:Request,res:Response):Promise<void>{const org=requiredParam(req.params.organizationId,'organizationId');res.status(201).json(apiResponse(await MaintenanceService.create(req.auth!,org,s.createMaintenanceSchema.parse(req.body))));}
export async function triage(req:Request,res:Response):Promise<void>{res.json(apiResponse(await MaintenanceService.triage(req.auth!,requiredParam(req.params.maintenanceId,'maintenanceId'),s.triageMaintenanceSchema.parse(req.body))));}
export async function assign(req:Request,res:Response):Promise<void>{res.json(apiResponse(await MaintenanceService.assign(req.auth!,requiredParam(req.params.maintenanceId,'maintenanceId'),s.assignMaintenanceSchema.parse(req.body))));}
export async function quote(req:Request,res:Response):Promise<void>{res.json(apiResponse(await MaintenanceService.quote(req.auth!,requiredParam(req.params.maintenanceId,'maintenanceId'),s.quoteMaintenanceSchema.parse(req.body))));}
export async function approve(req:Request,res:Response):Promise<void>{res.json(apiResponse(await MaintenanceService.approve(req.auth!,requiredParam(req.params.maintenanceId,'maintenanceId'),s.approveMaintenanceSchema.parse(req.body))));}
export async function progress(req:Request,res:Response):Promise<void>{res.json(apiResponse(await MaintenanceService.progress(req.auth!,requiredParam(req.params.maintenanceId,'maintenanceId'),s.progressMaintenanceSchema.parse(req.body))));}
export async function verify(req:Request,res:Response):Promise<void>{res.json(apiResponse(await MaintenanceService.verify(req.auth!,requiredParam(req.params.maintenanceId,'maintenanceId'),s.verifyMaintenanceSchema.parse(req.body))));}
export async function close(req:Request,res:Response):Promise<void>{res.json(apiResponse(await MaintenanceService.close(req.auth!,requiredParam(req.params.maintenanceId,'maintenanceId'))));}
export async function addEvidence(req:Request,res:Response):Promise<void>{const files=(req.files as Express.Multer.File[]|undefined)??[];res.status(201).json(apiResponse(await MaintenanceService.addEvidence(req.auth!,requiredParam(req.params.maintenanceId,'maintenanceId'),files)));}
export async function getPolicy(req:Request,res:Response):Promise<void>{const org=requiredParam(req.params.organizationId,'organizationId');res.json(apiResponse(await MaintenanceService.getPolicy(req.auth!,org)));}
export async function setPolicy(req:Request,res:Response):Promise<void>{const org=requiredParam(req.params.organizationId,'organizationId');res.json(apiResponse(await MaintenanceService.setPolicy(req.auth!,org,s.policySchema.parse(req.body))));}
