'use client';
import { useState } from 'react';
import type { Property } from '@/lib/data/resource-types';
import { useCreatePropertyMutation, useUpdatePropertyMutation } from '@/hooks/queries/use-property-queries';

const types: Property['propertyType'][] = ['APARTMENT','RESIDENTIAL_ESTATE','COMMERCIAL','MIXED_USE','OFFICE','RETAIL','WAREHOUSE','OTHER'];

export function PropertyForm({ organizationId, property, onDone, onCancel }: { organizationId: string; property?: Property; onDone: () => void; onCancel: () => void }) {
  const create = useCreatePropertyMutation(organizationId); const update = useUpdatePropertyMutation(organizationId, property?._id ?? '');
  const [name,setName]=useState(property?.name ?? ''); const [code,setCode]=useState(property?.code ?? ''); const [propertyType,setPropertyType]=useState<Property['propertyType']>(property?.propertyType ?? 'APARTMENT'); const [status,setStatus]=useState<Property['status']>(property?.status ?? 'ACTIVE'); const [city,setCity]=useState(property?.address.city ?? ''); const [addressLine1,setAddressLine1]=useState(property?.address.addressLine1 ?? ''); const [country,setCountry]=useState(property?.address.country ?? 'Kenya');
  const pending=create.isPending||update.isPending;
  async function submit(e:React.FormEvent){e.preventDefault(); if(pending)return; const input={name:name.trim(),code:code.trim(),propertyType,address:{addressLine1:addressLine1.trim(),city:city.trim(),country:country.trim()},...(property?{status}: {})}; try { if(property) await update.mutateAsync(input); else await create.mutateAsync(input); onDone(); } catch {} }
  return <form onSubmit={submit} className="space-y-4"><p className="text-sm text-muted-foreground">Create the property first, then add its buildings, floors and units.</p>{(create.error || update.error) && <p role="alert" className="text-sm text-[var(--danger-text)]">{(create.error || update.error)?.message}</p>}<div className="grid sm:grid-cols-2 gap-4"><Field label="Property name"><input required maxLength={160} value={name} onChange={e=>setName(e.target.value)} /></Field><Field label="Property code"><input required maxLength={50} value={code} onChange={e=>setCode(e.target.value)} /></Field></div><div className="grid sm:grid-cols-2 gap-4"><Field label="Property type"><select value={propertyType} onChange={e=>setPropertyType(e.target.value as Property['propertyType'])}>{types.map(t=><option key={t}>{t}</option>)}</select></Field>{property&&<Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value as Property['status'])}><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></Field>}</div><div className="grid sm:grid-cols-2 gap-4"><Field label="Address"><input required maxLength={200} value={addressLine1} onChange={e=>setAddressLine1(e.target.value)} /></Field><Field label="City"><input required value={city} onChange={e=>setCity(e.target.value)} /></Field></div><div className="grid sm:grid-cols-2 gap-4"><Field label="Country"><input required value={country} onChange={e=>setCountry(e.target.value)} /></Field></div><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onCancel} className="btn-secondary">Cancel</button><button disabled={pending} className="btn-primary">{pending?'Saving…':property?'Save changes':'Create property'}</button></div></form>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="text-xs font-medium text-muted-foreground">{label}</span><div className="mt-1">{children}</div></label>}
