import * as demo from './sales-demo.controller.js';
import { Router } from 'express';
import { requireAuth } from '../../middleware/auth.middleware.js';
import { asyncHandler } from '../../core/http/asyncHandler.js';
import * as controller from './sales.controller.js';

export const salesRouter = Router();
salesRouter.post('/demo-requests', asyncHandler(controller.requestDemo));
salesRouter.use(requireAuth);
salesRouter.use((_req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
salesRouter.get('/demos/catalog',asyncHandler(demo.catalog));
salesRouter.get('/demos',asyncHandler(demo.list));
salesRouter.post('/demos',asyncHandler(demo.prepare));
salesRouter.get('/demos/:id',asyncHandler(demo.view));
salesRouter.post('/demos/:id/commands',asyncHandler(demo.command));
salesRouter.post('/demos/:id/pilot',asyncHandler(demo.startPilot));
salesRouter.post('/organizations/:organizationId/pilot/insight',asyncHandler(demo.pilotInsight));
salesRouter.get('/organizations/:organizationId/pilot',asyncHandler(demo.pilotProgress));
salesRouter.post('/organizations/:organizationId/pilot/import/preview',asyncHandler(demo.importPreview));
salesRouter.post('/organizations/:organizationId/pilot/import/confirm',asyncHandler(demo.importConfirm));
salesRouter.post('/organizations/:organizationId/property-onboarding-requests', asyncHandler(controller.requestPropertyOnboarding));