'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { tenantClient, type CreateTenantInput, type UpdateTenantInput } from '../../lib/data/tenants';
import { tenancyClient, type CreateTenancyInput, type UpdateTenancyInput } from '../../lib/data/tenancies';
import { queryKeys } from '../../lib/data/query-keys';

export function useTenantsQuery(organizationId: string | null) { return useQuery({ queryKey: organizationId ? queryKeys.tenants.list(organizationId) : ['tenants', 'disabled'], queryFn: () => tenantClient.list(organizationId as string), enabled: Boolean(organizationId) }); }
export function useTenantQuery(organizationId: string | null, tenantId: string | null) { return useQuery({ queryKey: organizationId && tenantId ? queryKeys.tenants.detail(organizationId, tenantId) : ['tenant', 'disabled'], queryFn: () => tenantClient.get(tenantId as string), enabled: Boolean(organizationId && tenantId) }); }
export function useCreateTenantMutation(organizationId: string | null) { const qc=useQueryClient(); return useMutation({ mutationFn:(input:CreateTenantInput)=>tenantClient.create(organizationId as string,input), onSuccess:()=>{if(organizationId) void qc.invalidateQueries({queryKey:queryKeys.tenants.all(organizationId)});}}); }
export function useUpdateTenantMutation(organizationId: string | null, tenantId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(input:UpdateTenantInput)=>tenantClient.update(tenantId,input), onSuccess:()=>{if(organizationId) void qc.invalidateQueries({queryKey:queryKeys.tenants.all(organizationId)});}}); }

export function useTenanciesQuery(organizationId: string | null) { return useQuery({ queryKey: organizationId ? queryKeys.tenancies.list(organizationId) : ['tenancies','disabled'], queryFn:()=>tenancyClient.list(organizationId as string), enabled:Boolean(organizationId)}); }
export function useTenancyQuery(organizationId: string | null, tenancyId: string | null) { return useQuery({ queryKey:organizationId&&tenancyId?queryKeys.tenancies.detail(organizationId,tenancyId):['tenancy','disabled'], queryFn:()=>tenancyClient.get(tenancyId as string), enabled:Boolean(organizationId&&tenancyId)}); }
export function useCreateTenancyMutation(organizationId:string|null){const qc=useQueryClient();return useMutation({mutationFn:(input:CreateTenancyInput)=>tenancyClient.create(organizationId as string,input),onSuccess:()=>{if(organizationId){void qc.invalidateQueries({queryKey:queryKeys.tenancies.all(organizationId)});void qc.invalidateQueries({queryKey:queryKeys.units.all(organizationId)});}}});}
export function useUpdateTenancyMutation(organizationId:string|null,tenancyId:string){const qc=useQueryClient();return useMutation({mutationFn:(input:UpdateTenancyInput)=>tenancyClient.update(tenancyId,input),onSuccess:()=>{if(organizationId)void qc.invalidateQueries({queryKey:queryKeys.tenancies.all(organizationId)});}});}
export function useActivateTenancyMutation(organizationId:string|null){const qc=useQueryClient();return useMutation({mutationFn:(id:string)=>tenancyClient.activate(id),onSuccess:()=>{if(organizationId){void qc.invalidateQueries({queryKey:queryKeys.tenancies.all(organizationId)});void qc.invalidateQueries({queryKey:queryKeys.units.all(organizationId)});void qc.invalidateQueries({queryKey:queryKeys.tenants.all(organizationId)});}}});}
export function useTerminateTenancyMutation(organizationId:string|null){const qc=useQueryClient();return useMutation({mutationFn:(id:string)=>tenancyClient.terminate(id),onSuccess:()=>{if(organizationId){void qc.invalidateQueries({queryKey:queryKeys.tenancies.all(organizationId)});void qc.invalidateQueries({queryKey:queryKeys.units.all(organizationId)});void qc.invalidateQueries({queryKey:queryKeys.tenants.all(organizationId)});}}});}
