'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { financeClient, type AllocationInput, type ArrearsUpdateInput, type ExpenseInput, type FinancialPeriodInput, type GenerateRentInput, type PaymentDestinationInput, type PaymentInput, type RentChargeInput, type ServiceChargeInput } from '../../lib/data/finance';
import { queryKeys } from '../../lib/data/query-keys';

export function useRentChargesQuery(org:string|null){return useQuery({queryKey:org?queryKeys.finance.rent(org):['finance','rent','disabled'],queryFn:()=>financeClient.rent.list(org as string),enabled:Boolean(org)});}
export function useRentChargeQuery(org:string|null,id:string|null){return useQuery({queryKey:org&&id?queryKeys.finance.rentDetail(org,id):['finance','rent-detail','disabled'],queryFn:()=>financeClient.rent.get(id as string),enabled:Boolean(org&&id)});}
export function usePaymentsQuery(org:string|null){return useQuery({queryKey:org?queryKeys.finance.payments(org):['finance','payments','disabled'],queryFn:()=>financeClient.payments.list(org as string),enabled:Boolean(org)});}
export function usePaymentRefundsQuery(org:string|null,enabled=true){return useQuery({queryKey:org?queryKeys.finance.refunds(org):['finance','refunds','disabled'],queryFn:()=>financeClient.refunds.list(org as string),enabled:Boolean(org&&enabled)});}
export function useRequestRefundMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(v:{paymentId:string;reason:string})=>financeClient.refunds.request(v.paymentId,v.reason),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useReconcileRefundMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(paymentId:string)=>financeClient.refunds.reconcile(paymentId),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useApplyRefundLedgerMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(paymentId:string)=>financeClient.refunds.applyLedger(paymentId),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function usePaymentDestinationsQuery(org:string|null,enabled=true){return useQuery({queryKey:org?queryKeys.finance.paymentDestinations(org):['finance','payment-destinations','disabled'],queryFn:()=>financeClient.paymentDestinations.list(org as string),enabled:Boolean(org&&enabled)});}
export function useExpensesQuery(org:string|null){return useQuery({queryKey:org?queryKeys.finance.expenses(org):['finance','expenses','disabled'],queryFn:()=>financeClient.expenses.list(org as string),enabled:Boolean(org)});}
export function useServiceChargesQuery(org:string|null){return useQuery({queryKey:org?queryKeys.finance.serviceCharges(org):['finance','service-charges','disabled'],queryFn:()=>financeClient.serviceCharges.list(org as string),enabled:Boolean(org)});}
export function useArrearsQuery(org:string|null){return useQuery({queryKey:org?queryKeys.finance.arrears(org):['finance','arrears','disabled'],queryFn:()=>financeClient.arrears.list(org as string),enabled:Boolean(org)});}
export function useFinancialReportQuery(org:string|null,params:{from:string;to:string;propertyId?:string}|null){const keyParams=params?new URLSearchParams(params as Record<string,string>).toString():'';return useQuery({queryKey:org?queryKeys.finance.report(org,keyParams):['finance','report','disabled'],queryFn:()=>financeClient.report(org as string,params as {from:string;to:string;propertyId?:string}),enabled:Boolean(org&&params?.from&&params?.to)});}
export function useFinancialPeriodsQuery(org:string|null){return useQuery({queryKey:org?queryKeys.finance.periods(org):['finance','periods','disabled'],queryFn:()=>financeClient.periods.list(org as string),enabled:Boolean(org)});}
function invalidate(qc:ReturnType<typeof useQueryClient>,org:string){void qc.invalidateQueries({queryKey:queryKeys.finance.all(org)});}
export function useCreateRentMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(input:RentChargeInput)=>financeClient.rent.create(org as string,input),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useGenerateRentMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(input:GenerateRentInput)=>financeClient.rent.generate(org as string,input),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useCreatePaymentMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(input:PaymentInput)=>financeClient.payments.create(org as string,input),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useCreatePaymentDestinationMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(input:PaymentDestinationInput)=>financeClient.paymentDestinations.create(org as string,input),onSuccess:()=>{if(org)void qc.invalidateQueries({queryKey:queryKeys.finance.paymentDestinations(org)});}});}
export function useDisablePaymentDestinationMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(id:string)=>financeClient.paymentDestinations.disable(id),onSuccess:()=>{if(org)void qc.invalidateQueries({queryKey:queryKeys.finance.paymentDestinations(org)});}});}
export function useConfirmPaymentMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(v:{id:string;allocation?:AllocationInput})=>financeClient.payments.confirm(v.id,v.allocation),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useReversePaymentMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(id:string)=>financeClient.payments.reverse(id),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useCreateExpenseMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(input:ExpenseInput)=>financeClient.expenses.create(org as string,input),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useExpenseActionMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(v:{id:string;action:'approve'|'pay'|'reject';notes?:string})=>financeClient.expenses[v.action](v.id,v.notes),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useCreateServiceChargeMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(input:ServiceChargeInput)=>financeClient.serviceCharges.create(org as string,input),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useUpdateArrearsMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(v:{id:string;input:ArrearsUpdateInput})=>financeClient.arrears.update(v.id,v.input),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useCreateFinancialPeriodMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(input:FinancialPeriodInput)=>financeClient.periods.create(org as string,input),onSuccess:()=>{if(org)invalidate(qc,org);}});}
export function useCloseFinancialPeriodMutation(org:string|null){const qc=useQueryClient();return useMutation({mutationFn:(id:string)=>financeClient.periods.close(id),onSuccess:()=>{if(org)invalidate(qc,org);}});}
