'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { modelServingClient, type ApprovalDecisionInput, type ApprovalRequestInput, type DeploymentInput, type IncidentQuery, type ModelServingQuery, type MonitorInput, type PolicyInput, type RollbackInput, type TrainingInput } from '../../lib/data/model-serving';
import { queryKeys } from '../../lib/data/query-keys';

const key = (v: unknown) => JSON.stringify(v ?? {});
const invalidate = (qc: ReturnType<typeof useQueryClient>, org: string) => { void qc.invalidateQueries({ queryKey: queryKeys.modelServing.all(org) }); void qc.invalidateQueries({ queryKey: queryKeys.predictiveLearning.all(org) }); };

export function useModelServingPolicyQuery(org: string | null) { return useQuery({ queryKey: org ? queryKeys.modelServing.policy(org) : ['model-serving-policy', 'disabled'], queryFn: () => modelServingClient.policy(org as string), enabled: Boolean(org) }); }
export function useModelServingDeploymentsQuery(org: string | null, params: ModelServingQuery = {}) { return useQuery({ queryKey: org ? queryKeys.modelServing.deployments(org, key(params)) : ['model-serving-deployments', 'disabled'], queryFn: () => modelServingClient.deployments(org as string, params), enabled: Boolean(org) }); }
export function useModelMonitoringQuery(org: string | null, params: ModelServingQuery = {}) { return useQuery({ queryKey: org ? queryKeys.modelServing.monitoring(org, key(params)) : ['model-serving-monitoring', 'disabled'], queryFn: () => modelServingClient.monitoring(org as string, params), enabled: Boolean(org), refetchInterval: 30000 }); }
export function useModelApprovalsQuery(org: string | null, params: ModelServingQuery = {}) { return useQuery({ queryKey: org ? queryKeys.modelServing.approvals(org, key(params)) : ['model-serving-approvals', 'disabled'], queryFn: () => modelServingClient.approvals(org as string, params), enabled: Boolean(org), refetchInterval: 30000 }); }
export function useModelIncidentsQuery(org: string | null, params: IncidentQuery = {}) { return useQuery({ queryKey: org ? queryKeys.modelServing.incidents(org, key(params)) : ['model-serving-incidents', 'disabled'], queryFn: () => modelServingClient.incidents(org as string, params), enabled: Boolean(org), refetchInterval: 30000 }); }

export function useUpdateModelServingPolicyMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: PolicyInput) => modelServingClient.updatePolicy(org as string, input), onSuccess: () => org && invalidate(qc, org) }); }
export function useDeployModelMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: DeploymentInput) => modelServingClient.deploy(org as string, input), onSuccess: () => org && invalidate(qc, org) }); }
export function useRollbackModelMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: RollbackInput) => modelServingClient.rollback(org as string, input), onSuccess: () => org && invalidate(qc, org) }); }
export function useMonitorModelsMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: MonitorInput) => modelServingClient.monitor(org as string, input), onSuccess: () => org && invalidate(qc, org) }); }
export function useRequestModelApprovalMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: ApprovalRequestInput) => modelServingClient.requestApproval(org as string, input), onSuccess: () => org && invalidate(qc, org) }); }
export function useDecideModelApprovalMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ approvalId, input }: { approvalId: string; input: ApprovalDecisionInput }) => modelServingClient.decideApproval(approvalId, input), onSuccess: () => org && invalidate(qc, org) }); }
export function useUpdateModelIncidentMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ incidentId, input }: { incidentId: string; input: { status: 'ACKNOWLEDGED' | 'RESOLVED' | 'DISMISSED'; reason?: string } }) => modelServingClient.updateIncident(incidentId, input), onSuccess: () => org && invalidate(qc, org) }); }
export function useTrainPredictiveModelMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: TrainingInput) => modelServingClient.train(org as string, input), onSuccess: () => org && invalidate(qc, org) }); }
export function usePromotePredictiveModelMutation(org: string | null) { const qc = useQueryClient(); return useMutation({ mutationFn: (modelId: string) => modelServingClient.promote(org as string, modelId), onSuccess: () => org && invalidate(qc, org) }); }
