import { Types } from 'mongoose';
import { Property } from '../../database/models/Property.js';
import { Unit } from '../../database/models/Unit.js';
import { Tenancy } from '../../database/models/Tenancy.js';
import { RentCharge } from '../../database/models/RentCharge.js';
import { ArrearsCase } from '../../database/models/ArrearsCase.js';
import { PropertyHealthSnapshot } from '../../database/models/PropertyHealthSnapshot.js';
import { OrganizationMembership } from '../../database/models/OrganizationMembership.js';
import { Role } from '../../database/models/Role.js';
import { Job } from '../../database/models/Job.js';
import { LandlordAction } from '../../database/models/LandlordAction.js';
import { DecisionAutomationPolicy } from '../../database/models/DecisionAutomationPolicy.js';
import { DecisionAutomationRun } from '../../database/models/DecisionAutomationRun.js';
import { TenantArrearsRisk } from '../../database/models/TenantArrearsRisk.js';
import { VacancyForecast } from '../../database/models/VacancyForecast.js';
import { RevenueRiskForecast } from '../../database/models/RevenueRiskForecast.js';
import { PredictiveObservation } from '../../database/models/PredictiveObservation.js';
import { AuthorizationService } from '../../core/authorization/authorization.service.js';
import { ResourceScopeService } from '../../core/authorization/resource-scope.service.js';
import { AppError } from '../../core/errors/AppError.js';
import { AuditService } from '../audit/audit.service.js';
import { NotificationService } from '../notifications/notification.service.js';
import { CommandCenterService } from '../command-center/command-center.service.js';
import type { AuthenticatedUser } from '../../core/types/auth.js';
import type { z } from 'zod';
import type { actionQuerySchema, periodSchema, policySchema, tenantRiskQuerySchema, vacancyQuerySchema } from './decision-automation.schemas.js';

type PeriodInput=z.infer<typeof periodSchema>;
type PolicyInput=z.infer<typeof policySchema>;
type ActionQuery=z.infer<typeof actionQuerySchema>;
type TenantRiskQuery=z.infer<typeof tenantRiskQuerySchema>;
type VacancyQuery=z.infer<typeof vacancyQuerySchema>;

type Priority='CRITICAL'|'HIGH'|'MEDIUM'|'LOW';
type CandidateSource='FINANCE'|'OCCUPANCY'|'MAINTENANCE'|'SECURITY'|'COMPLIANCE'|'ANOMALY'|'RISK'|'INTELLIGENCE';
const DAY=86_400_000;
const MODEL_VERSION='RULE_BASED_PREDICTIVE_V1';
const priorityRank:Record<Priority,number>={LOW:1,MEDIUM:2,HIGH:3,CRITICAL:4};
const priorityFromRank=(rank:number):Priority=>rank>=4?'CRITICAL':rank>=3?'HIGH':rank>=2?'MEDIUM':'LOW';

type HealthSnapshotLike={metrics:Record<string,unknown>;score:number;asOf:Date};
type RiskLike={tenantId:Types.ObjectId;grade:'LOW'|'MODERATE'|'HIGH'|'CRITICAL';outstandingAmount:number;probability:number;confidence:number;score:number};
type VacancyLike={unitId:Types.ObjectId;predictedDaysToLease:number;revenueAtRisk:number;currentVacancyDays:number;confidence:number};
type RevenueForecastLike={horizonDays:number;baselineMonthlyRevenue:number;revenueAtRisk:number;confidence:number;drivers:Array<{code?:string|null;label?:string|null;impact?:number|null}>};
type UnitLike={_id:Types.ObjectId;buildingId:Types.ObjectId;floorId:Types.ObjectId;monthlyRent:number;status:string;updatedAt:Date};
type TenancyLike={_id:Types.ObjectId;unitId:Types.ObjectId;tenantId:Types.ObjectId;propertyId:Types.ObjectId;buildingId:Types.ObjectId;floorId:Types.ObjectId;status:string;startDate:Date;endDate?:Date|null;movedOutAt?:Date|null;monthlyRent:number;serviceCharge:number};
const round=(n:number)=>Math.round(n*100)/100;
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const oid=(v:string)=>{if(!Types.ObjectId.isValid(v))throw new AppError(400,'INVALID_ID','Invalid ObjectId');return new Types.ObjectId(v);};

function period(input:PeriodInput){const to=input.to??new Date();const from=input.from??new Date(to.getTime()-30*DAY);if(from>to)throw new AppError(400,'INVALID_PERIOD','The period start must be before the period end');return {from,to};}
function median(values:number[]){if(!values.length)return 0;const a=[...values].sort((x,y)=>x-y);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function slope(points:Array<{time:number;value:number}>){if(points.length<2)return 0;const x0=points[0]!.time;const xs=points.map(p=>(p.time-x0)/DAY);const ys=points.map(p=>p.value);const xm=xs.reduce((a,b)=>a+b,0)/xs.length;const ym=ys.reduce((a,b)=>a+b,0)/ys.length;const den=xs.reduce((s,x)=>s+(x-xm)**2,0);return den===0?0:xs.reduce((s,x,i)=>s+(x-xm)*(ys[i]!-ym),0)/den;}

export class DecisionAutomationService {
  static async getPolicy(auth:AuthenticatedUser,organizationId:string){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'decision-automation.view',org);return DecisionAutomationPolicy.findOne({organizationId:org}).lean();}

  static async updatePolicy(auth:AuthenticatedUser,organizationId:string,data:PolicyInput){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'decision-automation.policy.manage',org);const policy=await DecisionAutomationPolicy.findOneAndUpdate({organizationId:org},{$set:{...data,updatedBy:auth.userId}},{new:true,upsert:true,setDefaultsOnInsert:true});await AuditService.record({organizationId:org,actorUserId:auth.userId,action:'decision-automation.policy.updated',resourceType:'DecisionAutomationPolicy',resourceId:policy._id,after:policy.toObject()});if(policy.enabled)await this.schedule(org,policy.evaluationIntervalMinutes);return policy;}

  static async bootstrap(auth:AuthenticatedUser,organizationId:string){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'decision-automation.policy.manage',org);let policy=await DecisionAutomationPolicy.findOne({organizationId:org});if(!policy)policy=await DecisionAutomationPolicy.create({organizationId:org,updatedBy:auth.userId});if(policy.enabled)await this.schedule(org,policy.evaluationIntervalMinutes);return {policy,scheduled:true};}

  private static async schedule(organizationId:Types.ObjectId,intervalMinutes:number){const next=new Date(Date.now()+intervalMinutes*60_000);const bucket=Math.floor(next.getTime()/(intervalMinutes*60_000));const dedupeKey=`decision-automation:${organizationId.toString()}:${bucket}`;await Job.findOneAndUpdate({dedupeKey},{$setOnInsert:{organizationId,type:'decision-automation.evaluate',payload:{organizationId:String(organizationId),trigger:'SCHEDULED'},status:'QUEUED',priority:10,availableAt:next,maxAttempts:5,dedupeKey}},{upsert:true,new:true});await DecisionAutomationPolicy.updateOne({organizationId},{$set:{lastScheduledAt:next}});}

  private static async visibleProperties(auth:AuthenticatedUser,organizationId:Types.ObjectId,propertyId?:string){AuthorizationService.assertPermission(auth,'decision-automation.view',organizationId);const ids=await ResourceScopeService.scopedPropertyIds(auth,organizationId);const filter:Record<string,unknown>={organizationId,status:'ACTIVE'};if(ids)filter._id={$in:ids};if(propertyId){const p=oid(propertyId);if(ids&&!ids.some(x=>String(x)===String(p)))throw new AppError(403,'FORBIDDEN','You are not authorized to view this property');filter._id=p;}return Property.find(filter).sort({name:1}).lean();}

  static async evaluate(auth:AuthenticatedUser,organizationId:string,input:PeriodInput){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'decision-automation.evaluate',org);const properties=await this.visibleProperties(auth,org,input.propertyId);const {from,to}=period(input);return this.run(org,from,to,'MANUAL',auth.userId,properties.map(p=>p._id));}

  static async evaluateSystem(organizationId:Types.ObjectId,input?:{from?:Date;to?:Date;trigger?:'SCHEDULED'|'JOB'}){const to=input?.to??new Date();const from=input?.from??new Date(to.getTime()-30*DAY);const policy=await DecisionAutomationPolicy.findOne({organizationId}).lean();if(policy?.enabled===false)return {skipped:true,reason:'DISABLED'};return this.run(organizationId,from,to,input?.trigger??'JOB',undefined);}

  private static async run(organizationId:Types.ObjectId,from:Date,to:Date,trigger:'MANUAL'|'SCHEDULED'|'JOB',actorUserId?:Types.ObjectId,propertyIds?:Types.ObjectId[]){
    const run=await DecisionAutomationRun.create({organizationId,startedAt:new Date(),status:'RUNNING',trigger});
    try{
      await CommandCenterService.evaluateOrganization(organizationId,from,to,actorUserId,propertyIds);
      const properties=await Property.find({organizationId,status:'ACTIVE',...(propertyIds?{_id:{$in:propertyIds}}:{})}).sort({name:1}).lean();
      let actionsCreated=0,actionsEscalated=0,notificationsQueued=0,tenantRisksUpdated=0,vacancyForecastsUpdated=0,revenueForecastsUpdated=0;
      for(const property of properties){
        const result=await this.analyzeProperty(organizationId,property._id,from,to,actorUserId);
        actionsCreated+=result.actionsCreated;actionsEscalated+=result.actionsEscalated;notificationsQueued+=result.notificationsQueued;tenantRisksUpdated+=result.tenantRisksUpdated;vacancyForecastsUpdated+=result.vacancyForecastsUpdated;revenueForecastsUpdated++;
      }
      run.status='SUCCEEDED';run.completedAt=new Date();run.evaluatedProperties=properties.length;run.actionsCreated=actionsCreated;run.actionsEscalated=actionsEscalated;run.notificationsQueued=notificationsQueued;run.tenantRisksUpdated=tenantRisksUpdated;run.vacancyForecastsUpdated=vacancyForecastsUpdated;run.revenueForecastsUpdated=revenueForecastsUpdated;await run.save();
      await DecisionAutomationPolicy.updateOne({organizationId},{$set:{lastEvaluatedAt:new Date()}});
      const policy=await DecisionAutomationPolicy.findOne({organizationId}).lean();if(policy?.enabled)await this.schedule(organizationId,policy.evaluationIntervalMinutes);
      if(actorUserId)await AuditService.publish({organizationId,actorUserId,name:'decision-automation.completed',aggregateType:'DecisionAutomationRun',aggregateId:run._id,payload:{evaluatedProperties:properties.length,actionsCreated,actionsEscalated,notificationsQueued}});
      return {runId:String(run._id),evaluatedProperties:properties.length,actionsCreated,actionsEscalated,notificationsQueued,tenantRisksUpdated,vacancyForecastsUpdated,revenueForecastsUpdated};
    }catch(error){run.status='FAILED';run.completedAt=new Date();run.error=error instanceof Error?error.message:'Unknown automation failure';await run.save();throw error;}
  }

  private static async analyzeProperty(organizationId:Types.ObjectId,propertyId:Types.ObjectId,from:Date,to:Date,actorUserId?:Types.ObjectId){
    const latestRaw=await PropertyHealthSnapshot.findOne({organizationId,propertyId}).sort({asOf:-1}).lean();if(!latestRaw)return {actionsCreated:0,actionsEscalated:0,notificationsQueued:0,tenantRisksUpdated:0,vacancyForecastsUpdated:0};
    const latest=latestRaw as unknown as HealthSnapshotLike;
    const history=await PropertyHealthSnapshot.find({organizationId,propertyId}).sort({asOf:-1}).limit(12).lean();
    const scoreVelocity=slope(history.slice().reverse().map(h=>({time:h.asOf.getTime(),value:h.score})));
    const collectionVelocity=slope(history.slice().reverse().map(h=>({time:h.asOf.getTime(),value:Number((h.metrics as Record<string,unknown>).collectionRate??0)})));
    const occupancyVelocity=slope(history.slice().reverse().map(h=>({time:h.asOf.getTime(),value:Number((h.metrics as Record<string,unknown>).occupancyRate??0)})));
    const units=(await Unit.find({organizationId,propertyId,status:{$ne:'INACTIVE'}}).lean()) as unknown as UnitLike[];
    const vacancies=await this.forecastVacancies(organizationId,propertyId,units,to,actorUserId);
    const tenantRisks=await this.calculateTenantRisks(organizationId,propertyId,to,actorUserId);
    const revenue=await this.forecastRevenue(organizationId,propertyId,latest,scoreVelocity,tenantRisks,vacancies,30,to,actorUserId);
    const candidates=this.buildCandidates(propertyId,latest,scoreVelocity,collectionVelocity,occupancyVelocity,revenue,tenantRisks,vacancies);
    const policy=await DecisionAutomationPolicy.findOne({organizationId}).lean();
    let actionsCreated=0,actionsEscalated=0,notificationsQueued=0;
    for(const candidate of candidates){const outcome=await this.upsertAction(organizationId,candidate,policy?.escalationAfterMinutes??120);if(outcome.created)actionsCreated++;if(outcome.escalated)actionsEscalated++;if(outcome.notify)notificationsQueued+=await this.notifyLandlords(organizationId,outcome.action,policy?.maxNotificationsPerRun??20);if(actorUserId&&outcome.created)await AuditService.record({organizationId,actorUserId,action:'decision-automation.action.created',resourceType:'LandlordAction',resourceId:outcome.action._id,propertyId,after:outcome.action.toObject()});}
    return {actionsCreated,actionsEscalated,notificationsQueued,tenantRisksUpdated:tenantRisks.length,vacancyForecastsUpdated:vacancies.length};
  }

  private static buildCandidates(propertyId:Types.ObjectId,latest:HealthSnapshotLike,scoreVelocity:number,collectionVelocity:number,occupancyVelocity:number,revenue:RevenueForecastLike,tenantRisks:RiskLike[],vacancies:VacancyLike[]){
    const out:Array<{code:string;title:string;reason:string;recommendedAction:string;priority:Priority;source:CandidateSource;propertyId:Types.ObjectId;targetResourceType:string;targetResourceId:Types.ObjectId;urgencyScore:number;financialImpact:number;moneyAtRisk:number;confidence:number;metadata:Record<string,unknown>}>=[];
    const metrics=latest.metrics;
    const metricNumber=(key:string, fallback=0)=>Number(metrics[key]??fallback);
    if(metricNumber('criticalIncidents')>0)out.push({code:'SECURITY_ESCALATION',title:'Escalate critical security exposure',reason:`${metricNumber('criticalIncidents')} critical incident(s) remain open.`,recommendedAction:'Review the incident, assign an accountable owner, and confirm containment.',priority:'CRITICAL',source:'SECURITY',propertyId,targetResourceType:'Property',targetResourceId:propertyId,urgencyScore:100,financialImpact:0,moneyAtRisk:0,confidence:.98,metadata:{criticalIncidents:metricNumber('criticalIncidents')}});
    if(tenantRisks.some(r=>r.grade==='CRITICAL')){const r=tenantRisks.filter(x=>x.grade==='CRITICAL').sort((a,b)=>b.outstandingAmount-a.outstandingAmount)[0]!;out.push({code:'TENANT_ARREARS_ESCALATION',title:'Escalate high-risk tenant arrears',reason:`A tenant has a ${r.probability*100}% modeled arrears-risk probability with ${r.outstandingAmount} outstanding.`,recommendedAction:'Contact the tenant, document the collection plan, and escalate according to arrears policy.',priority:'CRITICAL',source:'RISK',propertyId,targetResourceType:'Tenant',targetResourceId:r.tenantId,urgencyScore:95,financialImpact:r.outstandingAmount,moneyAtRisk:r.outstandingAmount,confidence:r.confidence,metadata:{riskScore:r.score}});}
    if(vacancies.some(v=>v.predictedDaysToLease>=60)){const v=vacancies.sort((a,b)=>b.revenueAtRisk-a.revenueAtRisk)[0]!;out.push({code:'VACANCY_ESCALATION',title:'Escalate prolonged vacancy',reason:`Unit vacancy is forecast to persist for about ${Math.round(v.predictedDaysToLease)} days.`,recommendedAction:'Launch or intensify the leasing campaign and review pricing/condition barriers.',priority:'HIGH',source:'OCCUPANCY',propertyId,targetResourceType:'Unit',targetResourceId:v.unitId,urgencyScore:85,financialImpact:v.revenueAtRisk,moneyAtRisk:v.revenueAtRisk,confidence:v.confidence,metadata:{currentVacancyDays:v.currentVacancyDays,predictedDaysToLease:v.predictedDaysToLease}});}
    if(revenue.revenueAtRisk>revenue.baselineMonthlyRevenue*.15){out.push({code:'REVENUE_AT_RISK',title:'Protect forecast revenue',reason:`Projected revenue at risk is ${revenue.revenueAtRisk} over the next ${revenue.horizonDays} days.`,recommendedAction:'Prioritize the largest vacancy, collection, and arrears exposures before discretionary work.',priority:revenue.revenueAtRisk>revenue.baselineMonthlyRevenue*.3?'CRITICAL':'HIGH',source:'FINANCE',propertyId,targetResourceType:'Property',targetResourceId:propertyId,urgencyScore:90,moneyAtRisk:revenue.revenueAtRisk,financialImpact:revenue.revenueAtRisk,confidence:revenue.confidence,metadata:{drivers:revenue.drivers}});}
    if(scoreVelocity<=-0.5||collectionVelocity<=-0.5||occupancyVelocity<=-0.5){out.push({code:'NEGATIVE_TREND_VELOCITY',title:'Reverse deteriorating property trend',reason:`Health velocity is ${round(scoreVelocity)} points/day, collection velocity ${round(collectionVelocity)} pp/day, and occupancy velocity ${round(occupancyVelocity)} pp/day.`,recommendedAction:'Open a management review and address the leading financial/operational driver.',priority:scoreVelocity<=-1?'HIGH':'MEDIUM',source:'ANOMALY',propertyId,targetResourceType:'Property',targetResourceId:propertyId,urgencyScore:70,moneyAtRisk:revenue.revenueAtRisk,financialImpact:revenue.revenueAtRisk,confidence:.82,metadata:{scoreVelocity,collectionVelocity,occupancyVelocity}});}
    return out;
  }

  private static async upsertAction(organizationId:Types.ObjectId,candidate:ReturnType<typeof DecisionAutomationService.buildCandidates>[number],escalationAfterMinutes:number){
    const now=new Date();const existing=await LandlordAction.findOne({organizationId,propertyId:candidate.propertyId,code:candidate.code,status:{$in:['OPEN','ACKNOWLEDGED','IN_PROGRESS']},targetResourceId:candidate.targetResourceId});
    if(!existing){const action=await LandlordAction.create({...candidate,organizationId,detectedAt:now,lastEvaluatedAt:now,escalationLevel:0});return {action,created:true,escalated:false,notify:true};}
    const age=now.getTime()-existing.detectedAt.getTime();let escalated=false;let level=existing.escalationLevel??0;if(age>=escalationAfterMinutes*60_000&&level<3){level++;escalated=true;existing.escalationLevel=level;existing.escalatedAt=now;existing.priority=priorityFromRank(Math.min(4,priorityRank[existing.priority as Priority]+(level>=2?1:0)));}
    existing.reason=candidate.reason;existing.recommendedAction=candidate.recommendedAction;existing.urgencyScore=candidate.urgencyScore;existing.financialImpact=candidate.financialImpact;existing.moneyAtRisk=candidate.moneyAtRisk;existing.confidence=candidate.confidence;existing.lastEvaluatedAt=now;existing.metadata=new Map(Object.entries(candidate.metadata));await existing.save();return {action:existing,created:false,escalated,notify:escalated};
  }

  private static async notifyLandlords(organizationId:Types.ObjectId,action:Awaited<ReturnType<typeof LandlordAction.findOne>> & NonNullable<unknown>,max:number){const roleIds=await Role.find({key:'LANDLORD',system:true}).distinct('_id');const members=await OrganizationMembership.find({organizationId,status:'ACTIVE',roleIds:{$in:roleIds}}).select('userId').limit(max).lean();let count=0;for(const member of members){const n=await NotificationService.systemEnqueue({organizationId,recipientUserId:member.userId,channel:'IN_APP',type:'decision-automation.action',title:action.priority==='CRITICAL'?'Critical portfolio action':'Portfolio action requires attention',body:`${action.title}: ${action.reason}`,priority:action.priority==='CRITICAL'?'URGENT':action.priority==='HIGH'?'HIGH':'NORMAL',data:{actionId:String(action._id),propertyId:String(action.propertyId),code:action.code,moneyAtRisk:action.moneyAtRisk,escalationLevel:action.escalationLevel},dedupeKey:`landlord-action:${action._id.toString()}:recipient:${member.userId.toString()}:level:${action.escalationLevel}`});if(n){await Job.create({organizationId,type:'notification.send',payload:{notificationId:String(n._id)},availableAt:new Date(),priority:action.priority==='CRITICAL'?10:action.priority==='HIGH'?5:0,maxAttempts:5,dedupeKey:`notification:${n._id.toString()}`});count++;}}return count;}

  private static async calculateTenantRisks(organizationId:Types.ObjectId,propertyId:Types.ObjectId,asOf:Date,createdBy?:Types.ObjectId){
    const tenancies=(await Tenancy.find({organizationId,propertyId,status:{$in:['ACTIVE','NOTICE']}}).lean()) as unknown as TenancyLike[];const out:RiskLike[]=[];
    for(const t of tenancies){const charges=await RentCharge.find({organizationId,tenancyId:t._id,periodStart:{$lte:asOf},status:{$ne:'VOID'}}).sort({periodStart:-1}).limit(12).lean();const arrears=await ArrearsCase.find({organizationId,tenantId:t.tenantId,status:{$in:['OPEN','CONTACTED','PROMISED','ESCALATED']}}).lean();const outstanding=Math.max(0,arrears.reduce((s,a)=>s+a.amountOutstanding,0)+charges.reduce((s,c)=>s+c.balanceAmount,0));const obligation=Math.max(t.monthlyRent+t.serviceCharge,1);const overdueCharges=charges.filter(c=>c.balanceAmount>0&&c.dueDate<asOf);const daysPastDue=overdueCharges.length?Math.max(...overdueCharges.map(c=>Math.max(0,Math.floor((asOf.getTime()-c.dueDate.getTime())/DAY)))):0;const consistency=charges.length?clamp(charges.reduce((s,c)=>s+(c.totalAmount<=0?1:c.paidAmount/c.totalAmount),0)/charges.length*100,0,100):100;const arrearsRatio=clamp(outstanding/obligation,0,3);const score=round(clamp(arrearsRatio*35+clamp(daysPastDue/90,0,1)*25+(100-consistency)*.3+(t.status==='NOTICE'?15:0),0,100));const probability=round(clamp(score/100*.92,0,0.99));const grade=score>=80?'CRITICAL':score>=60?'HIGH':score>=35?'MODERATE':'LOW';const velocity=await this.tenantArrearsVelocity(organizationId,t.tenantId,asOf);const drivers=[{code:'OUTSTANDING',label:'Outstanding balance',impact:round(arrearsRatio*35)},{code:'DAYS_PAST_DUE',label:'Days past due',impact:round(clamp(daysPastDue/90,0,1)*25)},{code:'PAYMENT_CONSISTENCY',label:'Payment consistency',impact:round((100-consistency)*.3)}];if(t.status==='NOTICE')drivers.push({code:'NOTICE',label:'Tenancy is under notice',impact:15});if(velocity<0)drivers.push({code:'ARREARS_VELOCITY',label:'Arrears are worsening',impact:round(Math.abs(velocity))});const confidence=round(clamp(.45+charges.length*.04+(arrears.length?0.1:0),.45,.9));await PredictiveObservation.create({organizationId,entityType:'TENANT',entityId:t.tenantId,observationAt:asOf,modelDomain:'ARREARS',modelVersion:MODEL_VERSION,features:{outstandingRatio:arrearsRatio,daysPastDue,paymentConsistency:consistency,notice:t.status==='NOTICE'?1:0,arrearsVelocity:velocity},prediction:probability,confidence,labelStatus:'PENDING'});const doc=await TenantArrearsRisk.findOneAndUpdate({organizationId,tenancyId:t._id},{organizationId,propertyId,buildingId:t.buildingId,floorId:t.floorId,unitId:t.unitId,tenantId:t.tenantId,tenancyId:t._id,asOf,score,grade,probability,outstandingAmount:outstanding,monthlyObligation:obligation,daysPastDue,paymentConsistency:round(consistency),trendVelocity:round(velocity),drivers,confidence,modelVersion:MODEL_VERSION,...(createdBy?{createdBy}: {})},{new:true,upsert:true,setDefaultsOnInsert:true});out.push(doc!.toObject());}
    return out;
  }

  private static async tenantArrearsVelocity(organizationId:Types.ObjectId,tenantId:Types.ObjectId,asOf:Date){const charges=await RentCharge.find({organizationId,tenantId,periodStart:{$lte:asOf},status:{$ne:'VOID'}}).sort({periodStart:-1}).limit(6).lean();return slope(charges.slice().reverse().map(c=>({time:c.periodStart.getTime(),value:c.balanceAmount})));}

  private static async forecastVacancies(organizationId:Types.ObjectId,propertyId:Types.ObjectId,units:UnitLike[],asOf:Date,createdBy?:Types.ObjectId){
    const all=await Tenancy.find({organizationId,propertyId}).sort({unitId:1,startDate:1}).lean();
    const byUnit=new Map<string,TenancyLike[]>();
    for(const tenancy of all){const t=tenancy as unknown as TenancyLike;const key=String(t.unitId);const arr=byUnit.get(key)??[];arr.push(t);byUnit.set(key,arr);}
    const results:VacancyLike[]=[];
    for(const u of units.filter(x=>x.status==='VACANT')){
      const ts=byUnit.get(String(u._id))??[];const durations:number[]=[];
      for(let i=1;i<ts.length;i++){const prev=ts[i-1]!;const curr=ts[i]!;const end=prev.movedOutAt??prev.endDate;if(end&&curr.startDate>end)durations.push((curr.startDate.getTime()-end.getTime())/DAY);}
      const ended=ts.filter(t=>{const end=t.movedOutAt??t.endDate;return Boolean(end&&end.getTime()<=asOf.getTime());});
      const last=ended.sort((a,b)=>(b.movedOutAt??b.endDate)!.getTime()-(a.movedOutAt??a.endDate)!.getTime())[0];
      const start=last?(last.movedOutAt??last.endDate)!:u.updatedAt;const current=Math.max(0,(asOf.getTime()-start.getTime())/DAY);const med=median(durations)||30;
      const occupancy=await Unit.countDocuments({organizationId,propertyId,status:'OCCUPIED'});const total=await Unit.countDocuments({organizationId,propertyId,status:{$ne:'INACTIVE'}});const occupancyRate=total?occupancy/total:0.5;const pressure=occupancyRate<.8?1.2:occupancyRate>.95?.9:1;const predicted=Math.max(current,med*pressure);const revenue=u.monthlyRent*predicted/30;const confidence=round(clamp(.35+Math.min(.45,durations.length*.05),.35,.8));
      const doc=await VacancyForecast.findOneAndUpdate({organizationId,unitId:u._id},{organizationId,propertyId,buildingId:u.buildingId,floorId:u.floorId,unitId:u._id,asOf,currentVacancyDays:round(current),historicalMedianDays:round(med),historicalSampleSize:durations.length,predictedDaysToLease:round(predicted),predictedLeaseDate:new Date(asOf.getTime()+predicted*DAY),monthlyRent:u.monthlyRent,revenueAtRisk:round(revenue),confidence,modelVersion:MODEL_VERSION,drivers:[{code:'HISTORICAL_VACANCY',label:'Historical median vacancy',impact:round(med)},{code:'OCCUPANCY_PRESSURE',label:'Portfolio occupancy pressure',impact:round((1-occupancyRate)*100)}],...(createdBy?{createdBy}: {})},{new:true,upsert:true,setDefaultsOnInsert:true});
      results.push(doc!.toObject());await PredictiveObservation.create({organizationId,entityType:'UNIT',entityId:u._id,observationAt:asOf,modelDomain:'VACANCY',modelVersion:MODEL_VERSION,features:{currentVacancyDays:current,historicalMedianDays:med,occupancyRate},prediction:predicted,confidence,labelStatus:'PENDING'});
    }
    return results;
  }

  private static async forecastRevenue(organizationId:Types.ObjectId,propertyId:Types.ObjectId,latest:HealthSnapshotLike,healthVelocity:number,tenantRisks:RiskLike[],vacancies:VacancyLike[],horizonDays:number,asOf:Date,createdBy?:Types.ObjectId){const tenancies=await Tenancy.find({organizationId,propertyId,status:{$in:['ACTIVE','NOTICE']}}).select('monthlyRent serviceCharge').lean();const units=await Unit.find({organizationId,propertyId,status:{$ne:'INACTIVE'}}).select('monthlyRent status').lean();const activeMonthly=tenancies.reduce((s,t)=>s+t.monthlyRent+t.serviceCharge,0);const vacancyAmount=vacancies.reduce((s,v)=>s+v.revenueAtRisk,0);const baseline=units.reduce((s,u)=>s+u.monthlyRent,0);const metrics=latest.metrics;
    const metricNumber=(key:string, fallback=0)=>Number(metrics[key]??fallback);const collectionRate=clamp(Number(metricNumber('collectionRate',100)??100)/100,0,1);const months=horizonDays/30;const arrearsRisk=tenantRisks.reduce((s,r)=>s+r.outstandingAmount*r.probability,0);const collectionRisk=activeMonthly*months*(1-collectionRate);const maintenanceRisk=Number(metricNumber('maintenanceSpend')??0)*clamp(1+Math.abs(Math.min(0,healthVelocity))*10,1,2)*.15;const total=round(Math.max(0,vacancyAmount+arrearsRisk+collectionRisk+maintenanceRisk));const expected=round(Math.max(0,baseline*months-total));const confidence=round(clamp(.5+Math.min(.3,tenantRisks.length*.01)+Math.min(.15,vacancies.length*.03),.5,.9));const drivers=[{code:'VACANCY',label:'Vacancy opportunity cost',impact:round(vacancyAmount)},{code:'ARREARS',label:'Risk-adjusted tenant arrears',impact:round(arrearsRisk)},{code:'COLLECTION',label:'Collection-rate shortfall',impact:round(collectionRisk)},{code:'MAINTENANCE',label:'Risk-adjusted maintenance exposure',impact:round(maintenanceRisk)}];await RevenueRiskForecast.create({organizationId,propertyId,asOf,horizonDays,baselineMonthlyRevenue:round(baseline),expectedRevenue:expected,revenueAtRisk:total,vacancyRiskAmount:round(vacancyAmount),arrearsRiskAmount:round(arrearsRisk),collectionRiskAmount:round(collectionRisk),maintenanceRiskAmount:round(maintenanceRisk),healthVelocity:round(healthVelocity),confidence,modelVersion:MODEL_VERSION,drivers,...(createdBy?{createdBy}: {})});await PredictiveObservation.create({organizationId,entityType:'PROPERTY',entityId:propertyId,observationAt:asOf,modelDomain:'REVENUE',modelVersion:MODEL_VERSION,features:{baselineMonthlyRevenue:baseline,collectionRate,healthVelocity,vacancyRiskAmount:vacancyAmount,arrearsRiskAmount:arrearsRisk},prediction:total,confidence,labelStatus:'PENDING'});return {horizonDays,baselineMonthlyRevenue:round(baseline),expectedRevenue:expected,revenueAtRisk:total,vacancyRiskAmount:round(vacancyAmount),arrearsRiskAmount:round(arrearsRisk),collectionRiskAmount:round(collectionRisk),maintenanceRiskAmount:round(maintenanceRisk),healthVelocity:round(healthVelocity),confidence,drivers};}

  static async overview(auth:AuthenticatedUser,organizationId:string,input:PeriodInput){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'decision-automation.view',org);const props=await this.visibleProperties(auth,org,input.propertyId);const ids=props.map(p=>p._id);const actions=await LandlordAction.find({organizationId:org,propertyId:{$in:ids},status:{$in:['OPEN','ACKNOWLEDGED','IN_PROGRESS']}}).sort({priority:-1,urgencyScore:-1,moneyAtRisk:-1}).limit(100).lean();const risks=await TenantArrearsRisk.find({organizationId:org,propertyId:{$in:ids}}).sort({asOf:-1,score:-1}).limit(100).lean();const forecasts=await VacancyForecast.find({organizationId:org,propertyId:{$in:ids}}).sort({asOf:-1,revenueAtRisk:-1}).limit(100).lean();const revenue=await RevenueRiskForecast.find({organizationId:org,propertyId:{$in:ids}}).sort({asOf:-1,revenueAtRisk:-1}).limit(100).lean();const latestByProperty=new Map<string,RevenueForecastLike>();for(const r of revenue)if(!latestByProperty.has(String(r.propertyId)))latestByProperty.set(String(r.propertyId),r);return {asOf:new Date(),modelVersion:MODEL_VERSION,portfolio:{propertyCount:props.length,openActions:actions.length,criticalActions:actions.filter(a=>a.priority==='CRITICAL').length,totalMoneyAtRisk:round(actions.reduce((s,a)=>s+a.moneyAtRisk,0)),highRiskTenants:risks.filter(r=>r.grade==='HIGH'||r.grade==='CRITICAL').length,prolongedVacancies:forecasts.filter(v=>v.predictedDaysToLease>=60).length},trendVelocity:await this.portfolioVelocity(org,ids),actions,tenantRisks:risks,vacancyForecasts:forecasts,revenueForecasts:[...latestByProperty.values()]};}

  private static async portfolioVelocity(org:Types.ObjectId,propertyIds:Types.ObjectId[]){const rows=await PropertyHealthSnapshot.find({organizationId:org,propertyId:{$in:propertyIds}}).sort({asOf:-1}).limit(500).lean();const by=new Map<string,HealthSnapshotLike[]>();for(const r of rows){const a=by.get(String(r.propertyId))??[];if(a.length<12)a.push(r);by.set(String(r.propertyId),a);}const values=[...by.values()].map(h=>slope(h.slice().reverse().map(x=>({time:x.asOf.getTime(),value:x.score}))));return {healthScoreVelocity:round(values.length?values.reduce((a,b)=>a+b,0)/values.length:0),propertiesWithNegativeVelocity:values.filter(v=>v<0).length,propertyCount:values.length};}

  static async listActions(auth:AuthenticatedUser,organizationId:string,q:ActionQuery){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'decision-automation.action.view',org);const props=await this.visibleProperties(auth,org,q.propertyId);return LandlordAction.find({organizationId:org,propertyId:{$in:props.map(p=>p._id)},...(q.status?{status:q.status}:{}),...(q.priority?{priority:q.priority}:{})}).sort({priority:-1,urgencyScore:-1,moneyAtRisk:-1,detectedAt:1}).limit(q.limit).lean();}
  static async updateAction(auth:AuthenticatedUser,id:string,status:'ACKNOWLEDGED'|'IN_PROGRESS'|'RESOLVED'|'DISMISSED'){const action=await LandlordAction.findById(id);if(!action)throw new AppError(404,'ACTION_NOT_FOUND','Action not found');AuthorizationService.assertCan(auth,'decision-automation.action.manage',{organizationId:action.organizationId,propertyId:action.propertyId});const now=new Date();action.status=status;if(status==='ACKNOWLEDGED')action.acknowledgedAt=now;else if(status==='RESOLVED'||status==='DISMISSED')action.resolvedAt=now;if(status==='RESOLVED'||status==='DISMISSED')action.resolvedBy=auth.userId;await action.save();await AuditService.record({organizationId:action.organizationId,actorUserId:auth.userId,action:`decision-automation.action.${status.toLowerCase()}`,resourceType:'LandlordAction',resourceId:action._id,propertyId:action.propertyId,after:action.toObject()});return action;}
  static async listTenantRisks(auth:AuthenticatedUser,organizationId:string,q:TenantRiskQuery){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'decision-automation.tenant-risk.view',org);const props=await this.visibleProperties(auth,org,q.propertyId);return TenantArrearsRisk.find({organizationId:org,propertyId:{$in:props.map(p=>p._id)},...(q.grade?{grade:q.grade}: {})}).sort({score:-1,asOf:-1}).limit(q.limit).lean();}
  static async listVacancyForecasts(auth:AuthenticatedUser,organizationId:string,q:VacancyQuery){const org=oid(organizationId);AuthorizationService.assertPermission(auth,'decision-automation.vacancy.view',org);const props=await this.visibleProperties(auth,org,q.propertyId);return VacancyForecast.find({organizationId:org,propertyId:{$in:props.map(p=>p._id)}}).sort({revenueAtRisk:-1,asOf:-1}).limit(q.limit).lean();}
}
